/*
 * Copyright 2026 Stanislav Aleshin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ru.aleshin.features.overview.impl.presentation.theme.tokens

import androidx.compose.runtime.staticCompositionLocalOf
import ru.aleshin.timeplanner.core.ui.theme.tokens.TimePlannerLanguage

/**
 * @author Stanislav Aleshin on 18.02.2023.
 */
internal data class OverviewStrings(
    val topAppBarHomeTitle: String,
    val topAppBarOverviewTitle: String,
    val topAppBarMenuIconDesc: String,
    val dateDialogPickerHeadline: String,
    val dateDialogPickerTitle: String,
    val addTaskTitle: String,
    val navToBackTitle: String,
    val dialogCreateTitle: String,
    val otherError: String,
    val mainCategoryLabel: String,
    val subCategoryLabel: String,
    val priorityLabel: String,
    val subCategoryEmptyTitle: String,
    val noteTitle: String,
    val schedulesHeader: String,
    val realizedScheduleTitle: String,
    val accomplishmentScheduleTitle: String,
    val plannedScheduleTitle: String,
    val undefinedTasksHeader: String,
    val executeUndefinedTasksTitle: String,
    val currentTaskHeader: String,
    val noneTitle: String,
    val progressTitle: String,
    val taskDateChooserHeader: String,
    val taskDateChooserFieldLabel: String,
    val specifyDeadlineTitle: String,
    val deadlineLabel: String,
    val showAllSchedulesTitle: String,
    val sharedTasksDialogTitle: String,
    val sharedTasksDialogDesc: String,
    val sharedTasksCountFormat: String,
    val weekTimelineTitle: String,
    val freeTimeTitle: String,
    val workloadTitle: String,
    val tasksCountFormat: String,
    val openDayTitle: String,
    val showAllTasksTitle: String,
    val showLessTasksTitle: String,
    val noDeadlineTitle: String,
    val noScheduledTasksTitle: String,
    val selectedDayHeaderFormat: String,
    val metadataDivider: String,
    val goalsTitle: String,
    val addGoalIconDesc: String,
    val historyIconDesc: String,
    val emptyGoalsTitle: String,
    val goalDetailsTitle: String,
    val goalsHistoryTitle: String,
    val emptyHistoryTitle: String,
    val editGoalIconDesc: String,
    val deleteGoalTitle: String,
    val deleteGoalConfirmation: String,
    val actualTitle: String,
    val plannedTitle: String,
    val targetTitle: String,
    val remainingTitle: String,
    val scopeUnavailableTitle: String,
    val achievedTitle: String,
    val notAchievedTitle: String,
    val exceededTitle: String,
    val expiredTitle: String,
    val inProgressTitle: String,
    val deadlineIconDesc: String,
    val emptyGoalTasksTitle: String,
    val tasksUnit: String,
    val undoTitle: String,
    val goalDeletedMessage: String,
)

internal val russianOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Расписание",
    topAppBarOverviewTitle = "Обзор",
    topAppBarMenuIconDesc = "Открыть меню",
    dateDialogPickerHeadline = "Выберите дату",
    dateDialogPickerTitle = "Дневной план",
    addTaskTitle = "Добавить задачу",
    navToBackTitle = "Назад",
    dialogCreateTitle = "Создать",
    otherError = "Ошибка! Обратитесь к разработчику.",
    mainCategoryLabel = "Категория",
    subCategoryLabel = "Подкатегория",
    priorityLabel = "Приоритет",
    subCategoryEmptyTitle = "Отсутствует",
    noteTitle = "Заметка",
    schedulesHeader = "Расписания",
    realizedScheduleTitle = "Выполненное",
    accomplishmentScheduleTitle = "Текущее",
    plannedScheduleTitle = "В планах",
    undefinedTasksHeader = "Без времени",
    executeUndefinedTasksTitle = "Выполнить",
    currentTaskHeader = "Текущая задача",
    noneTitle = "Нету",
    progressTitle = "Прогресс",
    taskDateChooserHeader = "Выберите дату планирования",
    taskDateChooserFieldLabel = "Дата",
    specifyDeadlineTitle = "Указать",
    deadlineLabel = "Дедлайн",
    showAllSchedulesTitle = "Показать больше",
    sharedTasksDialogTitle = "Импорт задач",
    sharedTasksDialogDesc = "Проверьте задачи перед добавлением",
    sharedTasksCountFormat = "Задач: %s",
    weekTimelineTitle = "Неделя",
    freeTimeTitle = "Свободно",
    workloadTitle = "Загрузка",
    tasksCountFormat = "%s задач",
    openDayTitle = "Открыть день",
    showAllTasksTitle = "Показать все",
    showLessTasksTitle = "Свернуть",
    noDeadlineTitle = "Без дедлайна",
    noScheduledTasksTitle = "На этот день задач нет",
    selectedDayHeaderFormat = "%s · %s",
    metadataDivider = "·",
    goalsTitle = "Цели",
    addGoalIconDesc = "Добавить цель",
    historyIconDesc = "История целей",
    emptyGoalsTitle = "Целей пока нет",
    goalDetailsTitle = "Детали цели",
    goalsHistoryTitle = "История целей",
    emptyHistoryTitle = "Завершённых целей пока нет",
    editGoalIconDesc = "Редактировать цель",
    deleteGoalTitle = "Удалить цель",
    deleteGoalConfirmation = "Удалить эту цель? Завершённая история сохранится.",
    actualTitle = "Факт",
    plannedTitle = "Запланировано",
    targetTitle = "Цель",
    remainingTitle = "Осталось",
    scopeUnavailableTitle = "Выберите новую категорию, чтобы продолжить отслеживание",
    achievedTitle = "Выполнено",
    notAchievedTitle = "Не выполнено",
    exceededTitle = "Лимит превышен",
    expiredTitle = "Дедлайн истёк",
    inProgressTitle = "В процессе",
    deadlineIconDesc = "Дедлайн",
    emptyGoalTasksTitle = "Пока ни одна задача не влияет на эту цель",
    tasksUnit = "задач",
    undoTitle = "Отменить",
    goalDeletedMessage = "Цель удалена",
)

internal val englishOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Schedule",
    topAppBarOverviewTitle = "Overview",
    topAppBarMenuIconDesc = "Open menu",
    dateDialogPickerHeadline = "Select a date",
    dateDialogPickerTitle = "Daily plan",
    addTaskTitle = "Add a task",
    navToBackTitle = "Back",
    dialogCreateTitle = "Create",
    otherError = "Something went wrong. Contact the developer for help.",
    mainCategoryLabel = "Category",
    subCategoryLabel = "Subcategory",
    priorityLabel = "Priority",
    subCategoryEmptyTitle = "Absent",
    noteTitle = "Note",
    schedulesHeader = "Schedules",
    realizedScheduleTitle = "Completed",
    accomplishmentScheduleTitle = "Current",
    plannedScheduleTitle = "Planned",
    undefinedTasksHeader = "Unscheduled",
    executeUndefinedTasksTitle = "Execute",
    currentTaskHeader = "Current task",
    noneTitle = "None",
    progressTitle = "Progress",
    taskDateChooserHeader = "Select a planning date",
    taskDateChooserFieldLabel = "Date",
    specifyDeadlineTitle = "Specify",
    deadlineLabel = "Deadline",
    showAllSchedulesTitle = "Show more",
    sharedTasksDialogTitle = "Import tasks",
    sharedTasksDialogDesc = "Review shared tasks before adding them",
    sharedTasksCountFormat = "Tasks: %s",
    weekTimelineTitle = "Week timeline",
    freeTimeTitle = "Free time",
    workloadTitle = "Workload",
    tasksCountFormat = "%s tasks",
    openDayTitle = "Open day",
    showAllTasksTitle = "Show all",
    showLessTasksTitle = "Show less",
    noDeadlineTitle = "No deadline",
    noScheduledTasksTitle = "No tasks planned for this day",
    selectedDayHeaderFormat = "%s · %s",
    metadataDivider = "·",
    goalsTitle = "Goals",
    addGoalIconDesc = "Add goal",
    historyIconDesc = "Goal history",
    emptyGoalsTitle = "No goals yet",
    goalDetailsTitle = "Goal details",
    goalsHistoryTitle = "Goal history",
    emptyHistoryTitle = "No completed goals yet",
    editGoalIconDesc = "Edit goal",
    deleteGoalTitle = "Delete goal",
    deleteGoalConfirmation = "Delete this goal? Completed history will be kept.",
    actualTitle = "Actual",
    plannedTitle = "Planned",
    targetTitle = "Target",
    remainingTitle = "Remaining",
    scopeUnavailableTitle = "Choose a new category to continue tracking",
    achievedTitle = "Achieved",
    notAchievedTitle = "Not achieved",
    exceededTitle = "Limit exceeded",
    expiredTitle = "Deadline passed",
    inProgressTitle = "In progress",
    deadlineIconDesc = "Deadline",
    emptyGoalTasksTitle = "No tasks contribute to this goal yet",
    tasksUnit = "tasks",
    undoTitle = "Undo",
    goalDeletedMessage = "Goal deleted",
)

internal val persianOverviewString = OverviewStrings(
    topAppBarHomeTitle = "برنامه",
    topAppBarOverviewTitle = "نمای کلی",
    topAppBarMenuIconDesc = "بازکردن منو",
    dateDialogPickerHeadline = "انتخاب تاریخ",
    dateDialogPickerTitle = "برنامه ریز روزانه",
    addTaskTitle = "اضافه کردن یک کار",
    navToBackTitle = "بازگشت",
    dialogCreateTitle = "ایجاد",
    otherError = "خطا! با توسعه دهنده تماس بگیرید.",
    mainCategoryLabel = "دسته بندی",
    subCategoryLabel = "زیرمجموعه",
    priorityLabel = "اولویت ویژه",
    subCategoryEmptyTitle = "خالی",
    noteTitle = "یادداشت",
    schedulesHeader = "برنامه ها",
    realizedScheduleTitle = "تکمیل شده",
    accomplishmentScheduleTitle = "جریان",
    plannedScheduleTitle = "در برنامه ها",
    undefinedTasksHeader = "وظایف غیر توزیع شده",
    executeUndefinedTasksTitle = "برای انجام",
    currentTaskHeader = "وظیفه فعلی",
    noneTitle = "نه",
    progressTitle = "پیشرفت",
    taskDateChooserHeader = "تاریخ برنامه ریزی را انتخاب کنید",
    taskDateChooserFieldLabel = "تاریخ",
    specifyDeadlineTitle = "انتخاب کنید",
    deadlineLabel = "مهلت",
    showAllSchedulesTitle = "نمایش بیشتر",
    sharedTasksDialogTitle = "وارد کردن کارها",
    sharedTasksDialogDesc = "کارهای اشتراک‌گذاری‌شده را پیش از افزودن بررسی کنید",
    sharedTasksCountFormat = "کارها: %s",
    weekTimelineTitle = "نمای هفتگی",
    freeTimeTitle = "زمان آزاد",
    workloadTitle = "بار کاری",
    tasksCountFormat = "%s کار",
    openDayTitle = "باز کردن روز",
    showAllTasksTitle = "نمایش همه",
    showLessTasksTitle = "نمایش کمتر",
    noDeadlineTitle = "بدون مهلت",
    noScheduledTasksTitle = "برای این روز کاری برنامه‌ریزی نشده است",
    selectedDayHeaderFormat = "%s · %s",
    metadataDivider = "·",
    goalsTitle = "هدف‌ها",
    addGoalIconDesc = "افزودن هدف",
    historyIconDesc = "تاریخچه هدف‌ها",
    emptyGoalsTitle = "هنوز هدفی وجود ندارد",
    goalDetailsTitle = "جزئیات هدف",
    goalsHistoryTitle = "تاریخچه هدف‌ها",
    emptyHistoryTitle = "هنوز دوره تکمیل‌شده‌ای وجود ندارد",
    editGoalIconDesc = "ویرایش هدف",
    deleteGoalTitle = "حذف هدف",
    deleteGoalConfirmation = "این هدف حذف شود؟ تاریخچه تکمیل‌شده حفظ می‌شود.",
    actualTitle = "واقعی",
    plannedTitle = "برنامه‌ریزی‌شده",
    targetTitle = "هدف",
    remainingTitle = "باقی‌مانده",
    scopeUnavailableTitle = "برای ادامه پیگیری، دسته جدیدی انتخاب کنید",
    achievedTitle = "انجام شد",
    notAchievedTitle = "انجام نشد",
    exceededTitle = "از حد مجاز بیشتر",
    expiredTitle = "Deadline passed",
    inProgressTitle = "در حال انجام",
    deadlineIconDesc = "Deadline",
    emptyGoalTasksTitle = "No tasks contribute to this goal yet",
    tasksUnit = "کار",
    undoTitle = "واگرد",
    goalDeletedMessage = "هدف حذف شد",
)

internal val germanOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Zeitplan",
    topAppBarOverviewTitle = "Überblick",
    topAppBarMenuIconDesc = "Menü öffnen",
    dateDialogPickerHeadline = "Datum auswählen",
    dateDialogPickerTitle = "Tagesplan",
    addTaskTitle = "Aufgabe hinzufügen",
    navToBackTitle = "Zurück",
    dialogCreateTitle = "Erstellen",
    otherError = "Fehler! Wenden Sie sich an den Entwickler.",
    mainCategoryLabel = "Kategorie",
    subCategoryLabel = "Unterkategorie",
    priorityLabel = "Priorität",
    subCategoryEmptyTitle = "Leer",
    noteTitle = "Notiz",
    schedulesHeader = "Zeitpläne",
    realizedScheduleTitle = "Erledigt",
    accomplishmentScheduleTitle = "Aktuelles",
    plannedScheduleTitle = "Geplant",
    undefinedTasksHeader = "Nicht verteilte Aufgaben",
    executeUndefinedTasksTitle = "Erfüllen",
    currentTaskHeader = "aktive Aufgabe",
    noneTitle = "Keine",
    progressTitle = "Fortschritt",
    taskDateChooserHeader = "Wählen Sie ein Planungsdatum aus",
    taskDateChooserFieldLabel = "Datum",
    specifyDeadlineTitle = "Angeben",
    deadlineLabel = "Frist",
    showAllSchedulesTitle = "Mehr anzeigen",
    sharedTasksDialogTitle = "Aufgaben importieren",
    sharedTasksDialogDesc = "Prüfe die geteilten Aufgaben vor dem Hinzufügen",
    sharedTasksCountFormat = "Aufgaben: %s",
    weekTimelineTitle = "Wochenübersicht",
    freeTimeTitle = "Freie Zeit",
    workloadTitle = "Auslastung",
    tasksCountFormat = "%s Aufgaben",
    openDayTitle = "Tag öffnen",
    showAllTasksTitle = "Alle anzeigen",
    showLessTasksTitle = "Weniger anzeigen",
    noDeadlineTitle = "Keine Frist",
    noScheduledTasksTitle = "Keine Aufgaben für diesen Tag geplant",
    selectedDayHeaderFormat = "%s · %s",
    metadataDivider = "·",
    goalsTitle = "Ziele",
    addGoalIconDesc = "Ziel hinzufügen",
    historyIconDesc = "Zielverlauf",
    emptyGoalsTitle = "Noch keine Ziele",
    goalDetailsTitle = "Zieldetails",
    goalsHistoryTitle = "Zielverlauf",
    emptyHistoryTitle = "Noch keine abgeschlossenen Zeiträume",
    editGoalIconDesc = "Ziel bearbeiten",
    deleteGoalTitle = "Ziel löschen",
    deleteGoalConfirmation = "Dieses Ziel löschen? Der abgeschlossene Verlauf bleibt erhalten.",
    actualTitle = "Tatsächlich",
    plannedTitle = "Geplant",
    targetTitle = "Ziel",
    remainingTitle = "Verbleibend",
    scopeUnavailableTitle = "Wähle eine neue Kategorie, um die Erfassung fortzusetzen",
    achievedTitle = "Erreicht",
    notAchievedTitle = "Nicht erreicht",
    exceededTitle = "Limit überschritten",
    expiredTitle = "Deadline passed",
    inProgressTitle = "In Bearbeitung",
    deadlineIconDesc = "Deadline",
    emptyGoalTasksTitle = "No tasks contribute to this goal yet",
    tasksUnit = "Aufgaben",
    undoTitle = "Rückgängig",
    goalDeletedMessage = "Ziel gelöscht",
)

internal val spanishOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Horario",
    topAppBarOverviewTitle = "Visión general",
    topAppBarMenuIconDesc = "Abrir menú",
    dateDialogPickerHeadline = "Selecciona fecha",
    dateDialogPickerTitle = "Plan diario",
    addTaskTitle = "Añadir una tarea",
    navToBackTitle = "Volver",
    dialogCreateTitle = "Crear",
    otherError = "¡Error! Contacta al desarrollador.",
    mainCategoryLabel = "Categoría",
    subCategoryLabel = "Subcategoría",
    priorityLabel = "Prioridad",
    subCategoryEmptyTitle = "Ninguna",
    noteTitle = "Nota",
    schedulesHeader = "Horarios",
    realizedScheduleTitle = "Realizado",
    accomplishmentScheduleTitle = "Actual",
    plannedScheduleTitle = "En los planes",
    undefinedTasksHeader = "Tareas no distribuidas",
    executeUndefinedTasksTitle = "Ejecutar",
    currentTaskHeader = "Tarea actual",
    noneTitle = "No",
    progressTitle = "Progreso",
    taskDateChooserHeader = "Seleccione una fecha de planificación",
    taskDateChooserFieldLabel = "Fecha",
    specifyDeadlineTitle = "Especificar",
    deadlineLabel = "Fecha límite",
    showAllSchedulesTitle = "Mostrar más",
    sharedTasksDialogTitle = "Importar tareas",
    sharedTasksDialogDesc = "Revisa las tareas compartidas antes de añadirlas",
    sharedTasksCountFormat = "Tareas: %s",
    weekTimelineTitle = "Semana",
    freeTimeTitle = "Tiempo libre",
    workloadTitle = "Carga",
    tasksCountFormat = "%s tareas",
    openDayTitle = "Abrir día",
    showAllTasksTitle = "Mostrar todas",
    showLessTasksTitle = "Mostrar menos",
    noDeadlineTitle = "Sin fecha límite",
    noScheduledTasksTitle = "No hay tareas planificadas para este día",
    selectedDayHeaderFormat = "%s · %s",
    metadataDivider = "·",
    goalsTitle = "Objetivos",
    addGoalIconDesc = "Añadir objetivo",
    historyIconDesc = "Historial de objetivos",
    emptyGoalsTitle = "Aún no hay objetivos",
    goalDetailsTitle = "Detalles del objetivo",
    goalsHistoryTitle = "Historial de objetivos",
    emptyHistoryTitle = "Aún no hay periodos completados",
    editGoalIconDesc = "Editar objetivo",
    deleteGoalTitle = "Eliminar objetivo",
    deleteGoalConfirmation = "¿Eliminar este objetivo? Se conservará el historial completado.",
    actualTitle = "Real",
    plannedTitle = "Planificado",
    targetTitle = "Objetivo",
    remainingTitle = "Restante",
    scopeUnavailableTitle = "Elige una categoría nueva para continuar el seguimiento",
    achievedTitle = "Conseguido",
    notAchievedTitle = "No conseguido",
    exceededTitle = "Límite superado",
    expiredTitle = "Deadline passed",
    inProgressTitle = "En progreso",
    deadlineIconDesc = "Deadline",
    emptyGoalTasksTitle = "No tasks contribute to this goal yet",
    tasksUnit = "tareas",
    undoTitle = "Deshacer",
    goalDeletedMessage = "Objetivo eliminado",
)

internal val frenchOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Horaire",
    topAppBarOverviewTitle = "Vue d'Ensemble",
    topAppBarMenuIconDesc = "Ouvrir le menu",
    dateDialogPickerHeadline = "Selectionner une date",
    dateDialogPickerTitle = "Planning journalier",
    addTaskTitle = "Ajouter une tâche",
    navToBackTitle = "Retour",
    dialogCreateTitle = "Créer",
    otherError = "Erreur! Veuiller contacter le developpeur.",
    mainCategoryLabel = "Catégorie",
    subCategoryLabel = "Sous-catégorie",
    priorityLabel = "Priorité",
    subCategoryEmptyTitle = "Absent",
    noteTitle = "Note",
    schedulesHeader = "Horaires",
    realizedScheduleTitle = "Accompli",
    accomplishmentScheduleTitle = "Actuel",
    plannedScheduleTitle = "Dans les plans",
    undefinedTasksHeader = "Tâches non distribuées",
    executeUndefinedTasksTitle = "Exécuter",
    currentTaskHeader = "Tâche actuelle",
    noneTitle = "Non",
    progressTitle = "Progrès",
    taskDateChooserHeader = "Seleccione una fecha de planificación",
    taskDateChooserFieldLabel = "Fecha",
    specifyDeadlineTitle = "Précisez",
    deadlineLabel = "Date limite",
    showAllSchedulesTitle = "Voir plus",
    sharedTasksDialogTitle = "Importer des tâches",
    sharedTasksDialogDesc = "Vérifiez les tâches partagées avant de les ajouter",
    sharedTasksCountFormat = "Tâches : %s",
    weekTimelineTitle = "Semaine",
    freeTimeTitle = "Temps libre",
    workloadTitle = "Charge",
    tasksCountFormat = "%s tâches",
    openDayTitle = "Ouvrir le jour",
    showAllTasksTitle = "Tout afficher",
    showLessTasksTitle = "Afficher moins",
    noDeadlineTitle = "Sans échéance",
    noScheduledTasksTitle = "Aucune tâche prévue pour ce jour",
    selectedDayHeaderFormat = "%s · %s",
    metadataDivider = "·",
    goalsTitle = "Objectifs",
    addGoalIconDesc = "Ajouter un objectif",
    historyIconDesc = "Historique des objectifs",
    emptyGoalsTitle = "Aucun objectif pour le moment",
    goalDetailsTitle = "Détails de l’objectif",
    goalsHistoryTitle = "Historique des objectifs",
    emptyHistoryTitle = "Aucune période terminée",
    editGoalIconDesc = "Modifier l’objectif",
    deleteGoalTitle = "Supprimer l’objectif",
    deleteGoalConfirmation = "Supprimer cet objectif ? L’historique terminé sera conservé.",
    actualTitle = "Réel",
    plannedTitle = "Planifié",
    targetTitle = "Objectif",
    remainingTitle = "Restant",
    scopeUnavailableTitle = "Choisissez une nouvelle catégorie pour poursuivre le suivi",
    achievedTitle = "Atteint",
    notAchievedTitle = "Non atteint",
    exceededTitle = "Limite dépassée",
    expiredTitle = "Deadline passed",
    inProgressTitle = "En cours",
    deadlineIconDesc = "Deadline",
    emptyGoalTasksTitle = "No tasks contribute to this goal yet",
    tasksUnit = "tâches",
    undoTitle = "Annuler",
    goalDeletedMessage = "Objectif supprimé",
)
internal val brazilianPortugueseOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Horário",
    topAppBarMenuIconDesc = "Abrir menu",
    topAppBarOverviewTitle = "Visão geral",
    dateDialogPickerHeadline = "Selecione uma data",
    dateDialogPickerTitle = "Planejamento diário",
    addTaskTitle = "Adicionar tarefa",
    navToBackTitle = "Voltar",
    dialogCreateTitle = "Criar",
    otherError = "Erro! Contate o desenvolvedor.",
    mainCategoryLabel = "Categoria",
    subCategoryLabel = "Subcategoria",
    priorityLabel = "Prioridade",
    subCategoryEmptyTitle = "Faltou",
    noteTitle = "Nota",
    schedulesHeader = "Horário",
    realizedScheduleTitle = "Feito",
    accomplishmentScheduleTitle = "Atual",
    plannedScheduleTitle = "Nos planos",
    undefinedTasksHeader = "Tarefas não distribuídas",
    executeUndefinedTasksTitle = "Para executar",
    currentTaskHeader = "Tarefa atual",
    noneTitle = "No",
    progressTitle = "Progresso",
    taskDateChooserHeader = "Selecione uma data de planejamento",
    taskDateChooserFieldLabel = "Data",
    specifyDeadlineTitle = "Apontar",
    deadlineLabel = "Prazo",
    showAllSchedulesTitle = "Mostrar mais",
    sharedTasksDialogTitle = "Importar tarefas",
    sharedTasksDialogDesc = "Revise as tarefas compartilhadas antes de adicionar",
    sharedTasksCountFormat = "Tarefas: %s",
    weekTimelineTitle = "Semana",
    freeTimeTitle = "Tempo livre",
    workloadTitle = "Carga",
    tasksCountFormat = "%s tarefas",
    openDayTitle = "Abrir dia",
    showAllTasksTitle = "Mostrar todas",
    showLessTasksTitle = "Mostrar menos",
    noDeadlineTitle = "Sem prazo",
    noScheduledTasksTitle = "Nenhuma tarefa planejada para este dia",
    selectedDayHeaderFormat = "%s · %s",
    metadataDivider = "·",
    goalsTitle = "Metas",
    addGoalIconDesc = "Adicionar meta",
    historyIconDesc = "Histórico de metas",
    emptyGoalsTitle = "Ainda não há metas",
    goalDetailsTitle = "Detalhes da meta",
    goalsHistoryTitle = "Histórico de metas",
    emptyHistoryTitle = "Ainda não há períodos concluídos",
    editGoalIconDesc = "Editar meta",
    deleteGoalTitle = "Excluir meta",
    deleteGoalConfirmation = "Excluir esta meta? O histórico concluído será mantido.",
    actualTitle = "Real",
    plannedTitle = "Planejado",
    targetTitle = "Meta",
    remainingTitle = "Restante",
    scopeUnavailableTitle = "Escolha uma nova categoria para continuar acompanhando",
    achievedTitle = "Alcançada",
    notAchievedTitle = "Não alcançada",
    exceededTitle = "Limite excedido",
    expiredTitle = "Deadline passed",
    inProgressTitle = "Em andamento",
    deadlineIconDesc = "Deadline",
    emptyGoalTasksTitle = "No tasks contribute to this goal yet",
    tasksUnit = "tarefas",
    undoTitle = "Desfazer",
    goalDeletedMessage = "Meta excluída",
)

internal val turkishOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Program",
    topAppBarOverviewTitle = "Genel Bakış",
    topAppBarMenuIconDesc = "Menüyü aç",
    dateDialogPickerHeadline = "Bir tarih seçin",
    dateDialogPickerTitle = "Günlük plan",
    addTaskTitle = "Görev ekle",
    navToBackTitle = "Geri",
    dialogCreateTitle = "Oluştur",
    otherError = "Hata! Geliştirici ile iletişime geçin.",
    mainCategoryLabel = "Kategori",
    subCategoryLabel = "Alt kategori",
    priorityLabel = "Öncelik",
    subCategoryEmptyTitle = "Yok",
    noteTitle = "Not",
    schedulesHeader = "Planlar",
    realizedScheduleTitle = "Tamamlandı",
    accomplishmentScheduleTitle = "Mevcut",
    plannedScheduleTitle = "Planlar içinde",
    undefinedTasksHeader = "Dağıtılmamış görevler",
    executeUndefinedTasksTitle = "Yürüt",
    currentTaskHeader = "Mevcut görev",
    noneTitle = "Hiçbiri",
    progressTitle = "İlerleme",
    taskDateChooserHeader = "Bir planlama tarihi seçin",
    taskDateChooserFieldLabel = "Tarih",
    specifyDeadlineTitle = "Belirt",
    deadlineLabel = "Son tarih",
    showAllSchedulesTitle = "Daha fazlasını göster",
    sharedTasksDialogTitle = "Görevleri içe aktar",
    sharedTasksDialogDesc = "Eklemeden önce paylaşılan görevleri gözden geçir",
    sharedTasksCountFormat = "Görevler: %s",
    weekTimelineTitle = "Hafta",
    freeTimeTitle = "Boş zaman",
    workloadTitle = "Yoğunluk",
    tasksCountFormat = "%s görev",
    openDayTitle = "Günü aç",
    showAllTasksTitle = "Tümünü göster",
    showLessTasksTitle = "Daha az göster",
    noDeadlineTitle = "Son tarih yok",
    noScheduledTasksTitle = "Bu gün için planlanmış görev yok",
    selectedDayHeaderFormat = "%s · %s",
    metadataDivider = "·",
    goalsTitle = "Hedefler",
    addGoalIconDesc = "Hedef ekle",
    historyIconDesc = "Hedef geçmişi",
    emptyGoalsTitle = "Henüz hedef yok",
    goalDetailsTitle = "Hedef ayrıntıları",
    goalsHistoryTitle = "Hedef geçmişi",
    emptyHistoryTitle = "Henüz tamamlanan dönem yok",
    editGoalIconDesc = "Hedefi düzenle",
    deleteGoalTitle = "Hedefi sil",
    deleteGoalConfirmation = "Bu hedef silinsin mi? Tamamlanan geçmiş korunacak.",
    actualTitle = "Gerçekleşen",
    plannedTitle = "Planlanan",
    targetTitle = "Hedef",
    remainingTitle = "Kalan",
    scopeUnavailableTitle = "Takibe devam etmek için yeni bir kategori seçin",
    achievedTitle = "Tamamlandı",
    notAchievedTitle = "Tamamlanmadı",
    exceededTitle = "Sınır aşıldı",
    expiredTitle = "Deadline passed",
    inProgressTitle = "Devam ediyor",
    deadlineIconDesc = "Deadline",
    emptyGoalTasksTitle = "No tasks contribute to this goal yet",
    tasksUnit = "görev",
    undoTitle = "Geri al",
    goalDeletedMessage = "Hedef silindi",
)

internal val vietnameseOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Lịch trình",
    topAppBarOverviewTitle = "Tổng quan",
    topAppBarMenuIconDesc = "Mở thực đơn",
    dateDialogPickerHeadline = "Chọn ngày",
    dateDialogPickerTitle = "Kế hoạch hàng ngày",
    addTaskTitle = "Thêm nhiệm vụ",
    navToBackTitle = "Quay lại",
    dialogCreateTitle = "Tạo",
    otherError = "Lỗi! Hãy liên hệ với nhà phát triển.",
    mainCategoryLabel = "Danh mục",
    subCategoryLabel = "Danh mục con",
    priorityLabel = "Ưu tiên",
    subCategoryEmptyTitle = "Vắng mặt",
    noteTitle = "Ghi chú",
    schedulesHeader = "Lịch trình",
    realizedScheduleTitle = "Hoàn thành",
    accomplishmentScheduleTitle = "Hiện tại",
    plannedScheduleTitle = "Trong kế hoạch",
    undefinedTasksHeader = "Nhiệm vụ không được phân phối",
    executeUndefinedTasksTitle = "Thi hành",
    currentTaskHeader = "Nhiệm vụ hiện tại",
    noneTitle = "Không có",
    progressTitle = "Tiến độ",
    taskDateChooserHeader = "Chọn ngày lập kế hoạch",
    taskDateChooserFieldLabel = "Ngày",
    specifyDeadlineTitle = "Chỉ định",
    deadlineLabel = "Hạn chót",
    showAllSchedulesTitle = "Hiển thị nhiều hơn",
    sharedTasksDialogTitle = "Nhập nhiệm vụ",
    sharedTasksDialogDesc = "Kiểm tra nhiệm vụ được chia sẻ trước khi thêm",
    sharedTasksCountFormat = "Nhiệm vụ: %s",
    weekTimelineTitle = "Tuần",
    freeTimeTitle = "Thời gian rảnh",
    workloadTitle = "Khối lượng",
    tasksCountFormat = "%s nhiệm vụ",
    openDayTitle = "Mở ngày",
    showAllTasksTitle = "Hiển thị tất cả",
    showLessTasksTitle = "Thu gọn",
    noDeadlineTitle = "Không có hạn chót",
    noScheduledTasksTitle = "Không có nhiệm vụ nào được lên lịch cho ngày này",
    selectedDayHeaderFormat = "%s · %s",
    metadataDivider = "·",
    goalsTitle = "Mục tiêu",
    addGoalIconDesc = "Thêm mục tiêu",
    historyIconDesc = "Lịch sử mục tiêu",
    emptyGoalsTitle = "Chưa có mục tiêu",
    goalDetailsTitle = "Chi tiết mục tiêu",
    goalsHistoryTitle = "Lịch sử mục tiêu",
    emptyHistoryTitle = "Chưa có giai đoạn hoàn tất",
    editGoalIconDesc = "Chỉnh sửa mục tiêu",
    deleteGoalTitle = "Xóa mục tiêu",
    deleteGoalConfirmation = "Xóa mục tiêu này? Lịch sử đã hoàn tất sẽ được giữ lại.",
    actualTitle = "Thực tế",
    plannedTitle = "Đã lên kế hoạch",
    targetTitle = "Mục tiêu",
    remainingTitle = "Còn lại",
    scopeUnavailableTitle = "Chọn danh mục mới để tiếp tục theo dõi",
    achievedTitle = "Đã đạt",
    notAchievedTitle = "Chưa đạt",
    exceededTitle = "Vượt giới hạn",
    expiredTitle = "Deadline passed",
    inProgressTitle = "Đang thực hiện",
    deadlineIconDesc = "Deadline",
    emptyGoalTasksTitle = "No tasks contribute to this goal yet",
    tasksUnit = "nhiệm vụ",
    undoTitle = "Hoàn tác",
    goalDeletedMessage = "Đã xóa mục tiêu",
)

internal val polishOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Planer",
    topAppBarOverviewTitle = "Przegląd",
    topAppBarMenuIconDesc = "Otwórz menu",
    dateDialogPickerHeadline = "Wybierz datę",
    dateDialogPickerTitle = "Plan dzienny",
    addTaskTitle = "Dodaj zadanie",
    navToBackTitle = "Wróć",
    dialogCreateTitle = "Utwórz",
    otherError = "Coś poszło nie tak. Skontaktuj się z deweloperem by otrzymać pomoc.",
    mainCategoryLabel = "Kategoria",
    subCategoryLabel = "Podkategoria",
    priorityLabel = "Priorytet",
    subCategoryEmptyTitle = "Brak",
	noteTitle = "Notatka",
    schedulesHeader = "Harmonogramy",
    realizedScheduleTitle = "Ukończono",
    accomplishmentScheduleTitle = "Aktualnie",
    plannedScheduleTitle = "W planach",
    undefinedTasksHeader = "Zadania nierozmieszczone",
    executeUndefinedTasksTitle = "Wykonaj",
    currentTaskHeader = "Bieżące zadanie",
    noneTitle = "Brak",
    progressTitle = "Postęp",
    taskDateChooserHeader = "Wybierz datę planowania",
    taskDateChooserFieldLabel = "Data",
    specifyDeadlineTitle = "Określ",
    deadlineLabel = "Termin",
    showAllSchedulesTitle = "Pokaż więcej",
    sharedTasksDialogTitle = "Importuj zadania",
    sharedTasksDialogDesc = "Sprawdź udostępnione zadania przed dodaniem",
    sharedTasksCountFormat = "Zadania: %s",
    weekTimelineTitle = "Tydzień",
    freeTimeTitle = "Wolny czas",
    workloadTitle = "Obciążenie",
    tasksCountFormat = "%s zadań",
    openDayTitle = "Otwórz dzień",
    showAllTasksTitle = "Pokaż wszystkie",
    showLessTasksTitle = "Pokaż mniej",
    noDeadlineTitle = "Bez terminu",
    noScheduledTasksTitle = "Brak zadań zaplanowanych na ten dzień",
    selectedDayHeaderFormat = "%s · %s",
    metadataDivider = "·",
    goalsTitle = "Cele",
    addGoalIconDesc = "Dodaj cel",
    historyIconDesc = "Historia celów",
    emptyGoalsTitle = "Brak celów",
    goalDetailsTitle = "Szczegóły celu",
    goalsHistoryTitle = "Historia celów",
    emptyHistoryTitle = "Brak zakończonych okresów",
    editGoalIconDesc = "Edytuj cel",
    deleteGoalTitle = "Usuń cel",
    deleteGoalConfirmation = "Usunąć ten cel? Historia zakończonych okresów zostanie zachowana.",
    actualTitle = "Wykonano",
    plannedTitle = "Zaplanowano",
    targetTitle = "Cel",
    remainingTitle = "Pozostało",
    scopeUnavailableTitle = "Wybierz nową kategorię, aby kontynuować śledzenie",
    achievedTitle = "Osiągnięto",
    notAchievedTitle = "Nie osiągnięto",
    exceededTitle = "Limit przekroczony",
    expiredTitle = "Deadline passed",
    inProgressTitle = "W trakcie",
    deadlineIconDesc = "Deadline",
    emptyGoalTasksTitle = "No tasks contribute to this goal yet",
    tasksUnit = "zadania",
    undoTitle = "Cofnij",
    goalDeletedMessage = "Cel usunięty",
)

internal val italianOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Agenda",
    topAppBarOverviewTitle = "Panoramica",
    topAppBarMenuIconDesc = "Apri menu",
    dateDialogPickerHeadline = "Seleziona una data",
    dateDialogPickerTitle = "Pianificazione giornaliera",
    addTaskTitle = "Nuovo task",
    navToBackTitle = "Indietro",
    dialogCreateTitle = "Crea",
    otherError = "Qualcosa è andato storto. Contatta lo sviluppatore per ottenere assistenza.",
    mainCategoryLabel = "Categoria",
    subCategoryLabel = "Sottocategoria",
    priorityLabel = "Priorità",
    subCategoryEmptyTitle = "Assente",
    noteTitle = "Note",
    schedulesHeader = "Pianificazioni",
    realizedScheduleTitle = "Completate",
    accomplishmentScheduleTitle = "Corrente",
    plannedScheduleTitle = "Pianificati",
    undefinedTasksHeader = "Task non assegnati",
    executeUndefinedTasksTitle = "Esegui",
    currentTaskHeader = "Task corrente",
    noneTitle = "Niente",
    progressTitle = "Progressi",
    taskDateChooserHeader = "Seleziona una data",
    taskDateChooserFieldLabel = "Data",
    specifyDeadlineTitle = "Specificare",
    deadlineLabel = "Scadenza",
    showAllSchedulesTitle = "Mostra di più",
    sharedTasksDialogTitle = "Importa attività",
    sharedTasksDialogDesc = "Controlla le attività condivise prima di aggiungerle",
    sharedTasksCountFormat = "Attività: %s",
    weekTimelineTitle = "Settimana",
    freeTimeTitle = "Tempo libero",
    workloadTitle = "Carico",
    tasksCountFormat = "%s attività",
    openDayTitle = "Apri giorno",
    showAllTasksTitle = "Mostra tutte",
    showLessTasksTitle = "Mostra meno",
    noDeadlineTitle = "Nessuna scadenza",
    noScheduledTasksTitle = "Nessuna attività pianificata per questo giorno",
    selectedDayHeaderFormat = "%s · %s",
    metadataDivider = "·",
    goalsTitle = "Obiettivi",
    addGoalIconDesc = "Aggiungi obiettivo",
    historyIconDesc = "Cronologia obiettivi",
    emptyGoalsTitle = "Nessun obiettivo",
    goalDetailsTitle = "Dettagli obiettivo",
    goalsHistoryTitle = "Cronologia obiettivi",
    emptyHistoryTitle = "Nessun periodo completato",
    editGoalIconDesc = "Modifica obiettivo",
    deleteGoalTitle = "Elimina obiettivo",
    deleteGoalConfirmation = "Eliminare questo obiettivo? La cronologia completata sarà conservata.",
    actualTitle = "Effettivo",
    plannedTitle = "Pianificato",
    targetTitle = "Obiettivo",
    remainingTitle = "Rimanente",
    scopeUnavailableTitle = "Scegli una nuova categoria per continuare il monitoraggio",
    achievedTitle = "Raggiunto",
    notAchievedTitle = "Non raggiunto",
    exceededTitle = "Limite superato",
    expiredTitle = "Deadline passed",
    inProgressTitle = "In corso",
    deadlineIconDesc = "Deadline",
    emptyGoalTasksTitle = "No tasks contribute to this goal yet",
    tasksUnit = "attività",
    undoTitle = "Annulla",
    goalDeletedMessage = "Obiettivo eliminato",
)


internal val chineseOverviewString = OverviewStrings(
    topAppBarHomeTitle = "日程",
    topAppBarOverviewTitle = "概览",
    topAppBarMenuIconDesc = "打开菜单",
    dateDialogPickerHeadline = "选择日期",
    dateDialogPickerTitle = "每日计划",
    addTaskTitle = "添加任务",
    navToBackTitle = "返回",
    dialogCreateTitle = "创建",
    otherError = "出现问题。请联系开发者获取帮助。",
    mainCategoryLabel = "分类",
    subCategoryLabel = "子分类",
    priorityLabel = "优先级",
    subCategoryEmptyTitle = "无",
    noteTitle = "备注",
    schedulesHeader = "日程",
    realizedScheduleTitle = "已完成",
    accomplishmentScheduleTitle = "当前",
    plannedScheduleTitle = "计划中",
    undefinedTasksHeader = "未分配任务",
    executeUndefinedTasksTitle = "执行",
    currentTaskHeader = "当前任务",
    noneTitle = "无",
    progressTitle = "进度",
    taskDateChooserHeader = "选择计划日期",
    taskDateChooserFieldLabel = "日期",
    specifyDeadlineTitle = "指定",
    deadlineLabel = "截止时间",
    showAllSchedulesTitle = "显示更多",
    sharedTasksDialogTitle = "导入任务",
    sharedTasksDialogDesc = "添加前请检查分享的任务",
    sharedTasksCountFormat = "任务数：%s",
    weekTimelineTitle = "本周",
    freeTimeTitle = "空闲时间",
    workloadTitle = "负荷",
    tasksCountFormat = "%s 个任务",
    openDayTitle = "打开当天",
    showAllTasksTitle = "显示全部",
    showLessTasksTitle = "收起",
    noDeadlineTitle = "无截止时间",
    noScheduledTasksTitle = "当天没有计划任务",
    selectedDayHeaderFormat = "%s · %s",
    metadataDivider = "·",
    goalsTitle = "目标",
    addGoalIconDesc = "添加目标",
    historyIconDesc = "目标历史",
    emptyGoalsTitle = "暂无目标",
    goalDetailsTitle = "目标详情",
    goalsHistoryTitle = "目标历史",
    emptyHistoryTitle = "暂无已完成周期",
    editGoalIconDesc = "编辑目标",
    deleteGoalTitle = "删除目标",
    deleteGoalConfirmation = "删除此目标？已完成的历史记录将会保留。",
    actualTitle = "实际",
    plannedTitle = "计划",
    targetTitle = "目标",
    remainingTitle = "剩余",
    scopeUnavailableTitle = "请选择新分类以继续跟踪",
    achievedTitle = "已达成",
    notAchievedTitle = "未达成",
    exceededTitle = "超出限制",
    expiredTitle = "Deadline passed",
    inProgressTitle = "进行中",
    deadlineIconDesc = "Deadline",
    emptyGoalTasksTitle = "No tasks contribute to this goal yet",
    tasksUnit = "个任务",
    undoTitle = "撤销",
    goalDeletedMessage = "目标已删除",
)

internal val LocalOverviewStrings = staticCompositionLocalOf<OverviewStrings> {
    error("Overview Strings is not provided")
}

internal fun fetchOverviewStrings(language: TimePlannerLanguage) = when (language) {
    TimePlannerLanguage.EN -> englishOverviewString
    TimePlannerLanguage.RU -> russianOverviewString
    TimePlannerLanguage.DE -> germanOverviewString
    TimePlannerLanguage.ES -> spanishOverviewString
    TimePlannerLanguage.FA -> persianOverviewString
    TimePlannerLanguage.FR -> frenchOverviewString
    TimePlannerLanguage.PT_BR -> brazilianPortugueseOverviewString
    TimePlannerLanguage.TR -> turkishOverviewString
    TimePlannerLanguage.VN -> vietnameseOverviewString
    TimePlannerLanguage.PL -> polishOverviewString
    TimePlannerLanguage.IT -> italianOverviewString
    TimePlannerLanguage.ZH -> chineseOverviewString
}
