/*
 * Copyright 2026 Stanislav Aleshin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ru.aleshin.features.overview.impl.presentation.theme.tokens

import androidx.compose.runtime.staticCompositionLocalOf
import ru.aleshin.timeplanner.core.ui.theme.tokens.TimePlannerLanguage

/**
 * @author Stanislav Aleshin on 18.02.2023.
 */
internal data class OverviewStrings(
    val topAppBarHomeTitle: String,
    val topAppBarOverviewTitle: String,
    val topAppBarMenuIconDesc: String,
    val dateDialogPickerHeadline: String,
    val dateDialogPickerTitle: String,
    val addTaskTitle: String,
    val navToBackTitle: String,
    val dialogCreateTitle: String,
    val otherError: String,
    val mainCategoryLabel: String,
    val subCategoryLabel: String,
    val priorityLabel: String,
    val subCategoryEmptyTitle: String,
    val noteTitle: String,
    val schedulesHeader: String,
    val realizedScheduleTitle: String,
    val accomplishmentScheduleTitle: String,
    val plannedScheduleTitle: String,
    val undefinedTasksHeader: String,
    val executeUndefinedTasksTitle: String,
    val currentTaskHeader: String,
    val noneTitle: String,
    val progressTitle: String,
    val taskDateChooserHeader: String,
    val taskDateChooserFieldLabel: String,
    val specifyDeadlineTitle: String,
    val deadlineLabel: String,
    val showAllSchedulesTitle: String,
    val sharedTasksDialogTitle: String,
    val sharedTasksDialogDesc: String,
    val sharedTasksCountFormat: String,
)

internal val russianOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Расписание",
    topAppBarOverviewTitle = "Обзор",
    topAppBarMenuIconDesc = "Открыть меню",
    dateDialogPickerHeadline = "Выберите дату",
    dateDialogPickerTitle = "Дневной план",
    addTaskTitle = "Добавить задачу",
    navToBackTitle = "Назад",
    dialogCreateTitle = "Создать",
    otherError = "Ошибка! Обратитесь к разработчику.",
    mainCategoryLabel = "Категория",
    subCategoryLabel = "Подкатегория",
    priorityLabel = "Приоритет",
    subCategoryEmptyTitle = "Отсутствует",
    noteTitle = "Заметка",
    schedulesHeader = "Расписания",
    realizedScheduleTitle = "Выполненное",
    accomplishmentScheduleTitle = "Текущее",
    plannedScheduleTitle = "В планах",
    undefinedTasksHeader = "Не распределённые задачи",
    executeUndefinedTasksTitle = "Выполнить",
    currentTaskHeader = "Текущая задача",
    noneTitle = "Нету",
    progressTitle = "Прогресс",
    taskDateChooserHeader = "Выберите дату планирования",
    taskDateChooserFieldLabel = "Дата",
    specifyDeadlineTitle = "Указать",
    deadlineLabel = "Дедлайн",
    showAllSchedulesTitle = "Показать больше",
    sharedTasksDialogTitle = "Импорт задач",
    sharedTasksDialogDesc = "Проверьте задачи перед добавлением",
    sharedTasksCountFormat = "Задач: %s",
)

internal val englishOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Schedule",
    topAppBarOverviewTitle = "Overview",
    topAppBarMenuIconDesc = "Open menu",
    dateDialogPickerHeadline = "Select a date",
    dateDialogPickerTitle = "Daily plan",
    addTaskTitle = "Add a task",
    navToBackTitle = "Back",
    dialogCreateTitle = "Create",
    otherError = "Something went wrong. Contact the developer for help.",
    mainCategoryLabel = "Category",
    subCategoryLabel = "Subcategory",
    priorityLabel = "Priority",
    subCategoryEmptyTitle = "Absent",
    noteTitle = "Note",
    schedulesHeader = "Schedules",
    realizedScheduleTitle = "Completed",
    accomplishmentScheduleTitle = "Current",
    plannedScheduleTitle = "Planned",
    undefinedTasksHeader = "Undistributed tasks",
    executeUndefinedTasksTitle = "Execute",
    currentTaskHeader = "Current task",
    noneTitle = "None",
    progressTitle = "Progress",
    taskDateChooserHeader = "Select a planning date",
    taskDateChooserFieldLabel = "Date",
    specifyDeadlineTitle = "Specify",
    deadlineLabel = "Deadline",
    showAllSchedulesTitle = "Show more",
    sharedTasksDialogTitle = "Import tasks",
    sharedTasksDialogDesc = "Review shared tasks before adding them",
    sharedTasksCountFormat = "Tasks: %s",
)

internal val persianOverviewString = OverviewStrings(
    topAppBarHomeTitle = "برنامه",
    topAppBarOverviewTitle = "نمای کلی",
    topAppBarMenuIconDesc = "بازکردن منو",
    dateDialogPickerHeadline = "انتخاب تاریخ",
    dateDialogPickerTitle = "برنامه ریز روزانه",
    addTaskTitle = "اضافه کردن یک کار",
    navToBackTitle = "بازگشت",
    dialogCreateTitle = "ایجاد",
    otherError = "خطا! با توسعه دهنده تماس بگیرید.",
    mainCategoryLabel = "دسته بندی",
    subCategoryLabel = "زیرمجموعه",
    priorityLabel = "اولویت ویژه",
    subCategoryEmptyTitle = "خالی",
    noteTitle = "یادداشت",
    schedulesHeader = "برنامه ها",
    realizedScheduleTitle = "تکمیل شده",
    accomplishmentScheduleTitle = "جریان",
    plannedScheduleTitle = "در برنامه ها",
    undefinedTasksHeader = "وظایف غیر توزیع شده",
    executeUndefinedTasksTitle = "برای انجام",
    currentTaskHeader = "وظیفه فعلی",
    noneTitle = "نه",
    progressTitle = "پیشرفت",
    taskDateChooserHeader = "تاریخ برنامه ریزی را انتخاب کنید",
    taskDateChooserFieldLabel = "تاریخ",
    specifyDeadlineTitle = "انتخاب کنید",
    deadlineLabel = "مهلت",
    showAllSchedulesTitle = "نمایش بیشتر",
    sharedTasksDialogTitle = "وارد کردن کارها",
    sharedTasksDialogDesc = "کارهای اشتراک‌گذاری‌شده را پیش از افزودن بررسی کنید",
    sharedTasksCountFormat = "کارها: %s",
)

internal val germanOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Zeitplan",
    topAppBarOverviewTitle = "Überblick",
    topAppBarMenuIconDesc = "Menü öffnen",
    dateDialogPickerHeadline = "Datum auswählen",
    dateDialogPickerTitle = "Tagesplan",
    addTaskTitle = "Aufgabe hinzufügen",
    navToBackTitle = "Zurück",
    dialogCreateTitle = "Erstellen",
    otherError = "Fehler! Wenden Sie sich an den Entwickler.",
    mainCategoryLabel = "Kategorie",
    subCategoryLabel = "Unterkategorie",
    priorityLabel = "Priorität",
    subCategoryEmptyTitle = "Leer",
    noteTitle = "Notiz",
    schedulesHeader = "Zeitpläne",
    realizedScheduleTitle = "Erledigt",
    accomplishmentScheduleTitle = "Aktuelles",
    plannedScheduleTitle = "Geplant",
    undefinedTasksHeader = "Nicht verteilte Aufgaben",
    executeUndefinedTasksTitle = "Erfüllen",
    currentTaskHeader = "aktive Aufgabe",
    noneTitle = "Keine",
    progressTitle = "Fortschritt",
    taskDateChooserHeader = "Wählen Sie ein Planungsdatum aus",
    taskDateChooserFieldLabel = "Datum",
    specifyDeadlineTitle = "Angeben",
    deadlineLabel = "Frist",
    showAllSchedulesTitle = "Mehr anzeigen",
    sharedTasksDialogTitle = "Aufgaben importieren",
    sharedTasksDialogDesc = "Prüfe die geteilten Aufgaben vor dem Hinzufügen",
    sharedTasksCountFormat = "Aufgaben: %s",
)

internal val spanishOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Horario",
    topAppBarOverviewTitle = "Visión general",
    topAppBarMenuIconDesc = "Abrir menú",
    dateDialogPickerHeadline = "Selecciona fecha",
    dateDialogPickerTitle = "Plan diario",
    addTaskTitle = "Añadir una tarea",
    navToBackTitle = "Volver",
    dialogCreateTitle = "Crear",
    otherError = "¡Error! Contacta al desarrollador.",
    mainCategoryLabel = "Categoría",
    subCategoryLabel = "Subcategoría",
    priorityLabel = "Prioridad",
    subCategoryEmptyTitle = "Ninguna",
    noteTitle = "Nota",
    schedulesHeader = "Horarios",
    realizedScheduleTitle = "Realizado",
    accomplishmentScheduleTitle = "Actual",
    plannedScheduleTitle = "En los planes",
    undefinedTasksHeader = "Tareas no distribuidas",
    executeUndefinedTasksTitle = "Ejecutar",
    currentTaskHeader = "Tarea actual",
    noneTitle = "No",
    progressTitle = "Progreso",
    taskDateChooserHeader = "Seleccione una fecha de planificación",
    taskDateChooserFieldLabel = "Fecha",
    specifyDeadlineTitle = "Especificar",
    deadlineLabel = "Fecha límite",
    showAllSchedulesTitle = "Mostrar más",
    sharedTasksDialogTitle = "Importar tareas",
    sharedTasksDialogDesc = "Revisa las tareas compartidas antes de añadirlas",
    sharedTasksCountFormat = "Tareas: %s",
)

internal val frenchOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Horaire",
    topAppBarOverviewTitle = "Vue d'Ensemble",
    topAppBarMenuIconDesc = "Ouvrir le menu",
    dateDialogPickerHeadline = "Selectionner une date",
    dateDialogPickerTitle = "Planning journalier",
    addTaskTitle = "Ajouter une tâche",
    navToBackTitle = "Retour",
    dialogCreateTitle = "Créer",
    otherError = "Erreur! Veuiller contacter le developpeur.",
    mainCategoryLabel = "Catégorie",
    subCategoryLabel = "Sous-catégorie",
    priorityLabel = "Priorité",
    subCategoryEmptyTitle = "Absent",
    noteTitle = "Note",
    schedulesHeader = "Horaires",
    realizedScheduleTitle = "Accompli",
    accomplishmentScheduleTitle = "Actuel",
    plannedScheduleTitle = "Dans les plans",
    undefinedTasksHeader = "Tâches non distribuées",
    executeUndefinedTasksTitle = "Exécuter",
    currentTaskHeader = "Tâche actuelle",
    noneTitle = "Non",
    progressTitle = "Progrès",
    taskDateChooserHeader = "Seleccione una fecha de planificación",
    taskDateChooserFieldLabel = "Fecha",
    specifyDeadlineTitle = "Précisez",
    deadlineLabel = "Date limite",
    showAllSchedulesTitle = "Voir plus",
    sharedTasksDialogTitle = "Importer des tâches",
    sharedTasksDialogDesc = "Vérifiez les tâches partagées avant de les ajouter",
    sharedTasksCountFormat = "Tâches : %s",
)
internal val brazilianPortugueseOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Horário",
    topAppBarMenuIconDesc = "Abrir menu",
    topAppBarOverviewTitle = "Visão geral",
    dateDialogPickerHeadline = "Selecione uma data",
    dateDialogPickerTitle = "Planejamento diário",
    addTaskTitle = "Adicionar tarefa",
    navToBackTitle = "Voltar",
    dialogCreateTitle = "Criar",
    otherError = "Erro! Contate o desenvolvedor.",
    mainCategoryLabel = "Categoria",
    subCategoryLabel = "Subcategoria",
    priorityLabel = "Prioridade",
    subCategoryEmptyTitle = "Faltou",
    noteTitle = "Nota",
    schedulesHeader = "Horário",
    realizedScheduleTitle = "Feito",
    accomplishmentScheduleTitle = "Atual",
    plannedScheduleTitle = "Nos planos",
    undefinedTasksHeader = "Tarefas não distribuídas",
    executeUndefinedTasksTitle = "Para executar",
    currentTaskHeader = "Tarefa atual",
    noneTitle = "No",
    progressTitle = "Progresso",
    taskDateChooserHeader = "Selecione uma data de planejamento",
    taskDateChooserFieldLabel = "Data",
    specifyDeadlineTitle = "Apontar",
    deadlineLabel = "Prazo",
    showAllSchedulesTitle = "Mostrar mais",
    sharedTasksDialogTitle = "Importar tarefas",
    sharedTasksDialogDesc = "Revise as tarefas compartilhadas antes de adicionar",
    sharedTasksCountFormat = "Tarefas: %s",
)

internal val turkishOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Program",
    topAppBarOverviewTitle = "Genel Bakış",
    topAppBarMenuIconDesc = "Menüyü aç",
    dateDialogPickerHeadline = "Bir tarih seçin",
    dateDialogPickerTitle = "Günlük plan",
    addTaskTitle = "Görev ekle",
    navToBackTitle = "Geri",
    dialogCreateTitle = "Oluştur",
    otherError = "Hata! Geliştirici ile iletişime geçin.",
    mainCategoryLabel = "Kategori",
    subCategoryLabel = "Alt kategori",
    priorityLabel = "Öncelik",
    subCategoryEmptyTitle = "Yok",
    noteTitle = "Not",
    schedulesHeader = "Planlar",
    realizedScheduleTitle = "Tamamlandı",
    accomplishmentScheduleTitle = "Mevcut",
    plannedScheduleTitle = "Planlar içinde",
    undefinedTasksHeader = "Dağıtılmamış görevler",
    executeUndefinedTasksTitle = "Yürüt",
    currentTaskHeader = "Mevcut görev",
    noneTitle = "Hiçbiri",
    progressTitle = "İlerleme",
    taskDateChooserHeader = "Bir planlama tarihi seçin",
    taskDateChooserFieldLabel = "Tarih",
    specifyDeadlineTitle = "Belirt",
    deadlineLabel = "Son tarih",
    showAllSchedulesTitle = "Daha fazlasını göster",
    sharedTasksDialogTitle = "Görevleri içe aktar",
    sharedTasksDialogDesc = "Eklemeden önce paylaşılan görevleri gözden geçir",
    sharedTasksCountFormat = "Görevler: %s",
)

internal val vietnameseOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Lịch trình",
    topAppBarOverviewTitle = "Tổng quan",
    topAppBarMenuIconDesc = "Mở thực đơn",
    dateDialogPickerHeadline = "Chọn ngày",
    dateDialogPickerTitle = "Kế hoạch hàng ngày",
    addTaskTitle = "Thêm nhiệm vụ",
    navToBackTitle = "Quay lại",
    dialogCreateTitle = "Tạo",
    otherError = "Lỗi! Hãy liên hệ với nhà phát triển.",
    mainCategoryLabel = "Danh mục",
    subCategoryLabel = "Danh mục con",
    priorityLabel = "Ưu tiên",
    subCategoryEmptyTitle = "Vắng mặt",
    noteTitle = "Ghi chú",
    schedulesHeader = "Lịch trình",
    realizedScheduleTitle = "Hoàn thành",
    accomplishmentScheduleTitle = "Hiện tại",
    plannedScheduleTitle = "Trong kế hoạch",
    undefinedTasksHeader = "Nhiệm vụ không được phân phối",
    executeUndefinedTasksTitle = "Thi hành",
    currentTaskHeader = "Nhiệm vụ hiện tại",
    noneTitle = "Không có",
    progressTitle = "Tiến độ",
    taskDateChooserHeader = "Chọn ngày lập kế hoạch",
    taskDateChooserFieldLabel = "Ngày",
    specifyDeadlineTitle = "Chỉ định",
    deadlineLabel = "Hạn chót",
    showAllSchedulesTitle = "Hiển thị nhiều hơn",
    sharedTasksDialogTitle = "Nhập nhiệm vụ",
    sharedTasksDialogDesc = "Kiểm tra nhiệm vụ được chia sẻ trước khi thêm",
    sharedTasksCountFormat = "Nhiệm vụ: %s",
)

internal val polishOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Planer",
    topAppBarOverviewTitle = "Przegląd",
    topAppBarMenuIconDesc = "Otwórz menu",
    dateDialogPickerHeadline = "Wybierz datę",
    dateDialogPickerTitle = "Plan dzienny",
    addTaskTitle = "Dodaj zadanie",
    navToBackTitle = "Wróć",
    dialogCreateTitle = "Utwórz",
    otherError = "Coś poszło nie tak. Skontaktuj się z deweloperem by otrzymać pomoc.",
    mainCategoryLabel = "Kategoria",
    subCategoryLabel = "Podkategoria",
    priorityLabel = "Priorytet",
    subCategoryEmptyTitle = "Brak",
	noteTitle = "Notatka",
    schedulesHeader = "Harmonogramy",
    realizedScheduleTitle = "Ukończono",
    accomplishmentScheduleTitle = "Aktualnie",
    plannedScheduleTitle = "W planach",
    undefinedTasksHeader = "Zadania nierozmieszczone",
    executeUndefinedTasksTitle = "Wykonaj",
    currentTaskHeader = "Bieżące zadanie",
    noneTitle = "Brak",
    progressTitle = "Postęp",
    taskDateChooserHeader = "Wybierz datę planowania",
    taskDateChooserFieldLabel = "Data",
    specifyDeadlineTitle = "Określ",
    deadlineLabel = "Termin",
    showAllSchedulesTitle = "Pokaż więcej",
    sharedTasksDialogTitle = "Importuj zadania",
    sharedTasksDialogDesc = "Sprawdź udostępnione zadania przed dodaniem",
    sharedTasksCountFormat = "Zadania: %s",
)

internal val italianOverviewString = OverviewStrings(
    topAppBarHomeTitle = "Agenda",
    topAppBarOverviewTitle = "Panoramica",
    topAppBarMenuIconDesc = "Apri menu",
    dateDialogPickerHeadline = "Seleziona una data",
    dateDialogPickerTitle = "Pianificazione giornaliera",
    addTaskTitle = "Nuovo task",
    navToBackTitle = "Indietro",
    dialogCreateTitle = "Crea",
    otherError = "Qualcosa è andato storto. Contatta lo sviluppatore per ottenere assistenza.",
    mainCategoryLabel = "Categoria",
    subCategoryLabel = "Sottocategoria",
    priorityLabel = "Priorità",
    subCategoryEmptyTitle = "Assente",
    noteTitle = "Note",
    schedulesHeader = "Pianificazioni",
    realizedScheduleTitle = "Completate",
    accomplishmentScheduleTitle = "Corrente",
    plannedScheduleTitle = "Pianificati",
    undefinedTasksHeader = "Task non assegnati",
    executeUndefinedTasksTitle = "Esegui",
    currentTaskHeader = "Task corrente",
    noneTitle = "Niente",
    progressTitle = "Progressi",
    taskDateChooserHeader = "Seleziona una data",
    taskDateChooserFieldLabel = "Data",
    specifyDeadlineTitle = "Specificare",
    deadlineLabel = "Scadenza",
    showAllSchedulesTitle = "Mostra di più",
    sharedTasksDialogTitle = "Importa attività",
    sharedTasksDialogDesc = "Controlla le attività condivise prima di aggiungerle",
    sharedTasksCountFormat = "Attività: %s",
)


internal val chineseOverviewString = OverviewStrings(
    topAppBarHomeTitle = "日程",
    topAppBarOverviewTitle = "概览",
    topAppBarMenuIconDesc = "打开菜单",
    dateDialogPickerHeadline = "选择日期",
    dateDialogPickerTitle = "每日计划",
    addTaskTitle = "添加任务",
    navToBackTitle = "返回",
    dialogCreateTitle = "创建",
    otherError = "出现问题。请联系开发者获取帮助。",
    mainCategoryLabel = "分类",
    subCategoryLabel = "子分类",
    priorityLabel = "优先级",
    subCategoryEmptyTitle = "无",
    noteTitle = "备注",
    schedulesHeader = "日程",
    realizedScheduleTitle = "已完成",
    accomplishmentScheduleTitle = "当前",
    plannedScheduleTitle = "计划中",
    undefinedTasksHeader = "未分配任务",
    executeUndefinedTasksTitle = "执行",
    currentTaskHeader = "当前任务",
    noneTitle = "无",
    progressTitle = "进度",
    taskDateChooserHeader = "选择计划日期",
    taskDateChooserFieldLabel = "日期",
    specifyDeadlineTitle = "指定",
    deadlineLabel = "截止时间",
    showAllSchedulesTitle = "显示更多",
    sharedTasksDialogTitle = "导入任务",
    sharedTasksDialogDesc = "添加前请检查分享的任务",
    sharedTasksCountFormat = "任务数：%s",
)

internal val LocalOverviewStrings = staticCompositionLocalOf<OverviewStrings> {
    error("Overview Strings is not provided")
}

internal fun fetchOverviewStrings(language: TimePlannerLanguage) = when (language) {
    TimePlannerLanguage.EN -> englishOverviewString
    TimePlannerLanguage.RU -> russianOverviewString
    TimePlannerLanguage.DE -> germanOverviewString
    TimePlannerLanguage.ES -> spanishOverviewString
    TimePlannerLanguage.FA -> persianOverviewString
    TimePlannerLanguage.FR -> frenchOverviewString
    TimePlannerLanguage.PT_BR -> brazilianPortugueseOverviewString
    TimePlannerLanguage.TR -> turkishOverviewString
    TimePlannerLanguage.VN -> vietnameseOverviewString
    TimePlannerLanguage.PL -> polishOverviewString
    TimePlannerLanguage.IT -> italianOverviewString
    TimePlannerLanguage.ZH -> chineseOverviewString
}
