/*
 * Copyright 2026 Stanislav Aleshin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ru.aleshin.features.editor.impl.presentation.theme.tokens

import androidx.compose.runtime.staticCompositionLocalOf
import ru.aleshin.timeplanner.core.ui.theme.tokens.TimePlannerLanguage

/**
 * @author Stanislav Aleshin on 18.02.2023.
 */
internal data class EditorStrings(
    val topAppBarEditorTitle: String,
    val topAppBarCategoriesTitle: String,
    val topAppBarBackIconDesc: String,
    val topAppBarMenuIconDesc: String,
    val topAppBarTemplatesTitle: String,
    val mainCategoryChooserTitle: String,
    val subCategoryChooserTitle: String,
    val chooseCategoryTitle: String,
    val categoryNotSelectedTitle: String,
    val subCategoryDialogAddedTitle: String,
    val subCategoryDialogMainCategoryFormat: String,
    val mainCategoryTitle: String,
    val timeFieldStartLabel: String,
    val timeFieldEndLabel: String,
    val parameterChooserSwitchIconDesc: String,
    val timePickerHeader: String,
    val notifyParameterTitle: String,
    val notifyParameterDesc: String,
    val statisticsParameterTitle: String,
    val statisticsParameterDesc: String,
    val saveTaskButtonTitle: String,
    val cancelButtonTitle: String,
    val templateIconDesc: String,
    val topAppBarDeleteTitle: String,
    val categoryValidateError: String,
    val otherError: String,
    val startOverlayError: String,
    val endOverlayError: String,
    val fullOverlayError: String,
    val correctOverlayTitle: String,
    val durationPickerTitle: String,
    val templatesSheetTitle: String,
    val controlTitle: String,
    val applyTitle: String,
    val timeRangeFormat: String,
    val durationFormat: String,
    val notificationEnabledTitle: String,
    val notificationDisabledTitle: String,
    val emptyTemplatesTitle: String,
    val priorityParameterTitle: String,
    val noteLabel: String,
    val notePlaceholder: String,
    val undefinedTasksSheetTitle: String,
    val fifteenMinutesBeforeTitle: String,
    val oneHourBeforeTitle: String,
    val threeHourBeforeTitle: String,
    val oneDayBeforeTitle: String,
    val oneWeekBeforeTitle: String,
    val beforeEndTitle: String,
    val dialogCreateTitle: String,
    val categoryFieldLabel: String,
    val updateCategoryTitle: String,
    val deleteCategoryTitle: String,
    val subCategoryTitle: String,
    val warningDeleteCategoryText: String,
    val addCategoryTitle: String,
    val nameCategoryTitle: String,
    val restoreDefaultCategories: String,
)

internal val russianEditorString = EditorStrings(
    topAppBarEditorTitle = "Редактор",
    topAppBarCategoriesTitle = "Категории",
    topAppBarBackIconDesc = "Назад",
    topAppBarMenuIconDesc = "Открыть меню",
    topAppBarTemplatesTitle = "Шаблоны",
    mainCategoryChooserTitle = "Категория",
    subCategoryChooserTitle = "Подкатегория",
    chooseCategoryTitle = "Выбрать категорию",
    categoryNotSelectedTitle = "Отсутствует",
    subCategoryDialogAddedTitle = "Добавить",
    subCategoryDialogMainCategoryFormat = "Категория: %s",
    mainCategoryTitle = "Основная",
    timeFieldStartLabel = "Старт",
    timeFieldEndLabel = "Конец",
    parameterChooserSwitchIconDesc = "Установить параметр",
    timePickerHeader = "Выберите время",
    notifyParameterTitle = "Уведомления",
    notifyParameterDesc = "Отправить уведомление при выполнении задачи",
    statisticsParameterTitle = "Статистика",
    statisticsParameterDesc = "Учитывать данные в статистике",
    saveTaskButtonTitle = "Сохранить",
    cancelButtonTitle = "Отменить",
    templateIconDesc = "Добавить в шаблоны",
    topAppBarDeleteTitle = "Удалить",
    categoryValidateError = "* Выберите категорию",
    otherError = "Ошибка! Обратитесь к разработчику.",
    startOverlayError = "Конфликт! Наложение старта задачи.",
    endOverlayError = "Конфликт! Наложение конца задачи.",
    fullOverlayError = "Конфликт! Наложение задач.",
    correctOverlayTitle = "Исправить",
    durationPickerTitle = "Длительность",
    templatesSheetTitle = "Шаблоны",
    controlTitle = "Управлять",
    applyTitle = "Применить",
    timeRangeFormat = "Время: С %S до %s",
    durationFormat = "Длительность: %s",
    notificationEnabledTitle = "Уведомления: включены",
    notificationDisabledTitle = "Уведомления: выключены",
    emptyTemplatesTitle = "Список пуст",
    priorityParameterTitle = "Приоритет",
    noteLabel = "Заметка",
    notePlaceholder = "Небольшое примечание по желанию",
    undefinedTasksSheetTitle = "Не распределённые задачи",
    fifteenMinutesBeforeTitle = "За 15 мин. до начала",
    oneHourBeforeTitle = "За час до начала",
    threeHourBeforeTitle = "За два часа до начала",
    oneDayBeforeTitle = "За день до начала",
    oneWeekBeforeTitle = "За неделю до начала",
    beforeEndTitle = "Перед окончанием",
    dialogCreateTitle = "Создать",
    categoryFieldLabel = "Название",
    updateCategoryTitle = "Редактировать",
    deleteCategoryTitle = "Удалить",
    subCategoryTitle = "Подкатегории",
    warningDeleteCategoryText = "Вы уверены что хотите удалить основную категорию? " +
        "Данное действие приведёт к уничтожению всех ранее запланированных задач.",
    addCategoryTitle = "Добавить",
    nameCategoryTitle = "Название",
    restoreDefaultCategories = "Восстановить категории по умолчанию",
)

internal val englishEditorString = EditorStrings(
    topAppBarEditorTitle = "Editor",
    topAppBarCategoriesTitle = "Categories",
    topAppBarBackIconDesc = "Back",
    topAppBarMenuIconDesc = "Open menu",
    topAppBarTemplatesTitle = "Templates",
    mainCategoryChooserTitle = "Category",
    subCategoryChooserTitle = "Subcategory",
    chooseCategoryTitle = "Select a category",
    categoryNotSelectedTitle = "None",
    subCategoryDialogAddedTitle = "Add",
    subCategoryDialogMainCategoryFormat = "Category: %s",
    mainCategoryTitle = "Main",
    timeFieldStartLabel = "Start",
    timeFieldEndLabel = "End",
    parameterChooserSwitchIconDesc = "Set parameter",
    timePickerHeader = "Enter time",
    notifyParameterTitle = "Notifications",
    notifyParameterDesc = "Set a reminder for the task start",
    statisticsParameterTitle = "Statistics",
    statisticsParameterDesc = "Include in analytics",
    saveTaskButtonTitle = "Save",
    cancelButtonTitle = "Cancel",
    templateIconDesc = "Save as a template",
    topAppBarDeleteTitle = "Delete",
    categoryValidateError = "* Select a category",
    otherError = "Something went wrong. Contact the developer for help.",
    startOverlayError = "Conflict! Start time overlay",
    endOverlayError = "Conflict! End time overlay",
    fullOverlayError = "Conflict! Overlapping tasks",
    correctOverlayTitle = "Fix",
    durationPickerTitle = "Duration",
    templatesSheetTitle = "Templates",
    controlTitle = "Manage",
    applyTitle = "Apply",
    timeRangeFormat = "Time: from %S to %s",
    durationFormat = "Duration: %s",
    notificationEnabledTitle = "Notification: enabled",
    notificationDisabledTitle = "Notification: disabled",
    emptyTemplatesTitle = "List is empty",
    priorityParameterTitle = "Priority",
    noteLabel = "Note",
    notePlaceholder = "Optional",
    undefinedTasksSheetTitle = "Undistributed tasks",
    fifteenMinutesBeforeTitle = "15 mins before",
    oneHourBeforeTitle = "An hour before",
    threeHourBeforeTitle = "Two hours before",
    oneDayBeforeTitle = "A day before",
    oneWeekBeforeTitle = "A week before",
    beforeEndTitle = "Before completion",
    dialogCreateTitle = "Create",
    categoryFieldLabel = "Name",
    updateCategoryTitle = "Edit",
    deleteCategoryTitle = "Remove",
    subCategoryTitle = "Subcategories",
    warningDeleteCategoryText = "Are you sure you want to delete the main category? " +
        "This action will delete all previously scheduled tasks.",
    addCategoryTitle = "Add",
    nameCategoryTitle = "Name",
    restoreDefaultCategories = "Restore default categories",
)

internal val persianEditorString = EditorStrings(
    topAppBarEditorTitle = "ویرایشگر",
    topAppBarCategoriesTitle = "دسته بندی ها",
    topAppBarBackIconDesc = "بازگشت",
    topAppBarMenuIconDesc = "بازکردن منو",
    topAppBarTemplatesTitle = "قالب ها",
    mainCategoryChooserTitle = "دسته بندی",
    subCategoryChooserTitle = "زیرمجموعه",
    chooseCategoryTitle = "انتخاب دسته بندی",
    categoryNotSelectedTitle = "خالی",
    subCategoryDialogAddedTitle = "افزودن",
    subCategoryDialogMainCategoryFormat = "دسته بندی: %s",
    mainCategoryTitle = "اصلی",
    timeFieldStartLabel = "شرووع",
    timeFieldEndLabel = "پایان",
    parameterChooserSwitchIconDesc = "تنظیم پارامتر",
    timePickerHeader = "وارد کردن زمان",
    notifyParameterTitle = "اعلان ها",
    notifyParameterDesc = "هنگام تکمیل این کار، یک اعلان ارسال شود",
    statisticsParameterTitle = "آمارها",
    statisticsParameterDesc = "Include task in statistics",
    saveTaskButtonTitle = "دخیره",
    cancelButtonTitle = "لغو",
    templateIconDesc = "افزودن به قالب ها",
    topAppBarDeleteTitle = "حذف",
    categoryValidateError = "* انتخاب دسته بندی",
    otherError = "خطا! با توسعه دهنده تماس بگیرید.",
    startOverlayError = "تداخل! همپوشانی کردن شروع وظیفه",
    endOverlayError = "تداخل! همپوشانی کردن پایان وظیفه",
    fullOverlayError = "تداخل! وظایف همپوشانی دارند.",
    correctOverlayTitle = "تصحیح",
    durationPickerTitle = "مدت زمان",
    templatesSheetTitle = "قالب ها",
    controlTitle = "مدیریت",
    applyTitle = "اعمال",
    timeRangeFormat = "زمان: از %S تا %s",
    durationFormat = "مدت زمان: %s",
    notificationEnabledTitle = "اعلان: فعال",
    notificationDisabledTitle = "اعلان: غیرغعال",
    emptyTemplatesTitle = "لیست خالی است",
    priorityParameterTitle = "اولویت ویژه",
    noteLabel = "یادداشت",
    notePlaceholder = "یک یادداشت کوچک اختیاری است",
    undefinedTasksSheetTitle = "وظایف غیر توزیع شده",
    fifteenMinutesBeforeTitle = "15دقیقه قبل از شروع",
    oneHourBeforeTitle = "یک ساعت قبل از شروع",
    threeHourBeforeTitle = "دو ساعت قبل از شروع",
    oneDayBeforeTitle = "روز قبل از شروع",
    oneWeekBeforeTitle = "یک هفته قبل از شروع",
    beforeEndTitle = "قبل از پایان",
    dialogCreateTitle = "ایجاد",
    categoryFieldLabel = "نام",
    updateCategoryTitle = "تغییر",
    deleteCategoryTitle = "حذف",
    subCategoryTitle = "زیر مجموعه ها",
    warningDeleteCategoryText = "آیا مطمئن هستید که می خواهید دسته اصلی را حذف کنید؟ " +
        "این عمل تمام کارهای برنامه ریزی شده قبلی را از بین می برد.",
    addCategoryTitle = "افزودن",
    nameCategoryTitle = "نام",
    restoreDefaultCategories = "بازگرداندن دسته های پیش فرض",
)

internal val germanEditorString = EditorStrings(
    topAppBarEditorTitle = "Bearbeiten",
    topAppBarCategoriesTitle = "Kategorien",
    topAppBarBackIconDesc = "Zurück",
    topAppBarMenuIconDesc = "Menü öffnen",
    topAppBarTemplatesTitle = "Muster",
    mainCategoryChooserTitle = "Kategorie",
    subCategoryChooserTitle = "Unterkategorie",
    chooseCategoryTitle = "Kategorie auswählen",
    categoryNotSelectedTitle = "Fehlt",
    subCategoryDialogAddedTitle = "Hinzufügen",
    subCategoryDialogMainCategoryFormat = "Kategorie: %s",
    mainCategoryTitle = "Hauptkategorie",
    timeFieldStartLabel = "Start",
    timeFieldEndLabel = "Ende",
    parameterChooserSwitchIconDesc = "Parameter festlegen",
    timePickerHeader = "Zeit wählen",
    notifyParameterTitle = "Benachrichtigungen",
    notifyParameterDesc = "Benachrichtigung senden, wenn eine Aufgabe ausgeführt wird",
    statisticsParameterTitle = "Statistik",
    statisticsParameterDesc = "Daten in Statistiken berücksichtigen",
    saveTaskButtonTitle = "Speichern",
    cancelButtonTitle = "Abbrechen",
    templateIconDesc = "Zu Vorlagen hinzufügen",
    topAppBarDeleteTitle = "Entfernen",
    categoryValidateError = "* Wählen Sie eine Kategorie aus",
    otherError = "Fehler! Wenden Sie sich an den Entwickler.",
    startOverlayError = "Konflikt! Überlagerung des Aufgabenstarts.",
    endOverlayError = "Konflikt! Überlagert das Ende der Aufgabe.",
    fullOverlayError = "Konflikt! Überlagerung von Aufgaben.",
    correctOverlayTitle = "Korrigieren",
    durationPickerTitle = "Dauer",
    templatesSheetTitle = "Muster",
    controlTitle = "Verwalten",
    applyTitle = "Anwenden",
    timeRangeFormat = "Zeit von %s bis %s Uhr",
    durationFormat = "Dauer: %s",
    notificationEnabledTitle = "Benachrichtigungen: eingeschaltet",
    notificationDisabledTitle = "Benachrichtigungen: sind deaktiviert",
    emptyTemplatesTitle = "Die Liste ist leer",
    priorityParameterTitle = "Priorität",
    noteLabel = "Notiz",
    notePlaceholder = "Eine kleine Anmerkung optional",
    undefinedTasksSheetTitle = "Nicht verteilte Aufgaben",
    fifteenMinutesBeforeTitle = "15 Minuten vor dem Start",
    oneHourBeforeTitle = "Eine Stunde vor Beginn",
    threeHourBeforeTitle = "Zwei Stunden vor Beginn",
    oneDayBeforeTitle = "Einen Tag vor Beginn",
    oneWeekBeforeTitle = "Eine Woche vor dem Start",
    beforeEndTitle = "Vor dem Ende",
    dialogCreateTitle = "Erstellen",
    categoryFieldLabel = "Name",
    updateCategoryTitle = "Bearbeiten",
    deleteCategoryTitle = "Entfernen",
    subCategoryTitle = "Unterkategorien",
    warningDeleteCategoryText = "Sind Sie sicher, dass Sie die Hauptkategorie löschen möchten? " +
        "Durch diese Aktion werden alle zuvor geplanten Aufgaben gelöscht.",
    addCategoryTitle = "Hinzufügen",
    nameCategoryTitle = "Name",
    restoreDefaultCategories = "Standardkategorien wiederherstellen",
)

internal val spanishEditorString = EditorStrings(
    topAppBarEditorTitle = "Editor",
    topAppBarCategoriesTitle = "Categorías",
    topAppBarBackIconDesc = "Volver",
    topAppBarMenuIconDesc = "Abrir menú",
    topAppBarTemplatesTitle = "Plantillas",
    mainCategoryChooserTitle = "Categoría",
    subCategoryChooserTitle = "Subcategoría",
    chooseCategoryTitle = "Selecciona categoría",
    categoryNotSelectedTitle = "Ninguna",
    subCategoryDialogAddedTitle = "Añadir",
    subCategoryDialogMainCategoryFormat = "Categoría: %s",
    mainCategoryTitle = "Página principal",
    timeFieldStartLabel = "Empieza",
    timeFieldEndLabel = "Termina",
    parameterChooserSwitchIconDesc = "Establecer parámetro",
    timePickerHeader = "Introduce la hora",
    notifyParameterTitle = "Notificaciones",
    notifyParameterDesc = "Envía una notificación al completar la tarea",
    statisticsParameterTitle = "Estadísticas",
    statisticsParameterDesc = "Incluye la tarea en las estadísticas",
    saveTaskButtonTitle = "Guardar",
    cancelButtonTitle = "Cancelar",
    templateIconDesc = "Añadir a Plantillas",
    topAppBarDeleteTitle = "Eliminar",
    categoryValidateError = "* Selecciona una categoría",
    otherError = "¡Error! Contacta al desarrollador.",
    startOverlayError = "¡Conflicto! Inicio superpuesto.",
    endOverlayError = "¡Conflicto! Fin superpuesto.",
    fullOverlayError = "¡Conflicto! Tareas superpuestas.",
    correctOverlayTitle = "Corrige",
    durationPickerTitle = "Duración",
    templatesSheetTitle = "Plantillas",
    controlTitle = "Gestionar",
    applyTitle = "Aplicar",
    timeRangeFormat = "Hora: de %S a %s",
    durationFormat = "Duración: %s",
    notificationEnabledTitle = "Notificación: activada",
    notificationDisabledTitle = "Notificación: desactivada",
    emptyTemplatesTitle = "Lista vacía",
    priorityParameterTitle = "Prioridad especial",
    noteLabel = "Nota",
    notePlaceholder = "Una pequeña nota opcional",
    undefinedTasksSheetTitle = "Tareas no distribuidas",
    fifteenMinutesBeforeTitle = "15 minutos antes del Inicio",
    oneHourBeforeTitle = "Una hora antes del Inicio",
    threeHourBeforeTitle = "Dos horas antes del Inicio",
    oneDayBeforeTitle = "Un día antes del Inicio",
    oneWeekBeforeTitle = "Una semana antes del Inicio",
    beforeEndTitle = "Antes de terminar",
    dialogCreateTitle = "Crear",
    categoryFieldLabel = "Nombre",
    updateCategoryTitle = "Editar",
    deleteCategoryTitle = "Eliminar",
    subCategoryTitle = "Subcategorías",
    warningDeleteCategoryText = "¿Quieres eliminar la categoría principal? " +
        "Esto eliminará todas las tareas programadas anteriormente.",
    addCategoryTitle = "Añadir",
    nameCategoryTitle = "Nombre",
    restoreDefaultCategories = "Restaurar categorías predeterminadas",
)

internal val frenchEditorString = EditorStrings(
    topAppBarEditorTitle = "Éditeur",
    topAppBarCategoriesTitle = "Categories",
    topAppBarBackIconDesc = "Retour",
    topAppBarMenuIconDesc = "Ouvrir le menu",
    topAppBarTemplatesTitle = "Modèles",
    mainCategoryChooserTitle = "Catégorie",
    subCategoryChooserTitle = "Sous-catégorie",
    chooseCategoryTitle = "Sélectionner la catégorie",
    categoryNotSelectedTitle = "Absent",
    subCategoryDialogAddedTitle = "Ajouter",
    subCategoryDialogMainCategoryFormat = "Catégorie: %s",
    mainCategoryTitle = "Principal",
    timeFieldStartLabel = "Début",
    timeFieldEndLabel = "Fin",
    parameterChooserSwitchIconDesc = "Set parameter",
    timePickerHeader = "Entre l'heure",
    notifyParameterTitle = "Notifications",
    notifyParameterDesc = "Envoyer une notification lorsque la tâche est terminée",
    statisticsParameterTitle = "Statistiques",
    statisticsParameterDesc = "Inclure cette tâche dans les statistiques",
    saveTaskButtonTitle = "Sauvegarder",
    cancelButtonTitle = "Annuler",
    templateIconDesc = "Ajouter aux modèles",
    topAppBarDeleteTitle = "Supprimer",
    categoryValidateError = "* Sélectionnez une catégorie!",
    otherError = "Erreur! Veuillez contater le developpeur.",
    startOverlayError = "Conflit! Le début de la tâche se superpose.",
    endOverlayError = "Conflict! La fin de la tâche se superpose.",
    fullOverlayError = "Conflict! Deux tâches se chevanchent.",
    correctOverlayTitle = "Corriger",
    durationPickerTitle = "Durée",
    templatesSheetTitle = "Modèles",
    controlTitle = "Gestion",
    applyTitle = "Appliquer",
    timeRangeFormat = "Temps: de %S à %s",
    durationFormat = "Durée: %s",
    notificationEnabledTitle = "Notification: activées",
    notificationDisabledTitle = "Notification: désactivées",
    emptyTemplatesTitle = "La liste est vide",
    priorityParameterTitle = "Priorité",
    noteLabel = "Note",
    notePlaceholder = "Petite Note en option",
    undefinedTasksSheetTitle = "Tâches non distribuées",
    fifteenMinutesBeforeTitle = "15 minutes avant le début",
    oneHourBeforeTitle = "Une heure avant le début",
    threeHourBeforeTitle = "Deux heures avant le début",
    oneDayBeforeTitle = "La veille du début",
    oneWeekBeforeTitle = "Une semaine avant le début",
    beforeEndTitle = "Avant la fin",
    dialogCreateTitle = "Créer",
    categoryFieldLabel = "Titre",
    updateCategoryTitle = "Modifier",
    deleteCategoryTitle = "Supprimer",
    subCategoryTitle = "Sous-catégories",
    warningDeleteCategoryText = "Êtes-vous sur(e) de vouloir supprimer la catégorie principale? " +
        "Cette action engendredra la suppression de toutes les tâches prévues.",
    addCategoryTitle = "Ajouter",
    nameCategoryTitle = "Titre",
    restoreDefaultCategories = "Restaurer les Catégories par défaut",
)

internal val brazilianPortugueseEditorString = EditorStrings(
    topAppBarEditorTitle = "Editor",
    topAppBarCategoriesTitle = "Categorias",
    topAppBarBackIconDesc = "Voltar",
    topAppBarMenuIconDesc = "Abrir menu",
    topAppBarTemplatesTitle = "Templates",
    mainCategoryChooserTitle = "Categorias",
    subCategoryChooserTitle = "Subcategoria",
    chooseCategoryTitle = "Selecione uma categoria",
    categoryNotSelectedTitle = "Nenhum",
    subCategoryDialogAddedTitle = "Adicionar",
    subCategoryDialogMainCategoryFormat = "Categoria: %s",
    mainCategoryTitle = "Principal",
    timeFieldStartLabel = "Iniciar",
    timeFieldEndLabel = "Terminar",
    parameterChooserSwitchIconDesc = "Definir parâmetro",
    timePickerHeader = "Adicione o tempo",
    notifyParameterTitle = "Notificação",
    notifyParameterDesc = "Enviar uma notificação quando terminar essa tarefa",
    statisticsParameterTitle = "Estatísticas",
    statisticsParameterDesc = "Incluir tarefa nas estatísticas",
    saveTaskButtonTitle = "Salvar",
    cancelButtonTitle = "Cancelar",
    templateIconDesc = "Adicionar aos Templates",
    topAppBarDeleteTitle = "Deletar",
    categoryValidateError = "* Selecionar uma categoria",
    otherError = "Erro! Contate o desenvolvedor.",
    startOverlayError = "Conflito! Início da tarefa em sobreposição.",
    endOverlayError = "Conflito! Fim da tarefa em sobreposição.",
    fullOverlayError = "Conflito! Tarefas sobrepostas.",
    correctOverlayTitle = "Consertar",
    durationPickerTitle = "Duração",
    templatesSheetTitle = "Templates",
    controlTitle = "Administrar",
    applyTitle = "Aplicar",
    timeRangeFormat = "Tempo: from %S to %s",
    durationFormat = "Duração: %s",
    notificationEnabledTitle = "Notificação: ativada",
    notificationDisabledTitle = "Notificação: desativada",
    emptyTemplatesTitle = "Lista está vazia",
    priorityParameterTitle = "Prioridade",
    noteLabel = "Nota",
    notePlaceholder = "Uma nota é opcional",
    undefinedTasksSheetTitle = "Tarefas não distribuídas",
    fifteenMinutesBeforeTitle = "15 minutos antes do início",
    oneHourBeforeTitle = "Uma hora antes do início",
    threeHourBeforeTitle = "Duas horas antes do início",
    oneDayBeforeTitle = "No dia anterior ao início",
    oneWeekBeforeTitle = "Uma semana antes do início",
    beforeEndTitle = "Antes do fim",
    dialogCreateTitle = "Criar",
    categoryFieldLabel = "Nome",
    updateCategoryTitle = "Editar",
    deleteCategoryTitle = "Remover",
    subCategoryTitle = "Subcategorias",
    warningDeleteCategoryText = "Você tem certeza que deseja deletar a categoria principal? " +
        "Esta ação irá apagar todas as tarefas previamente planejadas.",
    addCategoryTitle = "Adicionar",
    nameCategoryTitle = "Nome",
    restoreDefaultCategories = "Restaurar categorias originais",
)

internal val turkishEditorString = EditorStrings(
    topAppBarEditorTitle = "Editör",
    topAppBarCategoriesTitle = "Kategoriler",
    topAppBarBackIconDesc = "Geri",
    topAppBarMenuIconDesc = "Menüyü aç",
    topAppBarTemplatesTitle = "Şablonlar",
    mainCategoryChooserTitle = "Kategori",
    subCategoryChooserTitle = "Alt Kategori",
    chooseCategoryTitle = "Kategori Seçin",
    categoryNotSelectedTitle = "Yok",
    subCategoryDialogAddedTitle = "Ekle",
    subCategoryDialogMainCategoryFormat = "Kategori: %s",
    mainCategoryTitle = "Ana",
    timeFieldStartLabel = "Başlangıç",
    timeFieldEndLabel = "Bitiş",
    parameterChooserSwitchIconDesc = "Parametre Belirle",
    timePickerHeader = "Zamanı Girin",
    notifyParameterTitle = "Bildirimler",
    notifyParameterDesc = "Bu görev tamamlandığında bildirim gönder",
    statisticsParameterTitle = "İstatistikler",
    statisticsParameterDesc = "Görevi istatistiklere dahil et",
    saveTaskButtonTitle = "Kaydet",
    cancelButtonTitle = "İptal",
    templateIconDesc = "Şablonlara Ekle",
    topAppBarDeleteTitle = "Sil",
    categoryValidateError = "* Bir kategori seçin",
    otherError = "Hata! Geliştirici ile iletişime geçin.",
    startOverlayError = "Çakışma! Görev başlangıcı üst üste.",
    endOverlayError = "Çakışma! Görev bitişi üst üste.",
    fullOverlayError = "Çakışma! Örtüşen görevler.",
    correctOverlayTitle = "Düzelt",
    durationPickerTitle = "Süre",
    templatesSheetTitle = "Şablonlar",
    controlTitle = "Yönet",
    applyTitle = "Uygula",
    timeRangeFormat = "Zaman: %S ile %s arasında",
    durationFormat = "Süre: %s",
    notificationEnabledTitle = "Bildirim: etkin",
    notificationDisabledTitle = "Bildirim: devre dışı",
    emptyTemplatesTitle = "Liste boş",
    priorityParameterTitle = "Öncelik",
    noteLabel = "Not",
    notePlaceholder = "Küçük bir not (isteğe bağlı)",
    undefinedTasksSheetTitle = "Dağıtılmamış Görevler",
    fifteenMinutesBeforeTitle = "Başlamadan 15 dakika önce",
    oneHourBeforeTitle = "Başlangıçtan bir saat önce",
    threeHourBeforeTitle = "Başlangıçtan iki saat önce",
    oneDayBeforeTitle = "Başlangıçtan bir gün önce",
    oneWeekBeforeTitle = "Başlamadan bir hafta önce",
    beforeEndTitle = "Bitişten önce",
    dialogCreateTitle = "Oluştur",
    categoryFieldLabel = "Ad",
    updateCategoryTitle = "Düzenle",
    deleteCategoryTitle = "Kaldır",
    subCategoryTitle = "Alt kategoriler",
    warningDeleteCategoryText = "Ana kategoriyi silmek istediğinizden emin misiniz? " +
        "Bu işlem önceden planlanmış tüm görevleri yok eder.",
    addCategoryTitle = "Ekle",
    nameCategoryTitle = "Ad",
    restoreDefaultCategories = "Varsayılan kategorilere geri dön",
)

internal val vietnameseEditorString = EditorStrings(
    topAppBarEditorTitle = "Trình biên tập",
    topAppBarCategoriesTitle = "Danh mục",
    topAppBarBackIconDesc = "Quay lại",
    topAppBarMenuIconDesc = "Mở thực đơn",
    topAppBarTemplatesTitle = "Mẫu",
    mainCategoryChooserTitle = "Danh mục",
    subCategoryChooserTitle = "Danh mục con",
    chooseCategoryTitle = "Chọn danh mục",
    categoryNotSelectedTitle = "Vắng mặt",
    subCategoryDialogAddedTitle = "Thêm",
    subCategoryDialogMainCategoryFormat = "Danh mục: %s",
    mainCategoryTitle = "Chính",
    timeFieldStartLabel = "Bắt đầu",
    timeFieldEndLabel = "Kết thúc",
    parameterChooserSwitchIconDesc = "Đặt tham số",
    timePickerHeader = "Nhập thời gian",
    notifyParameterTitle = "Thông báo",
    notifyParameterDesc = "Gửi thông báo khi hoàn thành nhiệm vụ này",
    statisticsParameterTitle = "Thống kê",
    statisticsParameterDesc = "Đưa nhiệm vụ vào thống kê",
    saveTaskButtonTitle = "Lưu",
    cancelButtonTitle = "Hủy",
    templateIconDesc = "Thêm vào mẫu",
    topAppBarDeleteTitle = "Xóa",
    categoryValidateError = "* Chọn một danh mục",
    otherError = "Lỗi! Hãy liên hệ với nhà phát triển.",
    startOverlayError = "Xung đột! Lớp phủ bắt đầu nhiệm vụ.",
    endOverlayError = "Xung đột! Lớp phủ kết thúc nhiệm vụ.",
    fullOverlayError = "Xung đột! Nhiệm vụ chồng chéo.",
    correctOverlayTitle = "Sửa",
    durationPickerTitle = "Thời lượng",
    templatesSheetTitle = "Mẫu",
    controlTitle = "Quản lý",
    applyTitle = "Áp dụng",
    timeRangeFormat = "Thời gian: từ %S đến %s",
    durationFormat = "Thời lượng: %s",
    notificationEnabledTitle = "Thông báo: đã bật",
    notificationDisabledTitle = "Thông báo: đã tắt",
    emptyTemplatesTitle = "Danh sách trống",
    priorityParameterTitle = "Ưu tiên",
    noteLabel = "Ghi chú",
    notePlaceholder = "Một ghi chú nhỏ là không bắt buộc",
    undefinedTasksSheetTitle = "Nhiệm vụ không được phân phối",
    fifteenMinutesBeforeTitle = "15 phút trước khi bắt đầu",
    oneHourBeforeTitle = "Một giờ trước khi bắt đầu",
    threeHourBeforeTitle = "Hai giờ trước khi bắt đầu",
    oneDayBeforeTitle = "Ngày trước khi bắt đầu",
    oneWeekBeforeTitle = "Một tuần trước khi bắt đầu",
    beforeEndTitle = "Trước khi kết thúc",
    dialogCreateTitle = "Tạo",
    categoryFieldLabel = "Tên",
    updateCategoryTitle = "Biên tập",
    deleteCategoryTitle = "Loại bỏ",
    subCategoryTitle = "Danh mục con",
    warningDeleteCategoryText = "Bạn có chắc chắn muốn xóa danh mục chính không?" +
        "Hành động này sẽ hủy tất cả các nhiệm vụ đã lên lịch trước đó.",
    addCategoryTitle = "Thêm vào",
    nameCategoryTitle = "Tên",
    restoreDefaultCategories = "Khôi phục danh mục mặc định",
)

internal val polishEditorString = EditorStrings(
    topAppBarEditorTitle = "Edytor",
    topAppBarCategoriesTitle = "Kategorie",
    topAppBarBackIconDesc = "Wróć",
    topAppBarMenuIconDesc = "Otwórz menu",
    topAppBarTemplatesTitle = "Szablony",
    mainCategoryChooserTitle = "Kategoria",
    subCategoryChooserTitle = "Podkategoria",
    chooseCategoryTitle = "Wybierz kategorię",
    categoryNotSelectedTitle = "Brak",
    subCategoryDialogAddedTitle = "Dodaj",
    subCategoryDialogMainCategoryFormat = "Kategoria: %s",
    mainCategoryTitle = "Planer",
    timeFieldStartLabel = "Początek",
    timeFieldEndLabel = "Koniec",
    parameterChooserSwitchIconDesc = "Ustaw parametr",
    timePickerHeader = "Wprowadź czas",
    notifyParameterTitle = "Powiadomienia",
    notifyParameterDesc = "Ustaw przypomnienie o rozpoczęciu zadania",
    statisticsParameterTitle = "Statystyki",
    statisticsParameterDesc = "Uwzględnij w analizach",
    saveTaskButtonTitle = "Zapisz",
    cancelButtonTitle = "Anuluj",
    templateIconDesc = "Zapisz jako szablon",
    topAppBarDeleteTitle = "Usuń",
    categoryValidateError = "* Wybierz kategorię",
    otherError = "Coś poszło nie tak. Skontaktuj się z twórcą aplikacji by otrzymać pomoc.",
    startOverlayError = "Konflikt! Nakładające się czasy rozpoczęcia",
    endOverlayError = "Konflikt! Nakładające się czasy zakończenia",
    fullOverlayError = "Konflikt! Nakładające się zadania",
    correctOverlayTitle = "Napraw",
    durationPickerTitle = "Czas trwania",
    templatesSheetTitle = "Szablony",
    controlTitle = "Zarządzaj",
    applyTitle = "Zastosuj",
    timeRangeFormat = "Czas: od %s do %s",
    durationFormat = "Czas trwania: %s",
    notificationEnabledTitle = "Powiadomienie: włączone",
    notificationDisabledTitle = "Powiadomienie: wyłączone",
    emptyTemplatesTitle = "Lista jest pusta",
    priorityParameterTitle = "Priorytet",
    noteLabel = "Notatka",
    notePlaceholder = "Opcjonalnie...",
    undefinedTasksSheetTitle = "Zadania nierozmieszczone",
    fifteenMinutesBeforeTitle = "15 minut przed",
    oneHourBeforeTitle = "Godzina przed",
    threeHourBeforeTitle = "Dwie godziny przed",
    oneDayBeforeTitle = "Dzień przed",
    oneWeekBeforeTitle = "Tydzień przed",
    beforeEndTitle = "Przed zakończeniem",
    dialogCreateTitle = "Utwórz",
    categoryFieldLabel = "Nazwa",
    updateCategoryTitle = "Edytuj",
    deleteCategoryTitle = "Usuń",
    subCategoryTitle = "Podkategorie",
    warningDeleteCategoryText = "Czy na pewno chcesz usunąć kategorię główną? " +
            "Ta operacja spowoduje usunięcie wszystkich wcześniej zaplanowanych zadań.",
    addCategoryTitle = "Dodaj",
    nameCategoryTitle = "Nazwa",
    restoreDefaultCategories = "Przywróć domyślne kategorie",
)

internal val italianEditorString = EditorStrings(
    topAppBarEditorTitle = "Editor",
    topAppBarCategoriesTitle = "Categorie",
    topAppBarBackIconDesc = "Indietro",
    topAppBarMenuIconDesc = "Apri menu",
    topAppBarTemplatesTitle = "Template",
    mainCategoryChooserTitle = "Categoria",
    subCategoryChooserTitle = "Sottocategoria",
    chooseCategoryTitle = "Seleziona una categoria",
    categoryNotSelectedTitle = "Niente",
    subCategoryDialogAddedTitle = "aggiungi",
    subCategoryDialogMainCategoryFormat = "Categoria: %s",
    mainCategoryTitle = "Principale",
    timeFieldStartLabel = "Inizio",
    timeFieldEndLabel = "Fine",
    parameterChooserSwitchIconDesc = "Imposta un parametro",
    timePickerHeader = "Inserisci l'orario",
    notifyParameterTitle = "Notifiche",
    notifyParameterDesc = "Imposta un promemoria per l'inizio del task",
    statisticsParameterTitle = "Statistiche",
    statisticsParameterDesc = "Includi nelle statistiche",
    saveTaskButtonTitle = "Salva",
    cancelButtonTitle = "Annulla",
    templateIconDesc = "Salva come template",
    topAppBarDeleteTitle = "Elimina",
    categoryValidateError = "* Seleziona una categoria",
    otherError = "Qualcosa è andato storto. Contatta lo sviluppatore per ottenere assistenza.",
    startOverlayError = "Conflitto! Sovrapposizione con l'orario di inizio",
    endOverlayError = "Conflitto! Sovrapposizione con l'orario di fine",
    fullOverlayError = "Conflitto! Task Sovrapposti",
    correctOverlayTitle = "Correggi",
    durationPickerTitle = "Durata",
    templatesSheetTitle = "Template",
    controlTitle = "Gestione",
    applyTitle = "Applica",
    timeRangeFormat = "Orario: dalle %S alle %s",
    durationFormat = "Durata: %s",
    notificationEnabledTitle = "Notifiche: abilitate",
    notificationDisabledTitle = "Notifiche: disabilitate",
    emptyTemplatesTitle = "La lista è vuota",
    priorityParameterTitle = "Priorità",
    noteLabel = "Note",
    notePlaceholder = "Opzionali",
    undefinedTasksSheetTitle = "Task non pianificate",
    fifteenMinutesBeforeTitle = "15 minuti prima",
    oneHourBeforeTitle = "Un'ora prima",
    threeHourBeforeTitle = "Due ore prima",
    oneDayBeforeTitle = "Un giorno prima",
    oneWeekBeforeTitle = "Una settimana prima",
    beforeEndTitle = "Prima del completamento",
    dialogCreateTitle = "Crea",
    categoryFieldLabel = "Nome",
    updateCategoryTitle = "Modifica",
    deleteCategoryTitle = "Rimuovi",
    subCategoryTitle = "Sottocategorie",
    warningDeleteCategoryText = "Sei sicuro di voler eliminare la categoria principale? " +
        "Questa azione eliminerà i task già programmati.",
    addCategoryTitle = "Aggiungi",
    nameCategoryTitle = "Nome",
    restoreDefaultCategories = "Reimposta le categorie di default",
)

internal val chineseEditorString = EditorStrings(
    topAppBarEditorTitle = "编辑器",
    topAppBarCategoriesTitle = "分类",
    topAppBarBackIconDesc = "返回",
    topAppBarMenuIconDesc = "打开菜单",
    topAppBarTemplatesTitle = "模板",
    mainCategoryChooserTitle = "分类",
    subCategoryChooserTitle = "子分类",
    chooseCategoryTitle = "选择分类",
    categoryNotSelectedTitle = "无",
    subCategoryDialogAddedTitle = "添加",
    subCategoryDialogMainCategoryFormat = "分类：%s",
    mainCategoryTitle = "主分类",
    timeFieldStartLabel = "开始",
    timeFieldEndLabel = "结束",
    parameterChooserSwitchIconDesc = "设置参数",
    timePickerHeader = "输入时间",
    notifyParameterTitle = "通知",
    notifyParameterDesc = "设置任务开始提醒",
    statisticsParameterTitle = "统计",
    statisticsParameterDesc = "计入统计",
    saveTaskButtonTitle = "保存",
    cancelButtonTitle = "取消",
    templateIconDesc = "保存为模板",
    topAppBarDeleteTitle = "删除",
    categoryValidateError = "* 请选择分类",
    otherError = "出现问题。请联系开发者获取帮助。",
    startOverlayError = "冲突！开始时间重叠",
    endOverlayError = "冲突！结束时间重叠",
    fullOverlayError = "冲突！任务时间重叠",
    correctOverlayTitle = "修正",
    durationPickerTitle = "时长",
    templatesSheetTitle = "模板",
    controlTitle = "管理",
    applyTitle = "应用",
    timeRangeFormat = "时间：从 %S 到 %s",
    durationFormat = "时长：%s",
    notificationEnabledTitle = "通知：已开启",
    notificationDisabledTitle = "通知：已关闭",
    emptyTemplatesTitle = "列表为空",
    priorityParameterTitle = "优先级",
    noteLabel = "备注",
    notePlaceholder = "可选",
    undefinedTasksSheetTitle = "未分配任务",
    fifteenMinutesBeforeTitle = "提前 15 分钟",
    oneHourBeforeTitle = "提前 1 小时",
    threeHourBeforeTitle = "提前 2 小时",
    oneDayBeforeTitle = "提前 1 天",
    oneWeekBeforeTitle = "提前 1 周",
    beforeEndTitle = "结束前",
    dialogCreateTitle = "创建",
    categoryFieldLabel = "名称",
    updateCategoryTitle = "编辑",
    deleteCategoryTitle = "删除",
    subCategoryTitle = "子分类",
    warningDeleteCategoryText = "确定要删除主分类吗？此操作将删除所有已安排的任务。",
    addCategoryTitle = "添加",
    nameCategoryTitle = "名称",
    restoreDefaultCategories = "恢复默认分类",
)

internal val LocalEditorStrings = staticCompositionLocalOf<EditorStrings> {
    error("Home Strings is not provided")
}

internal fun fetchEditorStrings(language: TimePlannerLanguage) = when (language) {
    TimePlannerLanguage.EN -> englishEditorString
    TimePlannerLanguage.RU -> russianEditorString
    TimePlannerLanguage.DE -> germanEditorString
    TimePlannerLanguage.ES -> spanishEditorString
    TimePlannerLanguage.FA -> persianEditorString
    TimePlannerLanguage.FR -> frenchEditorString
    TimePlannerLanguage.PT_BR -> brazilianPortugueseEditorString
    TimePlannerLanguage.TR -> turkishEditorString
    TimePlannerLanguage.VN -> vietnameseEditorString
    TimePlannerLanguage.PL -> polishEditorString
    TimePlannerLanguage.IT -> italianEditorString
    TimePlannerLanguage.ZH -> chineseEditorString
}
