/*
 * Copyright 2026 Stanislav Aleshin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ru.aleshin.features.analytics.impl.presentation.theme.tokens

import androidx.compose.runtime.staticCompositionLocalOf
import ru.aleshin.timeplanner.core.ui.theme.tokens.TimePlannerLanguage

/**
 * @author Stanislav Aleshin on 21.07.2026.
 */
internal data class AnalyticsStrings(
    val topAppBarTitle: String,
    val otherError: String,
    val lastSevenDays: String,
    val week: String,
    val month: String,
    val halfYear: String,
    val year: String,
    val currentPeriod: String,
    val previousPeriodDesc: String,
    val nextPeriodDesc: String,
    val previousMonthDesc: String,
    val nextMonthDesc: String,
    val selectRangeDesc: String,
    val cancel: String,
    val confirm: String,
    val summaryTitle: String,
    val summaryLastSevenDaysTitle: String,
    val summaryWeekTitle: String,
    val summaryMonthTitle: String,
    val summaryHalfYearTitle: String,
    val summaryYearTitle: String,
    val categoriesTitle: String,
    val loadTitle: String,
    val creationTitle: String,
    val durationStructureTitle: String,
    val planSourceTitle: String,
    val keyMetricsTitle: String,
    val regularityTitle: String,
    val busiestHoursTitle: String,
    val categorySummaryTitle: String,
    val subCategoriesTitle: String,
    val categoryLoadTitle: String,
    val dayPartsTitle: String,
    val categoryTasksTitle: String,
    val observationTitle: String,
    val planned: String,
    val completed: String,
    val skipped: String,
    val unfinished: String,
    val completionShare: String,
    val completedCountFormat: String,
    val previousPeriod: String,
    val comparisonPreviousZero: String,
    val comparisonUnavailable: String,
    val comparisonUnchanged: String,
    val byTime: String,
    val byTasks: String,
    val showAll: String,
    val collapse: String,
    val other: String,
    val newCategory: String,
    val showAllCategories: String,
    val showAllTasks: String,
    val tasksFormat: String,
    val loadTooltipFormat: String,
    val categoryLoadTooltipFormat: String,
    val median: String,
    val average: String,
    val createdInAdvance: String,
    val createdOneOrTwoDays: String,
    val createdSameDay: String,
    val createdAfterStart: String,
    val onlyUnlinkedTasks: String,
    val included: String,
    val medianPlanningAhead: String,
    val beforeStartFormat: String,
    val afterStartFormat: String,
    val atStart: String,
    val shortTasks: String,
    val mediumTasks: String,
    val longTasks: String,
    val withTemplate: String,
    val withoutTemplate: String,
    val important: String,
    val weekends: String,
    val longestBlock: String,
    val busiestDay: String,
    val activeDaysFormat: String,
    val dayUnit: String,
    val periodDaysFormat: String,
    val activeDayIncreaseFormat: String,
    val activeDayDecreaseFormat: String,
    val activeDayUnchanged: String,
    val less: String,
    val more: String,
    val heatmapRowDescFormat: String,
    val heatmapCellFormat: String,
    val heatmapDetailsAction: String,
    val dayPartRowDescFormat: String,
    val averageLoadExplanation: String,
    val averageLoadInfoDesc: String,
    val averagePlannedMinutes: String,
    val unavailableValue: String,
    val hourShort: String,
    val minuteShort: String,
    val noData: String,
    val noDataSupporting: String,
    val categoryNoData: String,
    val categoryNoDataSupporting: String,
    val sectionNoData: String,
    val creationNoData: String,
    val error: String,
    val categoryError: String,
    val retry: String,
    val loading: String,
    val openCategoryFormat: String,
    val navigateBackDesc: String,
    val categoryUnavailable: String,
    val categoryUnavailableSupporting: String,
    val withoutSubCategory: String,
    val categoryShare: String,
    val allPlan: String,
    val taskCount: String,
    val timeLabel: String,
    val tasksLabel: String,
    val tasksMetric: String,
    val averageDuration: String,
    val medianDuration: String,
    val taskCountIncreaseFormat: String,
    val taskCountDecreaseFormat: String,
    val metricDurationIncreaseFormat: String,
    val metricDurationDecreaseFormat: String,
    val completedCountIncreaseFormat: String,
    val completedCountDecreaseFormat: String,
    val completionIncreaseFormat: String,
    val completionDecreaseFormat: String,
    val completionPreviousZero: String,
    val categoryShareFormat: String,
    val categoryPreviousUnused: String,
    val categoryTimeIncreaseFormat: String,
    val categoryTimeDecreaseFormat: String,
    val busiestDayValueFormat: String,
    val dayPartNight: String,
    val dayPartMorning: String,
    val dayPartDay: String,
    val dayPartEvening: String,
    val statusCompleted: String,
    val statusSkipped: String,
    val statusUnfinished: String,
    val selectDateRange: String,
    val allWithoutSubCategory: String,
    val inCategory: String,
    val completionDropObservationFormat: String,
    val busiestDayObservationFormat: String,
    val dominantSubCategoryObservationFormat: String,
)

internal val russianAnalyticsString = AnalyticsStrings(
    topAppBarTitle = "Аналитика",
    otherError = "Что-то пошло не так. Обратитесь к разработчику.",
    lastSevenDays = "Последние 7 дней",
    week = "Неделя",
    month = "Месяц",
    halfYear = "Полугодие",
    year = "Год",
    currentPeriod = "Текущий период",
    previousPeriodDesc = "Предыдущий период",
    nextPeriodDesc = "Следующий период",
    previousMonthDesc = "Предыдущий месяц",
    nextMonthDesc = "Следующий месяц",
    selectRangeDesc = "Выбрать произвольный диапазон",
    cancel = "Отмена",
    confirm = "Готово",
    summaryTitle = "Итог периода",
    summaryLastSevenDaysTitle = "Итог за 7 дней",
    summaryWeekTitle = "Итог недели",
    summaryMonthTitle = "Итог месяца",
    summaryHalfYearTitle = "Итог полугодия",
    summaryYearTitle = "Итог года",
    categoriesTitle = "Время по категориям",
    loadTitle = "Динамика нагрузки",
    creationTitle = "Когда создаются задачи",
    durationStructureTitle = "Структура длительности задач",
    planSourceTitle = "Привязка к шаблонам",
    keyMetricsTitle = "Ключевые показатели",
    regularityTitle = "Регулярность планирования",
    busiestHoursTitle = "Самые загруженные часы",
    categorySummaryTitle = "Итог категории",
    subCategoriesTitle = "Время по подкатегориям",
    categoryLoadTitle = "Динамика категории",
    dayPartsTitle = "Распределение по времени суток",
    categoryTasksTitle = "Задачи категории",
    observationTitle = "Наблюдение",
    planned = "Запланировано",
    completed = "Выполнено",
    skipped = "Пропущено",
    unfinished = "Впереди",
    completionShare = "Доля выполнения",
    completedCountFormat = "%s из %s",
    previousPeriod = "к предыдущему периоду",
    comparisonPreviousZero = "В прошлом периоде нет выполненных задач",
    comparisonUnavailable = "Недостаточно данных для сравнения",
    comparisonUnchanged = "Без изменений",
    byTime = "По времени",
    byTasks = "По задачам",
    showAll = "Показать все",
    collapse = "Свернуть",
    other = "Другие",
    newCategory = "Новая",
    showAllCategories = "Показать все категории",
    showAllTasks = "Показать все задачи",
    tasksFormat = "Задач: %s",
    loadTooltipFormat = "%s · %s · %s",
    categoryLoadTooltipFormat = "%s · %s: %s · весь план: %s",
    median = "Медиана",
    average = "Среднее",
    createdInAdvance = "За 3 дня и раньше",
    createdOneOrTwoDays = "За 1–2 дня",
    createdSameDay = "В запланированный день",
    createdAfterStart = "После начала",
    onlyUnlinkedTasks = "Только задачи без привязки к шаблону",
    included = "учтено",
    medianPlanningAhead = "Медианное время планирования",
    beforeStartFormat = "%s до начала",
    afterStartFormat = "%s после начала",
    atStart = "в момент начала",
    shortTasks = "До 30 мин",
    mediumTasks = "Более 30 мин – 2 ч",
    longTasks = "Более 2 ч",
    withTemplate = "С привязкой к шаблону",
    withoutTemplate = "Без привязки к шаблону",
    important = "Повышенный приоритет",
    weekends = "В выходные",
    longestBlock = "Самый длинный блок",
    busiestDay = "Самый загруженный день",
    activeDaysFormat = "%s из %s %s",
    dayUnit = "день|дня|дней",
    periodDaysFormat = "из %s %s периода",
    activeDayIncreaseFormat = "На %d %s больше",
    activeDayDecreaseFormat = "На %d %s меньше",
    activeDayUnchanged = "Без изменений",
    less = "Меньше",
    more = "Больше",
    heatmapRowDescFormat = "%s: самый загруженный интервал %02d:00–%02d:00, в среднем %d мин в час",
    heatmapCellFormat = "%s, %02d:00–%02d:00 · %d мин",
    heatmapDetailsAction = "Показать часы этого дня",
    dayPartRowDescFormat = "%s: максимальная нагрузка в %s, в среднем %d мин",
    averageLoadExplanation = "Средняя нагрузка учитывает дни без задач",
    averageLoadInfoDesc = "О расчёте средней нагрузки",
    averagePlannedMinutes = "Средняя запланированная нагрузка в минутах за час",
    unavailableValue = "—",
    hourShort = "ч",
    minuteShort = "мин",
    noData = "Нет данных за выбранный период",
    noDataSupporting = "Добавьте задачи или выберите другой диапазон",
    categoryNoData = "Нет задач этой категории за выбранный период",
    categoryNoDataSupporting = "Выберите другой диапазон",
    sectionNoData = "Недостаточно данных для этой секции",
    creationNoData = "Нет данных о времени создания задач без привязки к шаблону",
    error = "Не удалось загрузить данные",
    categoryError = "Не удалось загрузить аналитику категории",
    retry = "Повторить",
    loading = "Загрузка аналитики",
    openCategoryFormat = "Открыть аналитику категории %s",
    navigateBackDesc = "Назад",
    categoryUnavailable = "Категория недоступна",
    categoryUnavailableSupporting = "Возможно, она была удалена",
    withoutSubCategory = "Без подкатегории",
    categoryShare = "Доля всего плана",
    allPlan = "Весь план",
    taskCount = "Количество задач",
    timeLabel = "Время",
    tasksLabel = "Задачи",
    tasksMetric = "Задач",
    averageDuration = "Средняя длительность",
    medianDuration = "Медианная длительность",
    taskCountIncreaseFormat = "+%d",
    taskCountDecreaseFormat = "−%d",
    metricDurationIncreaseFormat = "На %s больше",
    metricDurationDecreaseFormat = "На %s меньше",
    completedCountIncreaseFormat = "+%d",
    completedCountDecreaseFormat = "−%d",
    completionIncreaseFormat = "На %s выше",
    completionDecreaseFormat = "На %s ниже",
    completionPreviousZero = "В прошлом периоде нет выполненных задач",
    categoryShareFormat = "%s от всего запланированного времени",
    categoryPreviousUnused = "В предыдущем периоде категория не использовалась",
    categoryTimeIncreaseFormat = "На %s больше времени",
    categoryTimeDecreaseFormat = "На %s меньше времени",
    busiestDayValueFormat = "%s · %s",
    dayPartNight = "Ночь",
    dayPartMorning = "Утро",
    dayPartDay = "День",
    dayPartEvening = "Вечер",
    statusCompleted = "Выполнено",
    statusSkipped = "Пропущено",
    statusUnfinished = "Впереди",
    selectDateRange = "Выберите диапазон дат",
    allWithoutSubCategory = "Все задачи без подкатегории",
    inCategory = "в категории",
    completionDropObservationFormat = "Доля выполнения категории снизилась на %s относительно предыдущего периода",
    busiestDayObservationFormat = "На %s приходится %s времени категории — это самый нагруженный день",
    dominantSubCategoryObservationFormat = "%s занимает %s времени категории",
)

internal val englishAnalyticsString = AnalyticsStrings(
    topAppBarTitle = "Analytics",
    otherError = "Something went wrong. Contact the developer.",
    lastSevenDays = "Last 7 days",
    week = "Week",
    month = "Month",
    halfYear = "Half-year",
    year = "Year",
    currentPeriod = "Current period",
    previousPeriodDesc = "Previous period",
    nextPeriodDesc = "Next period",
    previousMonthDesc = "Previous month",
    nextMonthDesc = "Next month",
    selectRangeDesc = "Select custom range",
    cancel = "Cancel",
    confirm = "Done",
    summaryTitle = "Period summary",
    summaryLastSevenDaysTitle = "7-day summary",
    summaryWeekTitle = "Week summary",
    summaryMonthTitle = "Month summary",
    summaryHalfYearTitle = "Half-year summary",
    summaryYearTitle = "Year summary",
    categoriesTitle = "Time by category",
    loadTitle = "Workload trend",
    creationTitle = "When tasks are created",
    durationStructureTitle = "Task duration structure",
    planSourceTitle = "Template links",
    keyMetricsTitle = "Key metrics",
    regularityTitle = "Planning regularity",
    busiestHoursTitle = "Busiest hours",
    categorySummaryTitle = "Category summary",
    subCategoriesTitle = "Time by subcategory",
    categoryLoadTitle = "Category trend",
    dayPartsTitle = "Time-of-day distribution",
    categoryTasksTitle = "Category tasks",
    observationTitle = "Observation",
    planned = "Planned",
    completed = "Completed",
    skipped = "Skipped",
    unfinished = "Upcoming",
    completionShare = "Completion share",
    completedCountFormat = "%s of %s",
    previousPeriod = "vs previous period",
    comparisonPreviousZero = "No completed tasks in the previous period",
    comparisonUnavailable = "Not enough data to compare",
    comparisonUnchanged = "No change",
    byTime = "By time",
    byTasks = "By tasks",
    showAll = "Show all",
    collapse = "Collapse",
    other = "Other",
    newCategory = "New",
    showAllCategories = "Show all categories",
    showAllTasks = "Show all tasks",
    tasksFormat = "Tasks: %s",
    loadTooltipFormat = "%s · %s · %s",
    categoryLoadTooltipFormat = "%s · %s: %s · whole plan: %s",
    median = "Median",
    average = "Average",
    createdInAdvance = "3+ days ahead",
    createdOneOrTwoDays = "1–2 days ahead",
    createdSameDay = "On the scheduled day",
    createdAfterStart = "After start",
    onlyUnlinkedTasks = "Only tasks not linked to a template",
    included = "included",
    medianPlanningAhead = "Median planning lead time",
    beforeStartFormat = "%s before start",
    afterStartFormat = "%s after start",
    atStart = "at start time",
    shortTasks = "Up to 30 minutes",
    mediumTasks = "Over 30 minutes to 2 hours",
    longTasks = "Over 2 hours",
    withTemplate = "Linked to template",
    withoutTemplate = "Not linked to template",
    important = "Higher priority",
    weekends = "On weekends",
    longestBlock = "Longest block",
    busiestDay = "Busiest day",
    activeDaysFormat = "%s of %s %s",
    dayUnit = "day|days|days",
    periodDaysFormat = "of %s %s in the period",
    activeDayIncreaseFormat = "%d more %s",
    activeDayDecreaseFormat = "%d fewer %s",
    activeDayUnchanged = "No change",
    less = "Less",
    more = "More",
    heatmapRowDescFormat = "%s: busiest interval %02d:00–%02d:00, %d min per hour on average",
    heatmapCellFormat = "%s, %02d:00–%02d:00 · %d min",
    heatmapDetailsAction = "Show hours for this day",
    dayPartRowDescFormat = "%s: busiest on %s, %d min on average",
    averageLoadExplanation = "Average workload includes days without tasks",
    averageLoadInfoDesc = "About average workload calculation",
    averagePlannedMinutes = "Average planned workload, minutes per hour",
    unavailableValue = "—",
    hourShort = "h",
    minuteShort = "min",
    noData = "No data for the selected period",
    noDataSupporting = "Add tasks or select another range",
    categoryNoData = "No tasks in this category for the selected period",
    categoryNoDataSupporting = "Select another range",
    sectionNoData = "Not enough data for this section",
    creationNoData = "No creation-time data for tasks without a template",
    error = "Data could not be loaded",
    categoryError = "Category analytics could not be loaded",
    retry = "Retry",
    loading = "Loading analytics",
    openCategoryFormat = "Open analytics for %s",
    navigateBackDesc = "Back",
    categoryUnavailable = "Category unavailable",
    categoryUnavailableSupporting = "It may have been deleted",
    withoutSubCategory = "No subcategory",
    categoryShare = "Share of the whole plan",
    allPlan = "Whole plan",
    taskCount = "Task count",
    timeLabel = "Time",
    tasksLabel = "Tasks",
    tasksMetric = "Tasks",
    averageDuration = "Average duration",
    medianDuration = "Median duration",
    taskCountIncreaseFormat = "+%d",
    taskCountDecreaseFormat = "−%d",
    metricDurationIncreaseFormat = "%s more",
    metricDurationDecreaseFormat = "%s less",
    completedCountIncreaseFormat = "+%d",
    completedCountDecreaseFormat = "−%d",
    completionIncreaseFormat = "Up %s",
    completionDecreaseFormat = "Down %s",
    completionPreviousZero = "No completed tasks in the previous period",
    categoryShareFormat = "%s of all planned time",
    categoryPreviousUnused = "The category was not used in the previous period",
    categoryTimeIncreaseFormat = "%s more time",
    categoryTimeDecreaseFormat = "%s less time",
    busiestDayValueFormat = "%s · %s",
    dayPartNight = "Night",
    dayPartMorning = "Morning",
    dayPartDay = "Day",
    dayPartEvening = "Evening",
    statusCompleted = "Completed",
    statusSkipped = "Skipped",
    statusUnfinished = "Upcoming",
    selectDateRange = "Select date range",
    allWithoutSubCategory = "All tasks have no subcategory",
    inCategory = "in category",
    completionDropObservationFormat = "The category completion share decreased by %s compared with the previous period",
    busiestDayObservationFormat = "%s accounts for %s of category time and is the busiest day",
    dominantSubCategoryObservationFormat = "%s accounts for %s of category time",
)

internal val germanAnalyticsString = englishAnalyticsString.copy(
    topAppBarTitle = "Analyse",
    otherError = "Etwas ist schiefgelaufen. Wenden Sie sich an den Entwickler.",
    lastSevenDays = "Letzte 7 Tage",
    week = "Woche",
    month = "Monat",
    halfYear = "Halbjahr",
    year = "Jahr",
    currentPeriod = "Aktueller Zeitraum",
    previousPeriodDesc = "Vorheriger Zeitraum",
    nextPeriodDesc = "Nächster Zeitraum",
    previousMonthDesc = "Vorheriger Monat",
    nextMonthDesc = "Nächster Monat",
    selectRangeDesc = "Benutzerdefinierten Zeitraum auswählen",
    cancel = "Abbrechen",
    confirm = "Fertig",
    summaryTitle = "Zeitraumübersicht",
    summaryLastSevenDaysTitle = "7-Tage-Übersicht",
    summaryWeekTitle = "Wochenübersicht",
    summaryMonthTitle = "Monatsübersicht",
    summaryHalfYearTitle = "Halbjahresübersicht",
    summaryYearTitle = "Jahresübersicht",
    categoriesTitle = "Zeit nach Kategorie",
    loadTitle = "Auslastungsverlauf",
    creationTitle = "Wann Aufgaben erstellt werden",
    durationStructureTitle = "Struktur der Aufgabendauer",
    planSourceTitle = "Vorlagenverknüpfung",
    keyMetricsTitle = "Kennzahlen",
    regularityTitle = "Planungsregelmäßigkeit",
    busiestHoursTitle = "Stärkste Stunden",
    categorySummaryTitle = "Kategorieübersicht",
    subCategoriesTitle = "Zeit nach Unterkategorie",
    categoryLoadTitle = "Kategorieverlauf",
    dayPartsTitle = "Verteilung nach Tageszeit",
    categoryTasksTitle = "Aufgaben der Kategorie",
    observationTitle = "Beobachtung",
    planned = "Geplant",
    completed = "Erledigt",
    skipped = "Verpasst",
    unfinished = "Bevorstehend",
    completionShare = "Erledigungsanteil",
    completedCountFormat = "%s von %s",
    previousPeriod = "zum vorherigen Zeitraum",
    comparisonPreviousZero = "Im vorherigen Zeitraum gab es keine erledigten Aufgaben",
    comparisonUnavailable = "Noch nicht genügend Aufgaben für einen Vergleich",
    comparisonUnchanged = "Unverändert",
    byTime = "Nach Zeit",
    byTasks = "Nach Aufgaben",
    showAll = "Alle anzeigen",
    collapse = "Einklappen",
    other = "Andere",
    newCategory = "Neu",
    showAllCategories = "Alle Kategorien anzeigen",
    showAllTasks = "Alle Aufgaben anzeigen",
    tasksFormat = "Aufgaben: %s",
    loadTooltipFormat = "%s · %s · %s",
    categoryLoadTooltipFormat = "%s · %s: %s · gesamter Plan: %s",
    median = "Median",
    average = "Durchschnitt",
    createdInAdvance = "3+ Tage im Voraus",
    createdOneOrTwoDays = "1–2 Tage im Voraus",
    createdSameDay = "Am geplanten Tag",
    createdAfterStart = "Nach Beginn",
    onlyUnlinkedTasks = "Nur Aufgaben ohne Vorlagenverknüpfung",
    included = "berücksichtigt",
    medianPlanningAhead = "Medianer Planungsvorlauf",
    beforeStartFormat = "%s vor Beginn",
    afterStartFormat = "%s nach Beginn",
    atStart = "zum Startzeitpunkt",
    shortTasks = "Bis 30 Minuten",
    mediumTasks = "Über 30 Minuten bis 2 Stunden",
    longTasks = "Über 2 Stunden",
    withTemplate = "Mit Vorlage verknüpft",
    withoutTemplate = "Nicht mit Vorlage verknüpft",
    important = "Höhere Priorität",
    weekends = "Am Wochenende",
    longestBlock = "Längster Block",
    busiestDay = "Stärkster Tag",
    activeDaysFormat = "%s von %s %s",
    dayUnit = "Tag|Tage|Tage",
    periodDaysFormat = "von %s %s im Zeitraum",
    activeDayIncreaseFormat = "%d %s mehr",
    activeDayDecreaseFormat = "%d %s weniger",
    activeDayUnchanged = "Keine Änderung",
    less = "Weniger",
    more = "Mehr",
    heatmapRowDescFormat = "%s: stärkstes Zeitfenster %02d:00–%02d:00, durchschnittlich %d Min. pro Stunde",
    heatmapCellFormat = "%s, %02d:00–%02d:00 · %d Min.",
    heatmapDetailsAction = "Stunden dieses Tages anzeigen",
    dayPartRowDescFormat = "%s: höchste Auslastung am %s, durchschnittlich %d Min.",
    averageLoadExplanation = "Die durchschnittliche Auslastung berücksichtigt Tage ohne Aufgaben",
    averageLoadInfoDesc = "Zur Berechnung der durchschnittlichen Auslastung",
    averagePlannedMinutes = "Durchschnittlich geplante Auslastung, Minuten pro Stunde",
    unavailableValue = "—",
    hourShort = "Std.",
    minuteShort = "Min.",
    noData = "Keine Daten für den ausgewählten Zeitraum",
    noDataSupporting = "Aufgaben hinzufügen oder einen anderen Zeitraum auswählen",
    categoryNoData = "Keine Aufgaben dieser Kategorie im ausgewählten Zeitraum",
    categoryNoDataSupporting = "Einen anderen Zeitraum auswählen",
    sectionNoData = "Nicht genügend Daten für diesen Abschnitt",
    creationNoData = "Keine Erstellungszeitdaten für Aufgaben ohne Vorlage",
    error = "Daten konnten nicht geladen werden",
    categoryError = "Kategorieanalyse konnte nicht geladen werden",
    retry = "Erneut versuchen",
    loading = "Analyse wird geladen",
    openCategoryFormat = "Analyse für %s öffnen",
    navigateBackDesc = "Zurück",
    categoryUnavailable = "Kategorie nicht verfügbar",
    categoryUnavailableSupporting = "Sie wurde möglicherweise gelöscht",
    withoutSubCategory = "Ohne Unterkategorie",
    categoryShare = "Anteil am Gesamtplan",
    allPlan = "Gesamter Plan",
    taskCount = "Aufgabenanzahl",
    timeLabel = "Zeit",
    tasksLabel = "Aufgaben",
    tasksMetric = "Aufgaben",
    averageDuration = "Durchschnittliche Dauer",
    medianDuration = "Mediane Dauer",
    taskCountIncreaseFormat = "+%d",
    taskCountDecreaseFormat = "−%d",
    metricDurationIncreaseFormat = "%s mehr",
    metricDurationDecreaseFormat = "%s weniger",
    completedCountIncreaseFormat = "+%d",
    completedCountDecreaseFormat = "−%d",
    completionIncreaseFormat = "%s höher als im vorherigen Zeitraum",
    completionDecreaseFormat = "%s niedriger als im vorherigen Zeitraum",
    completionPreviousZero = "Im vorherigen Zeitraum gab es keine erledigten Aufgaben",
    categoryShareFormat = "%s der gesamten geplanten Zeit",
    categoryPreviousUnused = "Die Kategorie wurde im vorherigen Zeitraum nicht verwendet",
    categoryTimeIncreaseFormat = "%s mehr Zeit als im vorherigen Zeitraum",
    categoryTimeDecreaseFormat = "%s weniger Zeit als im vorherigen Zeitraum",
    busiestDayValueFormat = "%s · %s",
    dayPartNight = "Nacht",
    dayPartMorning = "Morgen",
    dayPartDay = "Tag",
    dayPartEvening = "Abend",
    statusCompleted = "Erledigt",
    statusSkipped = "Verpasst",
    statusUnfinished = "Bevorstehend",
    selectDateRange = "Zeitraum auswählen",
    allWithoutSubCategory = "Alle Aufgaben sind ohne Unterkategorie",
    inCategory = "in der Kategorie",
    completionDropObservationFormat = "Der Erledigungsanteil der Kategorie sank gegenüber dem vorherigen Zeitraum um %s",
    busiestDayObservationFormat = "%s macht %s der Kategoriezeit aus und ist der stärkste Tag",
    dominantSubCategoryObservationFormat = "%s macht %s der Kategoriezeit aus",
)

internal val spanishAnalyticsString = englishAnalyticsString.copy(
    topAppBarTitle = "Estadísticas",
    otherError = "Algo salió mal. Contacta con el desarrollador.",
    lastSevenDays = "Últimos 7 días",
    week = "Semana",
    month = "Mes",
    halfYear = "Semestre",
    year = "Año",
    currentPeriod = "Periodo actual",
    previousPeriodDesc = "Periodo anterior",
    nextPeriodDesc = "Periodo siguiente",
    previousMonthDesc = "Mes anterior",
    nextMonthDesc = "Mes siguiente",
    selectRangeDesc = "Seleccionar intervalo personalizado",
    cancel = "Cancelar",
    confirm = "Listo",
    summaryTitle = "Resumen del periodo",
    summaryLastSevenDaysTitle = "Resumen de 7 días",
    summaryWeekTitle = "Resumen semanal",
    summaryMonthTitle = "Resumen mensual",
    summaryHalfYearTitle = "Resumen semestral",
    summaryYearTitle = "Resumen anual",
    categoriesTitle = "Tiempo por categoría",
    loadTitle = "Evolución de la carga",
    creationTitle = "Cuándo se crean las tareas",
    durationStructureTitle = "Estructura de duración de tareas",
    planSourceTitle = "Vinculación con plantillas",
    keyMetricsTitle = "Métricas clave",
    regularityTitle = "Regularidad de planificación",
    busiestHoursTitle = "Horas con más carga",
    categorySummaryTitle = "Resumen de categoría",
    subCategoriesTitle = "Tiempo por subcategoría",
    categoryLoadTitle = "Evolución de la categoría",
    dayPartsTitle = "Distribución por franja horaria",
    categoryTasksTitle = "Tareas de la categoría",
    observationTitle = "Observación",
    planned = "Planificado",
    completed = "Completado",
    skipped = "Omitido",
    unfinished = "Pendiente",
    completionShare = "Proporción completada",
    completedCountFormat = "%s de %s",
    previousPeriod = "frente al periodo anterior",
    comparisonPreviousZero = "No hubo tareas completadas en el periodo anterior",
    comparisonUnavailable = "Aún no hay suficientes tareas para comparar",
    comparisonUnchanged = "Sin cambios",
    byTime = "Por tiempo",
    byTasks = "Por tareas",
    showAll = "Mostrar todo",
    collapse = "Contraer",
    other = "Otras",
    newCategory = "Nueva",
    showAllCategories = "Mostrar todas las categorías",
    showAllTasks = "Mostrar todas las tareas",
    tasksFormat = "Tareas: %s",
    loadTooltipFormat = "%s · %s · %s",
    categoryLoadTooltipFormat = "%s · %s: %s · plan completo: %s",
    median = "Mediana",
    average = "Promedio",
    createdInAdvance = "Con 3+ días de antelación",
    createdOneOrTwoDays = "Con 1–2 días de antelación",
    createdSameDay = "El día programado",
    createdAfterStart = "Después del inicio",
    onlyUnlinkedTasks = "Solo tareas no vinculadas a una plantilla",
    included = "incluidas",
    medianPlanningAhead = "Mediana de antelación",
    beforeStartFormat = "%s antes del inicio",
    afterStartFormat = "%s después del inicio",
    atStart = "a la hora de inicio",
    shortTasks = "Hasta 30 minutos",
    mediumTasks = "Más de 30 minutos y hasta 2 horas",
    longTasks = "Más de 2 horas",
    withTemplate = "Vinculadas a una plantilla",
    withoutTemplate = "Sin vincular a plantilla",
    important = "Prioridad alta",
    weekends = "En fin de semana",
    longestBlock = "Bloque más largo",
    busiestDay = "Día con más carga",
    activeDaysFormat = "%s de %s %s",
    dayUnit = "día|días|días",
    periodDaysFormat = "de %s %s del periodo",
    activeDayIncreaseFormat = "%d %s más",
    activeDayDecreaseFormat = "%d %s menos",
    activeDayUnchanged = "Sin cambios",
    less = "Menos",
    more = "Más",
    heatmapRowDescFormat = "%s: intervalo con más carga %02d:00–%02d:00, %d min por hora de media",
    heatmapCellFormat = "%s, %02d:00–%02d:00 · %d min",
    heatmapDetailsAction = "Mostrar las horas de este día",
    dayPartRowDescFormat = "%s: mayor carga el %s, %d min de media",
    averageLoadExplanation = "La carga media incluye los días sin tareas",
    averageLoadInfoDesc = "Acerca del cálculo de la carga media",
    averagePlannedMinutes = "Carga planificada media, minutos por hora",
    unavailableValue = "—",
    hourShort = "h",
    minuteShort = "min",
    noData = "No hay datos para el periodo seleccionado",
    noDataSupporting = "Añade tareas o selecciona otro intervalo",
    categoryNoData = "No hay tareas de esta categoría en el periodo seleccionado",
    categoryNoDataSupporting = "Selecciona otro intervalo",
    sectionNoData = "No hay suficientes datos para esta sección",
    creationNoData = "No hay datos de creación para tareas sin plantilla",
    error = "No se pudieron cargar los datos",
    categoryError = "No se pudo cargar el análisis de la categoría",
    retry = "Reintentar",
    loading = "Cargando análisis",
    openCategoryFormat = "Abrir análisis de %s",
    navigateBackDesc = "Atrás",
    categoryUnavailable = "Categoría no disponible",
    categoryUnavailableSupporting = "Puede que se haya eliminado",
    withoutSubCategory = "Sin subcategoría",
    categoryShare = "Proporción del plan completo",
    allPlan = "Plan completo",
    taskCount = "Número de tareas",
    timeLabel = "Tiempo",
    tasksLabel = "Tareas",
    tasksMetric = "Tareas",
    averageDuration = "Duración media",
    medianDuration = "Duración mediana",
    taskCountIncreaseFormat = "+%d",
    taskCountDecreaseFormat = "−%d",
    metricDurationIncreaseFormat = "%s más",
    metricDurationDecreaseFormat = "%s menos",
    completedCountIncreaseFormat = "+%d",
    completedCountDecreaseFormat = "−%d",
    completionIncreaseFormat = "%s más alta que en el periodo anterior",
    completionDecreaseFormat = "%s más baja que en el periodo anterior",
    completionPreviousZero = "No hubo tareas completadas en el periodo anterior",
    categoryShareFormat = "%s de todo el tiempo planificado",
    categoryPreviousUnused = "La categoría no se utilizó en el periodo anterior",
    categoryTimeIncreaseFormat = "%s más de tiempo que en el periodo anterior",
    categoryTimeDecreaseFormat = "%s menos de tiempo que en el periodo anterior",
    busiestDayValueFormat = "%s · %s",
    dayPartNight = "Noche",
    dayPartMorning = "Mañana",
    dayPartDay = "Día",
    dayPartEvening = "Tarde",
    statusCompleted = "Completada",
    statusSkipped = "Omitida",
    statusUnfinished = "Pendiente",
    selectDateRange = "Seleccionar intervalo de fechas",
    allWithoutSubCategory = "Todas las tareas están sin subcategoría",
    inCategory = "en la categoría",
    completionDropObservationFormat = "La proporción completada de la categoría bajó un %s frente al periodo anterior",
    busiestDayObservationFormat = "%s representa el %s del tiempo de la categoría y es el día con más carga",
    dominantSubCategoryObservationFormat = "%s representa el %s del tiempo de la categoría",
)

internal val persianAnalyticsString = englishAnalyticsString.copy(
    topAppBarTitle = "تحلیل ها",
    otherError = "مشکلی پیش آمد. با توسعه‌دهنده تماس بگیرید.",
    lastSevenDays = "۷ روز گذشته",
    week = "هفته",
    month = "ماه",
    halfYear = "نیم‌سال",
    year = "سال",
    currentPeriod = "دوره فعلی",
    previousPeriodDesc = "دوره قبلی",
    nextPeriodDesc = "دوره بعدی",
    previousMonthDesc = "ماه قبل",
    nextMonthDesc = "ماه بعد",
    selectRangeDesc = "انتخاب بازه دلخواه",
    cancel = "لغو",
    confirm = "انجام شد",
    summaryTitle = "خلاصه دوره",
    summaryLastSevenDaysTitle = "خلاصه ۷ روزه",
    summaryWeekTitle = "خلاصه هفته",
    summaryMonthTitle = "خلاصه ماه",
    summaryHalfYearTitle = "خلاصه نیم‌سال",
    summaryYearTitle = "خلاصه سال",
    categoriesTitle = "زمان بر اساس دسته‌بندی",
    loadTitle = "روند حجم کار",
    creationTitle = "زمان ایجاد کارها",
    durationStructureTitle = "ساختار مدت کارها",
    planSourceTitle = "پیوند با الگو",
    keyMetricsTitle = "شاخص‌های کلیدی",
    regularityTitle = "نظم برنامه‌ریزی",
    busiestHoursTitle = "شلوغ‌ترین ساعت‌ها",
    categorySummaryTitle = "خلاصه دسته‌بندی",
    subCategoriesTitle = "زمان بر اساس زیردسته",
    categoryLoadTitle = "روند دسته‌بندی",
    dayPartsTitle = "توزیع بر اساس زمان روز",
    categoryTasksTitle = "کارهای دسته‌بندی",
    observationTitle = "مشاهده",
    planned = "برنامه‌ریزی‌شده",
    completed = "انجام‌شده",
    skipped = "ازدست‌رفته",
    unfinished = "پیش رو",
    completionShare = "نسبت انجام",
    completedCountFormat = "%s از %s",
    previousPeriod = "نسبت به دوره قبلی",
    comparisonPreviousZero = "در دوره قبلی کار انجام‌شده‌ای وجود نداشت",
    comparisonUnavailable = "هنوز کار کافی برای مقایسه وجود ندارد",
    comparisonUnchanged = "بدون تغییر",
    byTime = "بر اساس زمان",
    byTasks = "بر اساس کارها",
    showAll = "نمایش همه",
    collapse = "جمع کردن",
    other = "سایر",
    newCategory = "جدید",
    showAllCategories = "نمایش همه دسته‌بندی‌ها",
    showAllTasks = "نمایش همه کارها",
    tasksFormat = "تعداد کارها: %s",
    loadTooltipFormat = "%s · %s · %s",
    categoryLoadTooltipFormat = "%s · %s: %s · کل برنامه: %s",
    median = "میانه",
    average = "میانگین",
    createdInAdvance = "۳ روز یا بیشتر زودتر",
    createdOneOrTwoDays = "۱ تا ۲ روز زودتر",
    createdSameDay = "در روز برنامه‌ریزی‌شده",
    createdAfterStart = "پس از شروع",
    onlyUnlinkedTasks = "فقط کارهای بدون پیوند به الگو",
    included = "محاسبه‌شده",
    medianPlanningAhead = "میانه زمان برنامه‌ریزی زودتر",
    beforeStartFormat = "%s پیش از شروع",
    afterStartFormat = "%s پس از شروع",
    atStart = "در زمان شروع",
    shortTasks = "تا ۳۰ دقیقه",
    mediumTasks = "بیش از ۳۰ دقیقه تا ۲ ساعت",
    longTasks = "بیش از ۲ ساعت",
    withTemplate = "پیوندخورده به الگو",
    withoutTemplate = "بدون پیوند به الگو",
    important = "اولویت بالاتر",
    weekends = "در آخر هفته",
    longestBlock = "طولانی‌ترین بازه",
    busiestDay = "شلوغ‌ترین روز",
    activeDaysFormat = "%s از %s %s",
    dayUnit = "روز|روز|روز",
    periodDaysFormat = "از %s %s دوره",
    activeDayIncreaseFormat = "%d %s بیشتر",
    activeDayDecreaseFormat = "%d %s کمتر",
    activeDayUnchanged = "بدون تغییر",
    less = "کمتر",
    more = "بیشتر",
    heatmapRowDescFormat = "%s: شلوغ‌ترین بازه %02d:00–%02d:00، میانگین %d دقیقه در ساعت",
    heatmapCellFormat = "%s، %02d:00–%02d:00 · %d دقیقه",
    heatmapDetailsAction = "نمایش ساعت‌های این روز",
    dayPartRowDescFormat = "%s: بیشترین حجم در %s، میانگین %d دقیقه",
    averageLoadExplanation = "میانگین حجم کار روزهای بدون کار را نیز شامل می‌شود",
    averageLoadInfoDesc = "درباره محاسبه میانگین حجم کار",
    averagePlannedMinutes = "میانگین حجم برنامه‌ریزی‌شده، دقیقه در ساعت",
    unavailableValue = "—",
    hourShort = "ساعت",
    minuteShort = "دقیقه",
    noData = "برای دوره انتخاب‌شده داده‌ای وجود ندارد",
    noDataSupporting = "کار اضافه کنید یا بازه دیگری را انتخاب کنید",
    categoryNoData = "در دوره انتخاب‌شده کاری از این دسته وجود ندارد",
    categoryNoDataSupporting = "بازه دیگری را انتخاب کنید",
    sectionNoData = "برای این بخش داده کافی وجود ندارد",
    creationNoData = "برای کارهای بدون الگو داده زمان ایجاد وجود ندارد",
    error = "بارگذاری داده‌ها ممکن نشد",
    categoryError = "بارگذاری تحلیل دسته‌بندی ممکن نشد",
    retry = "تلاش دوباره",
    loading = "در حال بارگذاری تحلیل",
    openCategoryFormat = "باز کردن تحلیل %s",
    navigateBackDesc = "بازگشت",
    categoryUnavailable = "دسته‌بندی در دسترس نیست",
    categoryUnavailableSupporting = "ممکن است حذف شده باشد",
    withoutSubCategory = "بدون زیردسته",
    categoryShare = "سهم از کل برنامه",
    allPlan = "کل برنامه",
    taskCount = "تعداد کارها",
    timeLabel = "زمان",
    tasksLabel = "کارها",
    tasksMetric = "کار",
    averageDuration = "میانگین مدت",
    medianDuration = "میانه مدت",
    taskCountIncreaseFormat = "+%d",
    taskCountDecreaseFormat = "−%d",
    metricDurationIncreaseFormat = "%s بیشتر",
    metricDurationDecreaseFormat = "%s کمتر",
    completedCountIncreaseFormat = "+%d",
    completedCountDecreaseFormat = "−%d",
    completionIncreaseFormat = "%s بیشتر از دوره قبل",
    completionDecreaseFormat = "%s کمتر از دوره قبل",
    completionPreviousZero = "در دوره قبلی کار انجام‌شده‌ای وجود نداشت",
    categoryShareFormat = "%s از کل زمان برنامه‌ریزی‌شده",
    categoryPreviousUnused = "این دسته در دوره قبلی استفاده نشده بود",
    categoryTimeIncreaseFormat = "%s زمان بیشتر از دوره قبلی",
    categoryTimeDecreaseFormat = "%s زمان کمتر از دوره قبلی",
    busiestDayValueFormat = "%s · %s",
    dayPartNight = "شب",
    dayPartMorning = "صبح",
    dayPartDay = "روز",
    dayPartEvening = "عصر",
    statusCompleted = "انجام‌شده",
    statusSkipped = "ازدست‌رفته",
    statusUnfinished = "پیش رو",
    selectDateRange = "انتخاب بازه تاریخ",
    allWithoutSubCategory = "همه کارها بدون زیردسته هستند",
    inCategory = "در دسته‌بندی",
    completionDropObservationFormat = "نسبت انجام این دسته نسبت به دوره قبلی %s کاهش یافته است",
    busiestDayObservationFormat = "%s برابر با %s از زمان دسته است و شلوغ‌ترین روز محسوب می‌شود",
    dominantSubCategoryObservationFormat = "%s برابر با %s از زمان دسته است",
)

internal val frenchAnalyticsString = englishAnalyticsString.copy(
    topAppBarTitle = "Statistiques",
    otherError = "Une erreur est survenue. Contactez le développeur.",
    lastSevenDays = "7 derniers jours",
    week = "Semaine",
    month = "Mois",
    halfYear = "Semestre",
    year = "Année",
    currentPeriod = "Période actuelle",
    previousPeriodDesc = "Période précédente",
    nextPeriodDesc = "Période suivante",
    previousMonthDesc = "Mois précédent",
    nextMonthDesc = "Mois suivant",
    selectRangeDesc = "Sélectionner une période personnalisée",
    cancel = "Annuler",
    confirm = "Terminé",
    summaryTitle = "Résumé de la période",
    summaryLastSevenDaysTitle = "Résumé sur 7 jours",
    summaryWeekTitle = "Résumé de la semaine",
    summaryMonthTitle = "Résumé du mois",
    summaryHalfYearTitle = "Résumé du semestre",
    summaryYearTitle = "Résumé de l’année",
    categoriesTitle = "Temps par catégorie",
    loadTitle = "Évolution de la charge",
    creationTitle = "Moment de création des tâches",
    durationStructureTitle = "Structure de durée des tâches",
    planSourceTitle = "Liens avec les modèles",
    keyMetricsTitle = "Indicateurs clés",
    regularityTitle = "Régularité de la planification",
    busiestHoursTitle = "Heures les plus chargées",
    categorySummaryTitle = "Résumé de la catégorie",
    subCategoriesTitle = "Temps par sous-catégorie",
    categoryLoadTitle = "Évolution de la catégorie",
    dayPartsTitle = "Répartition par moment de la journée",
    categoryTasksTitle = "Tâches de la catégorie",
    observationTitle = "Observation",
    planned = "Planifié",
    completed = "Terminé",
    skipped = "Manqué",
    unfinished = "À venir",
    completionShare = "Part terminée",
    completedCountFormat = "%s sur %s",
    previousPeriod = "par rapport à la période précédente",
    comparisonPreviousZero = "Aucune tâche n’était terminée pendant la période précédente",
    comparisonUnavailable = "Pas encore assez de tâches pour comparer",
    comparisonUnchanged = "Aucun changement",
    byTime = "Par temps",
    byTasks = "Par tâches",
    showAll = "Tout afficher",
    collapse = "Réduire",
    other = "Autres",
    newCategory = "Nouvelle",
    showAllCategories = "Afficher toutes les catégories",
    showAllTasks = "Afficher toutes les tâches",
    tasksFormat = "Tâches : %s",
    loadTooltipFormat = "%s · %s · %s",
    categoryLoadTooltipFormat = "%s · %s : %s · planning complet : %s",
    median = "Médiane",
    average = "Moyenne",
    createdInAdvance = "3 jours ou plus à l’avance",
    createdOneOrTwoDays = "1–2 jours à l’avance",
    createdSameDay = "Le jour planifié",
    createdAfterStart = "Après le début",
    onlyUnlinkedTasks = "Uniquement les tâches non liées à un modèle",
    included = "prises en compte",
    medianPlanningAhead = "Anticipation médiane",
    beforeStartFormat = "%s avant le début",
    afterStartFormat = "%s après le début",
    atStart = "à l’heure de début",
    shortTasks = "Jusqu’à 30 minutes",
    mediumTasks = "Plus de 30 minutes à 2 heures",
    longTasks = "Plus de 2 heures",
    withTemplate = "Liées à un modèle",
    withoutTemplate = "Non liées à un modèle",
    important = "Priorité élevée",
    weekends = "Le week-end",
    longestBlock = "Bloc le plus long",
    busiestDay = "Jour le plus chargé",
    activeDaysFormat = "%s sur %s %s",
    dayUnit = "jour|jours|jours",
    periodDaysFormat = "sur %s %s de la période",
    activeDayIncreaseFormat = "%d %s de plus",
    activeDayDecreaseFormat = "%d %s de moins",
    activeDayUnchanged = "Aucun changement",
    less = "Moins",
    more = "Plus",
    heatmapRowDescFormat = "%s : intervalle le plus chargé %02d:00–%02d:00, %d min par heure en moyenne",
    heatmapCellFormat = "%s, %02d:00–%02d:00 · %d min",
    heatmapDetailsAction = "Afficher les heures de ce jour",
    dayPartRowDescFormat = "%s : charge maximale le %s, %d min en moyenne",
    averageLoadExplanation = "La charge moyenne inclut les jours sans tâche",
    averageLoadInfoDesc = "À propos du calcul de la charge moyenne",
    averagePlannedMinutes = "Charge planifiée moyenne, minutes par heure",
    unavailableValue = "—",
    hourShort = "h",
    minuteShort = "min",
    noData = "Aucune donnée pour la période sélectionnée",
    noDataSupporting = "Ajoutez des tâches ou sélectionnez une autre période",
    categoryNoData = "Aucune tâche de cette catégorie pour la période sélectionnée",
    categoryNoDataSupporting = "Sélectionnez une autre période",
    sectionNoData = "Pas assez de données pour cette section",
    creationNoData = "Aucune donnée de création pour les tâches sans modèle",
    error = "Impossible de charger les données",
    categoryError = "Impossible de charger l’analyse de la catégorie",
    retry = "Réessayer",
    loading = "Chargement de l’analyse",
    openCategoryFormat = "Ouvrir l’analyse de %s",
    navigateBackDesc = "Retour",
    categoryUnavailable = "Catégorie indisponible",
    categoryUnavailableSupporting = "Elle a peut-être été supprimée",
    withoutSubCategory = "Sans sous-catégorie",
    categoryShare = "Part du planning complet",
    allPlan = "Planning complet",
    taskCount = "Nombre de tâches",
    timeLabel = "Temps",
    tasksLabel = "Tâches",
    tasksMetric = "Tâches",
    averageDuration = "Durée moyenne",
    medianDuration = "Durée médiane",
    taskCountIncreaseFormat = "+%d",
    taskCountDecreaseFormat = "−%d",
    metricDurationIncreaseFormat = "%s de plus",
    metricDurationDecreaseFormat = "%s de moins",
    completedCountIncreaseFormat = "+%d",
    completedCountDecreaseFormat = "−%d",
    completionIncreaseFormat = "%s plus élevée que pendant la période précédente",
    completionDecreaseFormat = "%s plus faible que pendant la période précédente",
    completionPreviousZero = "Aucune tâche n’était terminée pendant la période précédente",
    categoryShareFormat = "%s de tout le temps planifié",
    categoryPreviousUnused = "La catégorie n’était pas utilisée pendant la période précédente",
    categoryTimeIncreaseFormat = "%s de temps en plus que pendant la période précédente",
    categoryTimeDecreaseFormat = "%s de temps en moins que pendant la période précédente",
    busiestDayValueFormat = "%s · %s",
    dayPartNight = "Nuit",
    dayPartMorning = "Matin",
    dayPartDay = "Journée",
    dayPartEvening = "Soir",
    statusCompleted = "Terminée",
    statusSkipped = "Manquée",
    statusUnfinished = "À venir",
    selectDateRange = "Sélectionner une période",
    allWithoutSubCategory = "Toutes les tâches sont sans sous-catégorie",
    inCategory = "dans la catégorie",
    completionDropObservationFormat = "La part terminée de la catégorie a diminué de %s par rapport à la période précédente",
    busiestDayObservationFormat = "%s représente %s du temps de la catégorie et est le jour le plus chargé",
    dominantSubCategoryObservationFormat = "%s représente %s du temps de la catégorie",
)

internal val brazilianPortugueseAnalyticsString = englishAnalyticsString.copy(
    topAppBarTitle = "Análises",
    otherError = "Algo deu errado. Entre em contato com o desenvolvedor.",
    lastSevenDays = "Últimos 7 dias",
    week = "Semana",
    month = "Mês",
    halfYear = "Semestre",
    year = "Ano",
    currentPeriod = "Período atual",
    previousPeriodDesc = "Período anterior",
    nextPeriodDesc = "Próximo período",
    previousMonthDesc = "Mês anterior",
    nextMonthDesc = "Próximo mês",
    selectRangeDesc = "Selecionar intervalo personalizado",
    cancel = "Cancelar",
    confirm = "Concluir",
    summaryTitle = "Resumo do período",
    summaryLastSevenDaysTitle = "Resumo de 7 dias",
    summaryWeekTitle = "Resumo da semana",
    summaryMonthTitle = "Resumo do mês",
    summaryHalfYearTitle = "Resumo do semestre",
    summaryYearTitle = "Resumo do ano",
    categoriesTitle = "Tempo por categoria",
    loadTitle = "Evolução da carga",
    creationTitle = "Quando as tarefas são criadas",
    durationStructureTitle = "Estrutura de duração das tarefas",
    planSourceTitle = "Vínculo com modelos",
    keyMetricsTitle = "Métricas principais",
    regularityTitle = "Regularidade do planejamento",
    busiestHoursTitle = "Horários mais ocupados",
    categorySummaryTitle = "Resumo da categoria",
    subCategoriesTitle = "Tempo por subcategoria",
    categoryLoadTitle = "Evolução da categoria",
    dayPartsTitle = "Distribuição por período do dia",
    categoryTasksTitle = "Tarefas da categoria",
    observationTitle = "Observação",
    planned = "Planejado",
    completed = "Concluído",
    skipped = "Perdido",
    unfinished = "A seguir",
    completionShare = "Percentual concluído",
    completedCountFormat = "%s de %s",
    previousPeriod = "em relação ao período anterior",
    comparisonPreviousZero = "Não houve tarefas concluídas no período anterior",
    comparisonUnavailable = "Ainda não há tarefas suficientes para comparar",
    comparisonUnchanged = "Sem alterações",
    byTime = "Por tempo",
    byTasks = "Por tarefas",
    showAll = "Mostrar tudo",
    collapse = "Recolher",
    other = "Outras",
    newCategory = "Nova",
    showAllCategories = "Mostrar todas as categorias",
    showAllTasks = "Mostrar todas as tarefas",
    tasksFormat = "Tarefas: %s",
    loadTooltipFormat = "%s · %s · %s",
    categoryLoadTooltipFormat = "%s · %s: %s · plano completo: %s",
    median = "Mediana",
    average = "Média",
    createdInAdvance = "Com 3+ dias de antecedência",
    createdOneOrTwoDays = "Com 1–2 dias de antecedência",
    createdSameDay = "No dia programado",
    createdAfterStart = "Após o início",
    onlyUnlinkedTasks = "Apenas tarefas sem vínculo com modelo",
    included = "incluídas",
    medianPlanningAhead = "Mediana de antecedência",
    beforeStartFormat = "%s antes do início",
    afterStartFormat = "%s após o início",
    atStart = "no horário de início",
    shortTasks = "Até 30 minutos",
    mediumTasks = "Mais de 30 minutos até 2 horas",
    longTasks = "Mais de 2 horas",
    withTemplate = "Vinculadas a um modelo",
    withoutTemplate = "Sem vínculo com modelo",
    important = "Prioridade alta",
    weekends = "Nos fins de semana",
    longestBlock = "Bloco mais longo",
    busiestDay = "Dia mais ocupado",
    activeDaysFormat = "%s de %s %s",
    dayUnit = "dia|dias|dias",
    periodDaysFormat = "de %s %s do período",
    activeDayIncreaseFormat = "%d %s a mais",
    activeDayDecreaseFormat = "%d %s a menos",
    activeDayUnchanged = "Sem alteração",
    less = "Menos",
    more = "Mais",
    heatmapRowDescFormat = "%s: intervalo mais ocupado %02d:00–%02d:00, média de %d min por hora",
    heatmapCellFormat = "%s, %02d:00–%02d:00 · %d min",
    heatmapDetailsAction = "Mostrar os horários deste dia",
    dayPartRowDescFormat = "%s: maior carga em %s, média de %d min",
    averageLoadExplanation = "A carga média inclui dias sem tarefas",
    averageLoadInfoDesc = "Sobre o cálculo da carga média",
    averagePlannedMinutes = "Carga planejada média, minutos por hora",
    unavailableValue = "—",
    hourShort = "h",
    minuteShort = "min",
    noData = "Sem dados para o período selecionado",
    noDataSupporting = "Adicione tarefas ou selecione outro intervalo",
    categoryNoData = "Sem tarefas desta categoria no período selecionado",
    categoryNoDataSupporting = "Selecione outro intervalo",
    sectionNoData = "Dados insuficientes para esta seção",
    creationNoData = "Sem dados de criação para tarefas sem modelo",
    error = "Não foi possível carregar os dados",
    categoryError = "Não foi possível carregar a análise da categoria",
    retry = "Tentar novamente",
    loading = "Carregando análise",
    openCategoryFormat = "Abrir análise de %s",
    navigateBackDesc = "Voltar",
    categoryUnavailable = "Categoria indisponível",
    categoryUnavailableSupporting = "Ela pode ter sido excluída",
    withoutSubCategory = "Sem subcategoria",
    categoryShare = "Percentual do plano completo",
    allPlan = "Plano completo",
    taskCount = "Quantidade de tarefas",
    timeLabel = "Tempo",
    tasksLabel = "Tarefas",
    tasksMetric = "Tarefas",
    averageDuration = "Duração média",
    medianDuration = "Duração mediana",
    taskCountIncreaseFormat = "+%d",
    taskCountDecreaseFormat = "−%d",
    metricDurationIncreaseFormat = "%s a mais",
    metricDurationDecreaseFormat = "%s a menos",
    completedCountIncreaseFormat = "+%d",
    completedCountDecreaseFormat = "−%d",
    completionIncreaseFormat = "%s maior que no período anterior",
    completionDecreaseFormat = "%s menor que no período anterior",
    completionPreviousZero = "Não houve tarefas concluídas no período anterior",
    categoryShareFormat = "%s de todo o tempo planejado",
    categoryPreviousUnused = "A categoria não foi usada no período anterior",
    categoryTimeIncreaseFormat = "%s mais tempo que no período anterior",
    categoryTimeDecreaseFormat = "%s menos tempo que no período anterior",
    busiestDayValueFormat = "%s · %s",
    dayPartNight = "Noite",
    dayPartMorning = "Manhã",
    dayPartDay = "Dia",
    dayPartEvening = "Fim da tarde",
    statusCompleted = "Concluída",
    statusSkipped = "Perdida",
    statusUnfinished = "A seguir",
    selectDateRange = "Selecionar intervalo de datas",
    allWithoutSubCategory = "Todas as tarefas estão sem subcategoria",
    inCategory = "na categoria",
    completionDropObservationFormat = "O percentual concluído da categoria caiu %s em relação ao período anterior",
    busiestDayObservationFormat = "%s representa %s do tempo da categoria e é o dia mais ocupado",
    dominantSubCategoryObservationFormat = "%s representa %s do tempo da categoria",
)

internal val turkishAnalyticsString = englishAnalyticsString.copy(
    topAppBarTitle = "Analiz",
    otherError = "Bir şeyler ters gitti. Geliştiriciyle iletişime geçin.",
    lastSevenDays = "Son 7 gün",
    week = "Hafta",
    month = "Ay",
    halfYear = "Yarı yıl",
    year = "Yıl",
    currentPeriod = "Geçerli dönem",
    previousPeriodDesc = "Önceki dönem",
    nextPeriodDesc = "Sonraki dönem",
    previousMonthDesc = "Önceki ay",
    nextMonthDesc = "Sonraki ay",
    selectRangeDesc = "Özel aralık seç",
    cancel = "İptal",
    confirm = "Bitti",
    summaryTitle = "Dönem özeti",
    summaryLastSevenDaysTitle = "7 günlük özet",
    summaryWeekTitle = "Hafta özeti",
    summaryMonthTitle = "Ay özeti",
    summaryHalfYearTitle = "Yarı yıl özeti",
    summaryYearTitle = "Yıl özeti",
    categoriesTitle = "Kategoriye göre süre",
    loadTitle = "İş yükü eğilimi",
    creationTitle = "Görevlerin oluşturulma zamanı",
    durationStructureTitle = "Görev süresi yapısı",
    planSourceTitle = "Şablon bağlantıları",
    keyMetricsTitle = "Temel metrikler",
    regularityTitle = "Planlama düzeni",
    busiestHoursTitle = "En yoğun saatler",
    categorySummaryTitle = "Kategori özeti",
    subCategoriesTitle = "Alt kategoriye göre süre",
    categoryLoadTitle = "Kategori eğilimi",
    dayPartsTitle = "Günün saatlerine göre dağılım",
    categoryTasksTitle = "Kategori görevleri",
    observationTitle = "Gözlem",
    planned = "Planlanan",
    completed = "Tamamlanan",
    skipped = "Kaçırılan",
    unfinished = "Yaklaşan",
    completionShare = "Tamamlanma oranı",
    completedCountFormat = "%s / %s",
    previousPeriod = "önceki döneme göre",
    comparisonPreviousZero = "Önceki dönemde tamamlanan görev yoktu",
    comparisonUnavailable = "Karşılaştırma için henüz yeterli görev yok",
    comparisonUnchanged = "Değişiklik yok",
    byTime = "Süreye göre",
    byTasks = "Göreve göre",
    showAll = "Tümünü göster",
    collapse = "Daralt",
    other = "Diğer",
    newCategory = "Yeni",
    showAllCategories = "Tüm kategorileri göster",
    showAllTasks = "Tüm görevleri göster",
    tasksFormat = "Görevler: %s",
    loadTooltipFormat = "%s · %s · %s",
    categoryLoadTooltipFormat = "%s · %s: %s · tüm plan: %s",
    median = "Medyan",
    average = "Ortalama",
    createdInAdvance = "3+ gün önce",
    createdOneOrTwoDays = "1–2 gün önce",
    createdSameDay = "Planlanan gün",
    createdAfterStart = "Başlangıçtan sonra",
    onlyUnlinkedTasks = "Yalnızca şablona bağlı olmayan görevler",
    included = "dahil",
    medianPlanningAhead = "Medyan planlama öncesi süre",
    beforeStartFormat = "başlangıçtan %s önce",
    afterStartFormat = "başlangıçtan %s sonra",
    atStart = "başlangıç saatinde",
    shortTasks = "30 dakikaya kadar",
    mediumTasks = "30 dakikadan fazla–2 saat",
    longTasks = "2 saatten uzun",
    withTemplate = "Şablona bağlı",
    withoutTemplate = "Şablona bağlı değil",
    important = "Yüksek öncelik",
    weekends = "Hafta sonları",
    longestBlock = "En uzun blok",
    busiestDay = "En yoğun gün",
    activeDaysFormat = "%s / %s %s",
    dayUnit = "gün|gün|gün",
    periodDaysFormat = "dönemdeki %s %s içinden",
    activeDayIncreaseFormat = "%d %s daha fazla",
    activeDayDecreaseFormat = "%d %s daha az",
    activeDayUnchanged = "Değişiklik yok",
    less = "Daha az",
    more = "Daha fazla",
    heatmapRowDescFormat = "%s: en yoğun aralık %02d:00–%02d:00, saatte ortalama %d dk",
    heatmapCellFormat = "%s, %02d:00–%02d:00 · %d dk",
    heatmapDetailsAction = "Bu günün saatlerini göster",
    dayPartRowDescFormat = "%s: en yoğun %s, ortalama %d dk",
    averageLoadExplanation = "Ortalama iş yüküne görevsiz günler de dahildir",
    averageLoadInfoDesc = "Ortalama iş yükü hesaplaması hakkında",
    averagePlannedMinutes = "Ortalama planlanan iş yükü, saat başına dakika",
    unavailableValue = "—",
    hourShort = "sa",
    minuteShort = "dk",
    noData = "Seçilen dönem için veri yok",
    noDataSupporting = "Görev ekleyin veya başka bir aralık seçin",
    categoryNoData = "Seçilen dönemde bu kategoride görev yok",
    categoryNoDataSupporting = "Başka bir aralık seçin",
    sectionNoData = "Bu bölüm için yeterli veri yok",
    creationNoData = "Şablonsuz görevler için oluşturma zamanı verisi yok",
    error = "Veriler yüklenemedi",
    categoryError = "Kategori analizi yüklenemedi",
    retry = "Yeniden dene",
    loading = "Analiz yükleniyor",
    openCategoryFormat = "%s analizini aç",
    navigateBackDesc = "Geri",
    categoryUnavailable = "Kategori kullanılamıyor",
    categoryUnavailableSupporting = "Silinmiş olabilir",
    withoutSubCategory = "Alt kategori yok",
    categoryShare = "Tüm plandaki pay",
    allPlan = "Tüm plan",
    taskCount = "Görev sayısı",
    timeLabel = "Süre",
    tasksLabel = "Görevler",
    tasksMetric = "Görev",
    averageDuration = "Ortalama süre",
    medianDuration = "Medyan süre",
    taskCountIncreaseFormat = "+%d",
    taskCountDecreaseFormat = "−%d",
    metricDurationIncreaseFormat = "%s daha fazla",
    metricDurationDecreaseFormat = "%s daha az",
    completedCountIncreaseFormat = "+%d",
    completedCountDecreaseFormat = "−%d",
    completionIncreaseFormat = "önceki döneme göre %s daha yüksek",
    completionDecreaseFormat = "önceki döneme göre %s daha düşük",
    completionPreviousZero = "Önceki dönemde tamamlanan görev yoktu",
    categoryShareFormat = "tüm planlanan sürenin %s kadarı",
    categoryPreviousUnused = "Kategori önceki dönemde kullanılmadı",
    categoryTimeIncreaseFormat = "önceki dönemden %s daha fazla süre",
    categoryTimeDecreaseFormat = "önceki dönemden %s daha az süre",
    busiestDayValueFormat = "%s · %s",
    dayPartNight = "Gece",
    dayPartMorning = "Sabah",
    dayPartDay = "Gündüz",
    dayPartEvening = "Akşam",
    statusCompleted = "Tamamlandı",
    statusSkipped = "Kaçırıldı",
    statusUnfinished = "Yaklaşan",
    selectDateRange = "Tarih aralığı seç",
    allWithoutSubCategory = "Tüm görevlerin alt kategorisi yok",
    inCategory = "kategorisinde",
    completionDropObservationFormat = "Kategori tamamlanma oranı önceki döneme göre %s azaldı",
    busiestDayObservationFormat = "%s, kategori süresinin %s kadarını oluşturur ve en yoğun gündür",
    dominantSubCategoryObservationFormat = "%s, kategori süresinin %s kadarını oluşturur",
)

internal val vietnameseAnalyticsString = englishAnalyticsString.copy(
    topAppBarTitle = "Phân tích",
    otherError = "Đã xảy ra lỗi. Hãy liên hệ với nhà phát triển.",
    lastSevenDays = "7 ngày qua",
    week = "Tuần",
    month = "Tháng",
    halfYear = "Nửa năm",
    year = "Năm",
    currentPeriod = "Kỳ hiện tại",
    previousPeriodDesc = "Kỳ trước",
    nextPeriodDesc = "Kỳ tiếp theo",
    previousMonthDesc = "Tháng trước",
    nextMonthDesc = "Tháng tiếp theo",
    selectRangeDesc = "Chọn khoảng tùy chỉnh",
    cancel = "Hủy",
    confirm = "Xong",
    summaryTitle = "Tóm tắt kỳ",
    summaryLastSevenDaysTitle = "Tóm tắt 7 ngày",
    summaryWeekTitle = "Tóm tắt tuần",
    summaryMonthTitle = "Tóm tắt tháng",
    summaryHalfYearTitle = "Tóm tắt nửa năm",
    summaryYearTitle = "Tóm tắt năm",
    categoriesTitle = "Thời gian theo danh mục",
    loadTitle = "Xu hướng khối lượng",
    creationTitle = "Thời điểm tạo nhiệm vụ",
    durationStructureTitle = "Cơ cấu thời lượng nhiệm vụ",
    planSourceTitle = "Liên kết mẫu",
    keyMetricsTitle = "Chỉ số chính",
    regularityTitle = "Mức độ đều đặn khi lập kế hoạch",
    busiestHoursTitle = "Giờ bận nhất",
    categorySummaryTitle = "Tóm tắt danh mục",
    subCategoriesTitle = "Thời gian theo danh mục con",
    categoryLoadTitle = "Xu hướng danh mục",
    dayPartsTitle = "Phân bổ theo thời điểm trong ngày",
    categoryTasksTitle = "Nhiệm vụ trong danh mục",
    observationTitle = "Nhận xét",
    planned = "Đã lên kế hoạch",
    completed = "Đã hoàn thành",
    skipped = "Đã bỏ lỡ",
    unfinished = "Sắp tới",
    completionShare = "Tỷ lệ hoàn thành",
    completedCountFormat = "%s trên %s",
    previousPeriod = "so với kỳ trước",
    comparisonPreviousZero = "Kỳ trước không có nhiệm vụ hoàn thành",
    comparisonUnavailable = "Chưa đủ nhiệm vụ để so sánh",
    comparisonUnchanged = "Không đổi",
    byTime = "Theo thời gian",
    byTasks = "Theo nhiệm vụ",
    showAll = "Hiển thị tất cả",
    collapse = "Thu gọn",
    other = "Khác",
    newCategory = "Mới",
    showAllCategories = "Hiển thị tất cả danh mục",
    showAllTasks = "Hiển thị tất cả nhiệm vụ",
    tasksFormat = "Nhiệm vụ: %s",
    loadTooltipFormat = "%s · %s · %s",
    categoryLoadTooltipFormat = "%s · %s: %s · toàn bộ kế hoạch: %s",
    median = "Trung vị",
    average = "Trung bình",
    createdInAdvance = "Trước từ 3 ngày",
    createdOneOrTwoDays = "Trước 1–2 ngày",
    createdSameDay = "Trong ngày đã lên lịch",
    createdAfterStart = "Sau khi bắt đầu",
    onlyUnlinkedTasks = "Chỉ nhiệm vụ không liên kết mẫu",
    included = "được tính",
    medianPlanningAhead = "Trung vị thời gian lên kế hoạch trước",
    beforeStartFormat = "%s trước khi bắt đầu",
    afterStartFormat = "%s sau khi bắt đầu",
    atStart = "tại thời điểm bắt đầu",
    shortTasks = "Tối đa 30 phút",
    mediumTasks = "Trên 30 phút đến 2 giờ",
    longTasks = "Trên 2 giờ",
    withTemplate = "Đã liên kết mẫu",
    withoutTemplate = "Không liên kết mẫu",
    important = "Ưu tiên cao",
    weekends = "Vào cuối tuần",
    longestBlock = "Khối dài nhất",
    busiestDay = "Ngày bận nhất",
    activeDaysFormat = "%s trên %s %s",
    dayUnit = "ngày|ngày|ngày",
    periodDaysFormat = "trong %s %s của kỳ",
    activeDayIncreaseFormat = "nhiều hơn %d %s",
    activeDayDecreaseFormat = "ít hơn %d %s",
    activeDayUnchanged = "Không thay đổi",
    less = "Ít hơn",
    more = "Nhiều hơn",
    heatmapRowDescFormat = "%s: khoảng bận nhất %02d:00–%02d:00, trung bình %d phút mỗi giờ",
    heatmapCellFormat = "%s, %02d:00–%02d:00 · %d phút",
    heatmapDetailsAction = "Hiển thị các giờ trong ngày này",
    dayPartRowDescFormat = "%s: bận nhất vào %s, trung bình %d phút",
    averageLoadExplanation = "Khối lượng trung bình bao gồm cả ngày không có nhiệm vụ",
    averageLoadInfoDesc = "Thông tin về cách tính khối lượng trung bình",
    averagePlannedMinutes = "Khối lượng đã lên kế hoạch trung bình, phút mỗi giờ",
    unavailableValue = "—",
    hourShort = "giờ",
    minuteShort = "phút",
    noData = "Không có dữ liệu cho kỳ đã chọn",
    noDataSupporting = "Thêm nhiệm vụ hoặc chọn khoảng khác",
    categoryNoData = "Không có nhiệm vụ thuộc danh mục này trong kỳ đã chọn",
    categoryNoDataSupporting = "Chọn khoảng khác",
    sectionNoData = "Không đủ dữ liệu cho phần này",
    creationNoData = "Không có dữ liệu thời điểm tạo cho nhiệm vụ không dùng mẫu",
    error = "Không thể tải dữ liệu",
    categoryError = "Không thể tải phân tích danh mục",
    retry = "Thử lại",
    loading = "Đang tải phân tích",
    openCategoryFormat = "Mở phân tích cho %s",
    navigateBackDesc = "Quay lại",
    categoryUnavailable = "Danh mục không khả dụng",
    categoryUnavailableSupporting = "Danh mục có thể đã bị xóa",
    withoutSubCategory = "Không có danh mục con",
    categoryShare = "Tỷ lệ trong toàn bộ kế hoạch",
    allPlan = "Toàn bộ kế hoạch",
    taskCount = "Số nhiệm vụ",
    timeLabel = "Thời gian",
    tasksLabel = "Nhiệm vụ",
    tasksMetric = "Nhiệm vụ",
    averageDuration = "Thời lượng trung bình",
    medianDuration = "Thời lượng trung vị",
    taskCountIncreaseFormat = "+%d",
    taskCountDecreaseFormat = "−%d",
    metricDurationIncreaseFormat = "nhiều hơn %s",
    metricDurationDecreaseFormat = "ít hơn %s",
    completedCountIncreaseFormat = "+%d",
    completedCountDecreaseFormat = "−%d",
    completionIncreaseFormat = "cao hơn %s so với kỳ trước",
    completionDecreaseFormat = "thấp hơn %s so với kỳ trước",
    completionPreviousZero = "Kỳ trước không có nhiệm vụ hoàn thành",
    categoryShareFormat = "%s tổng thời gian đã lên kế hoạch",
    categoryPreviousUnused = "Danh mục không được dùng trong kỳ trước",
    categoryTimeIncreaseFormat = "nhiều hơn kỳ trước %s thời gian",
    categoryTimeDecreaseFormat = "ít hơn kỳ trước %s thời gian",
    busiestDayValueFormat = "%s · %s",
    dayPartNight = "Đêm",
    dayPartMorning = "Buổi sáng",
    dayPartDay = "Ban ngày",
    dayPartEvening = "Buổi tối",
    statusCompleted = "Đã hoàn thành",
    statusSkipped = "Đã bỏ lỡ",
    statusUnfinished = "Sắp tới",
    selectDateRange = "Chọn khoảng ngày",
    allWithoutSubCategory = "Tất cả nhiệm vụ không có danh mục con",
    inCategory = "trong danh mục",
    completionDropObservationFormat = "Tỷ lệ hoàn thành của danh mục giảm %s so với kỳ trước",
    busiestDayObservationFormat = "%s chiếm %s thời gian danh mục và là ngày bận nhất",
    dominantSubCategoryObservationFormat = "%s chiếm %s thời gian danh mục",
)

internal val polishAnalyticsString = englishAnalyticsString.copy(
    topAppBarTitle = "Analizy",
    otherError = "Coś poszło nie tak. Skontaktuj się z twórcą aplikacji.",
    lastSevenDays = "Ostatnie 7 dni",
    week = "Tydzień",
    month = "Miesiąc",
    halfYear = "Półrocze",
    year = "Rok",
    currentPeriod = "Bieżący okres",
    previousPeriodDesc = "Poprzedni okres",
    nextPeriodDesc = "Następny okres",
    previousMonthDesc = "Poprzedni miesiąc",
    nextMonthDesc = "Następny miesiąc",
    selectRangeDesc = "Wybierz własny zakres",
    cancel = "Anuluj",
    confirm = "Gotowe",
    summaryTitle = "Podsumowanie okresu",
    summaryLastSevenDaysTitle = "Podsumowanie 7 dni",
    summaryWeekTitle = "Podsumowanie tygodnia",
    summaryMonthTitle = "Podsumowanie miesiąca",
    summaryHalfYearTitle = "Podsumowanie półrocza",
    summaryYearTitle = "Podsumowanie roku",
    categoriesTitle = "Czas według kategorii",
    loadTitle = "Trend obciążenia",
    creationTitle = "Kiedy tworzone są zadania",
    durationStructureTitle = "Struktura czasu trwania zadań",
    planSourceTitle = "Powiązanie z szablonami",
    keyMetricsTitle = "Kluczowe wskaźniki",
    regularityTitle = "Regularność planowania",
    busiestHoursTitle = "Najbardziej zajęte godziny",
    categorySummaryTitle = "Podsumowanie kategorii",
    subCategoriesTitle = "Czas według podkategorii",
    categoryLoadTitle = "Trend kategorii",
    dayPartsTitle = "Rozkład według pory dnia",
    categoryTasksTitle = "Zadania kategorii",
    observationTitle = "Obserwacja",
    planned = "Zaplanowano",
    completed = "Ukończono",
    skipped = "Pominięto",
    unfinished = "Nadchodzące",
    completionShare = "Udział ukończonych",
    completedCountFormat = "%s z %s",
    previousPeriod = "względem poprzedniego okresu",
    comparisonPreviousZero = "W poprzednim okresie nie było ukończonych zadań",
    comparisonUnavailable = "Za mało zadań, aby je porównać",
    comparisonUnchanged = "Bez zmian",
    byTime = "Według czasu",
    byTasks = "Według zadań",
    showAll = "Pokaż wszystko",
    collapse = "Zwiń",
    other = "Inne",
    newCategory = "Nowa",
    showAllCategories = "Pokaż wszystkie kategorie",
    showAllTasks = "Pokaż wszystkie zadania",
    tasksFormat = "Zadania: %s",
    loadTooltipFormat = "%s · %s · %s",
    categoryLoadTooltipFormat = "%s · %s: %s · cały plan: %s",
    median = "Mediana",
    average = "Średnia",
    createdInAdvance = "Co najmniej 3 dni wcześniej",
    createdOneOrTwoDays = "1–2 dni wcześniej",
    createdSameDay = "W zaplanowanym dniu",
    createdAfterStart = "Po rozpoczęciu",
    onlyUnlinkedTasks = "Tylko zadania niepowiązane z szablonem",
    included = "uwzględniono",
    medianPlanningAhead = "Mediana wyprzedzenia planowania",
    beforeStartFormat = "%s przed rozpoczęciem",
    afterStartFormat = "%s po rozpoczęciu",
    atStart = "w chwili rozpoczęcia",
    shortTasks = "Do 30 minut",
    mediumTasks = "Ponad 30 minut do 2 godzin",
    longTasks = "Ponad 2 godziny",
    withTemplate = "Powiązane z szablonem",
    withoutTemplate = "Niepowiązane z szablonem",
    important = "Wyższy priorytet",
    weekends = "W weekendy",
    longestBlock = "Najdłuższy blok",
    busiestDay = "Najbardziej zajęty dzień",
    activeDaysFormat = "%s z %s %s",
    dayUnit = "dzień|dni|dni",
    periodDaysFormat = "z %s %s okresu",
    activeDayIncreaseFormat = "o %d %s więcej",
    activeDayDecreaseFormat = "o %d %s mniej",
    activeDayUnchanged = "Bez zmian",
    less = "Mniej",
    more = "Więcej",
    heatmapRowDescFormat = "%s: najbardziej zajęty przedział %02d:00–%02d:00, średnio %d min na godzinę",
    heatmapCellFormat = "%s, %02d:00–%02d:00 · %d min",
    heatmapDetailsAction = "Pokaż godziny tego dnia",
    dayPartRowDescFormat = "%s: największe obciążenie w %s, średnio %d min",
    averageLoadExplanation = "Średnie obciążenie uwzględnia dni bez zadań",
    averageLoadInfoDesc = "O obliczaniu średniego obciążenia",
    averagePlannedMinutes = "Średnie planowane obciążenie, minuty na godzinę",
    unavailableValue = "—",
    hourShort = "godz.",
    minuteShort = "min",
    noData = "Brak danych dla wybranego okresu",
    noDataSupporting = "Dodaj zadania lub wybierz inny zakres",
    categoryNoData = "Brak zadań tej kategorii w wybranym okresie",
    categoryNoDataSupporting = "Wybierz inny zakres",
    sectionNoData = "Za mało danych dla tej sekcji",
    creationNoData = "Brak danych o utworzeniu zadań bez szablonu",
    error = "Nie udało się wczytać danych",
    categoryError = "Nie udało się wczytać analizy kategorii",
    retry = "Spróbuj ponownie",
    loading = "Wczytywanie analizy",
    openCategoryFormat = "Otwórz analizę kategorii %s",
    navigateBackDesc = "Wstecz",
    categoryUnavailable = "Kategoria niedostępna",
    categoryUnavailableSupporting = "Mogła zostać usunięta",
    withoutSubCategory = "Bez podkategorii",
    categoryShare = "Udział w całym planie",
    allPlan = "Cały plan",
    taskCount = "Liczba zadań",
    timeLabel = "Czas",
    tasksLabel = "Zadania",
    tasksMetric = "Zadania",
    averageDuration = "Średni czas trwania",
    medianDuration = "Mediana czasu trwania",
    taskCountIncreaseFormat = "+%d",
    taskCountDecreaseFormat = "−%d",
    metricDurationIncreaseFormat = "o %s więcej",
    metricDurationDecreaseFormat = "o %s mniej",
    completedCountIncreaseFormat = "+%d",
    completedCountDecreaseFormat = "−%d",
    completionIncreaseFormat = "o %s wyżej niż w poprzednim okresie",
    completionDecreaseFormat = "o %s niżej niż w poprzednim okresie",
    completionPreviousZero = "W poprzednim okresie nie było ukończonych zadań",
    categoryShareFormat = "%s całego zaplanowanego czasu",
    categoryPreviousUnused = "Kategoria nie była używana w poprzednim okresie",
    categoryTimeIncreaseFormat = "o %s więcej czasu niż w poprzednim okresie",
    categoryTimeDecreaseFormat = "o %s mniej czasu niż w poprzednim okresie",
    busiestDayValueFormat = "%s · %s",
    dayPartNight = "Noc",
    dayPartMorning = "Rano",
    dayPartDay = "Dzień",
    dayPartEvening = "Wieczór",
    statusCompleted = "Ukończone",
    statusSkipped = "Pominięte",
    statusUnfinished = "Nadchodzące",
    selectDateRange = "Wybierz zakres dat",
    allWithoutSubCategory = "Wszystkie zadania są bez podkategorii",
    inCategory = "w kategorii",
    completionDropObservationFormat = "Udział ukończonych zadań kategorii spadł o %s względem poprzedniego okresu",
    busiestDayObservationFormat = "%s odpowiada za %s czasu kategorii i jest najbardziej zajętym dniem",
    dominantSubCategoryObservationFormat = "%s odpowiada za %s czasu kategorii",
)

internal val italianAnalyticsString = englishAnalyticsString.copy(
    topAppBarTitle = "Statistiche",
    otherError = "Qualcosa è andato storto. Contatta lo sviluppatore.",
    lastSevenDays = "Ultimi 7 giorni",
    week = "Settimana",
    month = "Mese",
    halfYear = "Semestre",
    year = "Anno",
    currentPeriod = "Periodo corrente",
    previousPeriodDesc = "Periodo precedente",
    nextPeriodDesc = "Periodo successivo",
    previousMonthDesc = "Mese precedente",
    nextMonthDesc = "Mese successivo",
    selectRangeDesc = "Seleziona intervallo personalizzato",
    cancel = "Annulla",
    confirm = "Fine",
    summaryTitle = "Riepilogo del periodo",
    summaryLastSevenDaysTitle = "Riepilogo di 7 giorni",
    summaryWeekTitle = "Riepilogo settimanale",
    summaryMonthTitle = "Riepilogo mensile",
    summaryHalfYearTitle = "Riepilogo semestrale",
    summaryYearTitle = "Riepilogo annuale",
    categoriesTitle = "Tempo per categoria",
    loadTitle = "Andamento del carico",
    creationTitle = "Quando vengono create le attività",
    durationStructureTitle = "Struttura della durata delle attività",
    planSourceTitle = "Collegamento ai modelli",
    keyMetricsTitle = "Metriche principali",
    regularityTitle = "Regolarità della pianificazione",
    busiestHoursTitle = "Ore più impegnative",
    categorySummaryTitle = "Riepilogo categoria",
    subCategoriesTitle = "Tempo per sottocategoria",
    categoryLoadTitle = "Andamento della categoria",
    dayPartsTitle = "Distribuzione per fascia oraria",
    categoryTasksTitle = "Attività della categoria",
    observationTitle = "Osservazione",
    planned = "Pianificato",
    completed = "Completato",
    skipped = "Saltato",
    unfinished = "In arrivo",
    completionShare = "Percentuale completata",
    completedCountFormat = "%s su %s",
    previousPeriod = "rispetto al periodo precedente",
    comparisonPreviousZero = "Nel periodo precedente non c’erano attività completate",
    comparisonUnavailable = "Non ci sono ancora abbastanza attività da confrontare",
    comparisonUnchanged = "Nessuna variazione",
    byTime = "Per tempo",
    byTasks = "Per attività",
    showAll = "Mostra tutto",
    collapse = "Comprimi",
    other = "Altro",
    newCategory = "Nuova",
    showAllCategories = "Mostra tutte le categorie",
    showAllTasks = "Mostra tutte le attività",
    tasksFormat = "Attività: %s",
    loadTooltipFormat = "%s · %s · %s",
    categoryLoadTooltipFormat = "%s · %s: %s · piano completo: %s",
    median = "Mediana",
    average = "Media",
    createdInAdvance = "Con almeno 3 giorni di anticipo",
    createdOneOrTwoDays = "Con 1–2 giorni di anticipo",
    createdSameDay = "Nel giorno pianificato",
    createdAfterStart = "Dopo l’inizio",
    onlyUnlinkedTasks = "Solo attività non collegate a un modello",
    included = "incluse",
    medianPlanningAhead = "Anticipo mediano della pianificazione",
    beforeStartFormat = "%s prima dell’inizio",
    afterStartFormat = "%s dopo l’inizio",
    atStart = "all’ora di inizio",
    shortTasks = "Fino a 30 minuti",
    mediumTasks = "Oltre 30 minuti fino a 2 ore",
    longTasks = "Oltre 2 ore",
    withTemplate = "Collegate a un modello",
    withoutTemplate = "Non collegate a modelli",
    important = "Priorità elevata",
    weekends = "Nei fine settimana",
    longestBlock = "Blocco più lungo",
    busiestDay = "Giorno più impegnativo",
    activeDaysFormat = "%s su %s %s",
    dayUnit = "giorno|giorni|giorni",
    periodDaysFormat = "su %s %s del periodo",
    activeDayIncreaseFormat = "%d %s in più",
    activeDayDecreaseFormat = "%d %s in meno",
    activeDayUnchanged = "Nessuna variazione",
    less = "Meno",
    more = "Più",
    heatmapRowDescFormat = "%s: intervallo più impegnativo %02d:00–%02d:00, media %d min all'ora",
    heatmapCellFormat = "%s, %02d:00–%02d:00 · %d min",
    heatmapDetailsAction = "Mostra le ore di questo giorno",
    dayPartRowDescFormat = "%s: carico massimo il %s, media %d min",
    averageLoadExplanation = "Il carico medio include i giorni senza attività",
    averageLoadInfoDesc = "Informazioni sul calcolo del carico medio",
    averagePlannedMinutes = "Carico medio pianificato, minuti per ora",
    unavailableValue = "—",
    hourShort = "h",
    minuteShort = "min",
    noData = "Nessun dato per il periodo selezionato",
    noDataSupporting = "Aggiungi attività o seleziona un altro intervallo",
    categoryNoData = "Nessuna attività di questa categoria nel periodo selezionato",
    categoryNoDataSupporting = "Seleziona un altro intervallo",
    sectionNoData = "Dati insufficienti per questa sezione",
    creationNoData = "Nessun dato di creazione per le attività senza modello",
    error = "Impossibile caricare i dati",
    categoryError = "Impossibile caricare l’analisi della categoria",
    retry = "Riprova",
    loading = "Caricamento analisi",
    openCategoryFormat = "Apri l’analisi di %s",
    navigateBackDesc = "Indietro",
    categoryUnavailable = "Categoria non disponibile",
    categoryUnavailableSupporting = "Potrebbe essere stata eliminata",
    withoutSubCategory = "Senza sottocategoria",
    categoryShare = "Quota del piano completo",
    allPlan = "Piano completo",
    taskCount = "Numero di attività",
    timeLabel = "Tempo",
    tasksLabel = "Attività",
    tasksMetric = "Attività",
    averageDuration = "Durata media",
    medianDuration = "Durata mediana",
    taskCountIncreaseFormat = "+%d",
    taskCountDecreaseFormat = "−%d",
    metricDurationIncreaseFormat = "%s in più",
    metricDurationDecreaseFormat = "%s in meno",
    completedCountIncreaseFormat = "+%d",
    completedCountDecreaseFormat = "−%d",
    completionIncreaseFormat = "%s più alta rispetto al periodo precedente",
    completionDecreaseFormat = "%s più bassa rispetto al periodo precedente",
    completionPreviousZero = "Nel periodo precedente non c’erano attività completate",
    categoryShareFormat = "%s di tutto il tempo pianificato",
    categoryPreviousUnused = "La categoria non è stata usata nel periodo precedente",
    categoryTimeIncreaseFormat = "%s di tempo in più rispetto al periodo precedente",
    categoryTimeDecreaseFormat = "%s di tempo in meno rispetto al periodo precedente",
    busiestDayValueFormat = "%s · %s",
    dayPartNight = "Notte",
    dayPartMorning = "Mattina",
    dayPartDay = "Giorno",
    dayPartEvening = "Sera",
    statusCompleted = "Completata",
    statusSkipped = "Saltata",
    statusUnfinished = "In arrivo",
    selectDateRange = "Seleziona intervallo di date",
    allWithoutSubCategory = "Tutte le attività sono senza sottocategoria",
    inCategory = "nella categoria",
    completionDropObservationFormat = "La percentuale completata della categoria è diminuita del %s rispetto al periodo precedente",
    busiestDayObservationFormat = "%s rappresenta il %s del tempo della categoria ed è il giorno più impegnativo",
    dominantSubCategoryObservationFormat = "%s rappresenta il %s del tempo della categoria",
)

internal val chineseAnalyticsString = englishAnalyticsString.copy(
    topAppBarTitle = "统计",
    otherError = "出现问题。请联系开发者。",
    lastSevenDays = "最近 7 天",
    week = "周",
    month = "月",
    halfYear = "半年",
    year = "年",
    currentPeriod = "当前周期",
    previousPeriodDesc = "上一周期",
    nextPeriodDesc = "下一周期",
    previousMonthDesc = "上个月",
    nextMonthDesc = "下个月",
    selectRangeDesc = "选择自定义范围",
    cancel = "取消",
    confirm = "完成",
    summaryTitle = "周期摘要",
    summaryLastSevenDaysTitle = "7 天摘要",
    summaryWeekTitle = "本周摘要",
    summaryMonthTitle = "本月摘要",
    summaryHalfYearTitle = "半年摘要",
    summaryYearTitle = "年度摘要",
    categoriesTitle = "各类别时间",
    loadTitle = "负荷趋势",
    creationTitle = "任务创建时间",
    durationStructureTitle = "任务时长结构",
    planSourceTitle = "模板关联",
    keyMetricsTitle = "关键指标",
    regularityTitle = "计划规律性",
    busiestHoursTitle = "最繁忙时段",
    categorySummaryTitle = "类别摘要",
    subCategoriesTitle = "各子类别时间",
    categoryLoadTitle = "类别趋势",
    dayPartsTitle = "时段分布",
    categoryTasksTitle = "类别任务",
    observationTitle = "观察",
    planned = "已计划",
    completed = "已完成",
    skipped = "已错过",
    unfinished = "待完成",
    completionShare = "完成比例",
    completedCountFormat = "%s / %s",
    previousPeriod = "与上一周期相比",
    comparisonPreviousZero = "上一周期没有已完成任务",
    comparisonUnavailable = "任务数量暂不足以比较",
    comparisonUnchanged = "无变化",
    byTime = "按时间",
    byTasks = "按任务",
    showAll = "显示全部",
    collapse = "收起",
    other = "其他",
    newCategory = "新增",
    showAllCategories = "显示所有类别",
    showAllTasks = "显示所有任务",
    tasksFormat = "任务：%s",
    loadTooltipFormat = "%s · %s · %s",
    categoryLoadTooltipFormat = "%s · %s：%s · 整体计划：%s",
    median = "中位数",
    average = "平均值",
    createdInAdvance = "提前 3 天以上",
    createdOneOrTwoDays = "提前 1–2 天",
    createdSameDay = "计划当天",
    createdAfterStart = "开始后",
    onlyUnlinkedTasks = "仅未关联模板的任务",
    included = "已计入",
    medianPlanningAhead = "计划提前时间中位数",
    beforeStartFormat = "开始前 %s",
    afterStartFormat = "开始后 %s",
    atStart = "开始时",
    shortTasks = "不超过 30 分钟",
    mediumTasks = "超过 30 分钟至 2 小时",
    longTasks = "超过 2 小时",
    withTemplate = "已关联模板",
    withoutTemplate = "未关联模板",
    important = "较高优先级",
    weekends = "周末",
    longestBlock = "最长连续时段",
    busiestDay = "最繁忙的一天",
    activeDaysFormat = "%s / %s %s",
    dayUnit = "天|天|天",
    periodDaysFormat = "周期共 %s %s",
    activeDayIncreaseFormat = "增加 %d %s",
    activeDayDecreaseFormat = "减少 %d %s",
    activeDayUnchanged = "无变化",
    less = "较少",
    more = "较多",
    heatmapRowDescFormat = "%s：最繁忙时段 %02d:00–%02d:00，平均每小时 %d 分钟",
    heatmapCellFormat = "%s，%02d:00–%02d:00 · %d 分钟",
    heatmapDetailsAction = "显示当天各小时",
    dayPartRowDescFormat = "%s：%s负荷最高，平均 %d 分钟",
    averageLoadExplanation = "平均负荷包括没有任务的日期",
    averageLoadInfoDesc = "关于平均负荷的计算",
    averagePlannedMinutes = "平均计划负荷，每小时分钟数",
    unavailableValue = "—",
    hourShort = "小时",
    minuteShort = "分钟",
    noData = "所选周期没有数据",
    noDataSupporting = "添加任务或选择其他范围",
    categoryNoData = "所选周期内该类别没有任务",
    categoryNoDataSupporting = "请选择其他范围",
    sectionNoData = "此部分数据不足",
    creationNoData = "没有未关联模板任务的创建时间数据",
    error = "无法加载数据",
    categoryError = "无法加载类别分析",
    retry = "重试",
    loading = "正在加载分析",
    openCategoryFormat = "打开 %s 的分析",
    navigateBackDesc = "返回",
    categoryUnavailable = "类别不可用",
    categoryUnavailableSupporting = "它可能已被删除",
    withoutSubCategory = "无子类别",
    categoryShare = "占整体计划比例",
    allPlan = "整体计划",
    taskCount = "任务数量",
    timeLabel = "时间",
    tasksLabel = "任务",
    tasksMetric = "任务",
    averageDuration = "平均时长",
    medianDuration = "时长中位数",
    taskCountIncreaseFormat = "+%d",
    taskCountDecreaseFormat = "−%d",
    metricDurationIncreaseFormat = "增加 %s",
    metricDurationDecreaseFormat = "减少 %s",
    completedCountIncreaseFormat = "+%d",
    completedCountDecreaseFormat = "−%d",
    completionIncreaseFormat = "比上一周期提高 %s",
    completionDecreaseFormat = "比上一周期降低 %s",
    completionPreviousZero = "上一周期没有已完成任务",
    categoryShareFormat = "占全部计划时间的 %s",
    categoryPreviousUnused = "上一周期未使用此类别",
    categoryTimeIncreaseFormat = "比上一周期增加 %s 时间",
    categoryTimeDecreaseFormat = "比上一周期减少 %s 时间",
    busiestDayValueFormat = "%s · %s",
    dayPartNight = "夜间",
    dayPartMorning = "上午",
    dayPartDay = "白天",
    dayPartEvening = "晚上",
    statusCompleted = "已完成",
    statusSkipped = "已错过",
    statusUnfinished = "待完成",
    selectDateRange = "选择日期范围",
    allWithoutSubCategory = "所有任务均无子类别",
    inCategory = "在类别中",
    completionDropObservationFormat = "类别完成比例较上一周期下降了 %s",
    busiestDayObservationFormat = "%s 占类别时间的 %s，是最繁忙的一天",
    dominantSubCategoryObservationFormat = "%s 占类别时间的 %s",
)

internal val LocalAnalyticsStrings = staticCompositionLocalOf<AnalyticsStrings> {
    error("Analytics strings are not provided")
}

internal fun fetchAnalyticsStrings(language: TimePlannerLanguage) = when (language) {
    TimePlannerLanguage.RU -> russianAnalyticsString
    TimePlannerLanguage.EN -> englishAnalyticsString
    TimePlannerLanguage.DE -> germanAnalyticsString
    TimePlannerLanguage.ES -> spanishAnalyticsString
    TimePlannerLanguage.FA -> persianAnalyticsString
    TimePlannerLanguage.FR -> frenchAnalyticsString
    TimePlannerLanguage.PT_BR -> brazilianPortugueseAnalyticsString
    TimePlannerLanguage.TR -> turkishAnalyticsString
    TimePlannerLanguage.VN -> vietnameseAnalyticsString
    TimePlannerLanguage.PL -> polishAnalyticsString
    TimePlannerLanguage.IT -> italianAnalyticsString
    TimePlannerLanguage.ZH -> chineseAnalyticsString
}
