/*
 * Copyright 2023 Stanislav Aleshin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ru.aleshin.features.settings.impl.presentation.theme.tokens

import androidx.compose.runtime.staticCompositionLocalOf
import ru.aleshin.core.ui.theme.tokens.TimePlannerLanguage

/**
 * @author Stanislav Aleshin on 17.02.2023.
 */
internal data class SettingsStrings(
    val settingsTitle: String,
    val mainSettingsTitle: String,
    val mainSettingsThemeTitle: String,
    val darkThemeTitle: String,
    val lightThemeTitle: String,
    val systemThemeTitle: String,
    val mainSettingsLanguageTitle: String,
    val rusLanguageTitle: String,
    val engLanguageTitle: String,
    val gerLanguageTitle: String,
    val spaLanguageTitle: String,
    val perLanguageTitle: String,
    val freLanguageTitle: String,
    val braporLanguageTitle: String,
    val turLanguageTitle: String,
    val vieLanguageTitle: String,
    val polLanguageTitle: String,
    val italianLanguageTitle: String,
    val chiLanguageTitle: String,
    val defaultLanguageTitle: String,
    val backIconDesc: String,
    val moreIconDesc: String,
    val resetToDefaultTitle: String,
    val menuIconDesc: String,
    val dataSectionHeader: String,
    val clearDataTitle: String,
    val clearDataButtonTitle: String,
    val clearDataWarning: String,
    val backupDataTitle: String,
    val backupDataButtonTitle: String,
    val restoreDataButtonTitle: String,
    val errorBackupMessage: String,
    val errorBackupFileMessage: String,
    val otherError: String,
    val mainSettingsDynamicColorTitle: String,
    val aboutAppHeader: String,
    val versionCodeTitle: String,
    val versionNameTitle: String,
    val developerTitle: String,
    val licenseTitle: String,
    val githubTitle: String,
    val askQuestionTitle: String,
    val donateTitle: String,
    val copyTitle: String,
    val mainSettingsColorsTitle: String,
    val donateHeader: String,
    val secureSectionHeader: String,
    val secureModeTitle: String,
    val interfaceSectionHeader: String,
    val calendarButtonBehaviorTitle: String,
    val currentDayCalendarBehavior: String,
    val selectDayCalendarBehavior: String,
)

internal val russianSettingsString = SettingsStrings(
    settingsTitle = "Настройки",
    mainSettingsTitle = "Основные настройки",
    mainSettingsThemeTitle = "Тема:",
    darkThemeTitle = "Тёмная",
    lightThemeTitle = "Светлая",
    systemThemeTitle = "Системная",
    mainSettingsLanguageTitle = "Язык приложения",
    rusLanguageTitle = "Русский",
    engLanguageTitle = "Английский",
    gerLanguageTitle = "Немецкий",
    spaLanguageTitle = "Испанский",
    perLanguageTitle = "Персидский(b)",
    freLanguageTitle = "Французкий",
    braporLanguageTitle = "Португальский",
    turLanguageTitle = "Турецкий",
    vieLanguageTitle = "Вьетнамский",
    polLanguageTitle = "Польский",
    italianLanguageTitle = "Итальянский",
    chiLanguageTitle = "Китайский",
    defaultLanguageTitle = "По умолчанию",
    backIconDesc = "Назад",
    moreIconDesc = "Дополнительно",
    resetToDefaultTitle = "По умолчанию",
    menuIconDesc = "Меню",
    dataSectionHeader = "Данные",
    clearDataTitle = "Удалить все данные",
    clearDataButtonTitle = "Очистить",
    clearDataWarning = "Данное действие приведёт к полной очистке данных приложения!",
    backupDataTitle = "Резервная копия",
    backupDataButtonTitle = "Сохранить",
    restoreDataButtonTitle = "Восстановить",
    errorBackupMessage = "Ошибка резервного копирования",
    errorBackupFileMessage = "Ошибка при работе с файлом",
    otherError = "Ошибка! Обратитесь к разработчику.",
    mainSettingsDynamicColorTitle = "Динамические цвета",
    aboutAppHeader = "О приложении",
    versionCodeTitle = "Номер сборки",
    versionNameTitle = "Версия",
    developerTitle = "Разработчик",
    licenseTitle = "Лицензия",
    githubTitle = "Github",
    askQuestionTitle = "Задать вопрос",
    donateTitle = "Поддержать приложение",
    copyTitle = "Копировать",
    mainSettingsColorsTitle = "Цвет",
    donateHeader = "Донат",
    secureSectionHeader = "Безопасность",
    secureModeTitle = "Безопасный режим",
    interfaceSectionHeader = "Интерфейс",
    calendarButtonBehaviorTitle = "Поведение кнопки календаря",
    currentDayCalendarBehavior = "Текущий день",
    selectDayCalendarBehavior = "Выбор дня",
)

internal val englishSettingsString = SettingsStrings(
    settingsTitle = "Settings",
    mainSettingsTitle = "Appearance",
    mainSettingsThemeTitle = "Theme",
    darkThemeTitle = "Dark",
    lightThemeTitle = "Light",
    systemThemeTitle = "System",
    mainSettingsLanguageTitle = "App language",
    rusLanguageTitle = "Russian",
    engLanguageTitle = "English",
    gerLanguageTitle = "German",
    spaLanguageTitle = "Spanish",
    perLanguageTitle = "Persian(b)",
    freLanguageTitle = "French",
    braporLanguageTitle = "Portuguese",
    turLanguageTitle = "Turkish",
    vieLanguageTitle = "Vietnamese",
    polLanguageTitle = "Polish",
    italianLanguageTitle = "Italian",
    chiLanguageTitle = "Chinese",
    defaultLanguageTitle = "Default",
    backIconDesc = "Navigate up",
    moreIconDesc = "More",
    resetToDefaultTitle = "Reset to default",
    menuIconDesc = "Menu",
    dataSectionHeader = "Database",
    clearDataTitle = "Erase all data",
    clearDataButtonTitle = "Clear",
    clearDataWarning = "This action will result in a complete clearing of the application data",
    backupDataTitle = "Backup",
    backupDataButtonTitle = "Save",
    restoreDataButtonTitle = "Restore",
    errorBackupMessage = "Backup Error",
    errorBackupFileMessage = "There was an error working with the file",
    otherError = "Something went wrong. Contact the developer for help.",
    mainSettingsDynamicColorTitle = "Dynamic colors",
    aboutAppHeader = "About the app",
    versionCodeTitle = "Build number",
    versionNameTitle = "Version",
    developerTitle = "Developer",
    licenseTitle = "License",
    githubTitle = "Github",
    askQuestionTitle = "Ask a question",
    donateTitle = "Support with a donation",
    copyTitle = "Copy",
    mainSettingsColorsTitle = "Color",
    donateHeader = "Donate",
    secureSectionHeader = "Security",
    secureModeTitle = "Secure screen",
    interfaceSectionHeader = "Interface",
    calendarButtonBehaviorTitle = "Calendar icon behavior",
    currentDayCalendarBehavior = "Set to today",
    selectDayCalendarBehavior = "Pick a date",
)

internal val germanSettingsString = SettingsStrings(
    settingsTitle = "Einstellungen",
    mainSettingsTitle = "Allgemeine Einstellungen",
    mainSettingsThemeTitle = "Thema:",
    darkThemeTitle = "Dunkel",
    lightThemeTitle = "Hell",
    systemThemeTitle = "System",
    mainSettingsLanguageTitle = "Sprache der Anwendung",
    rusLanguageTitle = "Russisch",
    engLanguageTitle = "Englisch",
    gerLanguageTitle = "Deutsch",
    spaLanguageTitle = "Spanisch",
    perLanguageTitle = "Persisch(b)",
    freLanguageTitle = "Französisch",
    braporLanguageTitle = "Portugiesisch",
    turLanguageTitle = "Türkisch",
    vieLanguageTitle = "Vietnamesisch",
    polLanguageTitle = "Polnisch",
    italianLanguageTitle = "Italienisch",
    chiLanguageTitle = "Chinesisch",
    defaultLanguageTitle = "Standard",
    backIconDesc = "Zurück",
    moreIconDesc = "Mehr",
    resetToDefaultTitle = "Auf Standard zurücksetzen",
    menuIconDesc = "Menü",
    dataSectionHeader = "Daten",
    clearDataTitle = "Alle Daten löschen",
    clearDataButtonTitle = "Löschen",
    clearDataWarning = "Diese Aktion führt zu einer vollständigen Bereinigung der Anwendungsdaten!",
    backupDataTitle = "Sicherung",
    backupDataButtonTitle = "Sichern",
    restoreDataButtonTitle = "Wiederherstellen",
    errorBackupMessage = "Sicherungsfehler",
    errorBackupFileMessage = "Fehler beim Arbeiten mit der Datei",
    otherError = "Fehler! Kontaktieren Sie den Entwickler.",
    mainSettingsDynamicColorTitle = "Dynamische Farben",
    aboutAppHeader = "Über die App",
    versionCodeTitle = "Build-Nummer",
    versionNameTitle = "Version",
    developerTitle = "Entwickler",
    licenseTitle = "Lizenz",
    githubTitle = "Github",
    askQuestionTitle = "Eine Frage stellen",
    donateTitle = "App unterstützen",
    copyTitle = "kopieren",
    mainSettingsColorsTitle = "Farbe",
    donateHeader = "Donat",
    secureSectionHeader = "Sicherheitseinstellungen",
    secureModeTitle = "Sicherer Bildschirm",
    interfaceSectionHeader = "Schnittstelle",
    calendarButtonBehaviorTitle = "Verhalten der Kalenderschaltfläche",
    currentDayCalendarBehavior = "Aktueller Tag",
    selectDayCalendarBehavior = "Wahl des Tages",
)

internal val spanishSettingsString = SettingsStrings(
    settingsTitle = "Ajustes",
    mainSettingsTitle = "Ajustes generales",
    mainSettingsThemeTitle = "Estilo:",
    darkThemeTitle = "Oscuro",
    lightThemeTitle = "Claro",
    systemThemeTitle = "Sistema",
    mainSettingsLanguageTitle = "Idioma ",
    rusLanguageTitle = "Ruso",
    engLanguageTitle = "Inglés",
    gerLanguageTitle = "Alemán",
    spaLanguageTitle = "Español",
    perLanguageTitle = "Persa(b)",
    freLanguageTitle = "Francés",
    braporLanguageTitle = "Portugués",
    turLanguageTitle = "Turco",
    vieLanguageTitle = "Vietnamita",
    polLanguageTitle = "Polaco",
    italianLanguageTitle = "Italiano",
    chiLanguageTitle = "Chino",
    defaultLanguageTitle = "Por defecto",
    backIconDesc = "Volver arriba",
    moreIconDesc = "Más",
    resetToDefaultTitle = "Restablecer valores",
    menuIconDesc = "Menú",
    dataSectionHeader = "Datos",
    clearDataTitle = "Borrar todos los datos",
    clearDataButtonTitle = "Borrar",
    clearDataWarning = "¡Esto supondrá la eliminación completa de todos los datos!",
    backupDataTitle = "Respaldo",
    backupDataButtonTitle = "Guardar",
    restoreDataButtonTitle = "Restaurar",
    errorBackupMessage = "Error de respaldo",
    errorBackupFileMessage = "Error al trabajar con el archivo",
    otherError = "¡Error! Contacta al desarrollador.",
    mainSettingsDynamicColorTitle = "Colores dinámicos",
    aboutAppHeader = "Acerca de la aplicación",
    versionCodeTitle = "Número de construcción",
    versionNameTitle = "Versión",
    developerTitle = "Elaborador",
    licenseTitle = "Licencia",
    githubTitle = "Github",
    askQuestionTitle = "Preguntar",
    donateTitle = "Apoyar la aplicación",
    copyTitle = "Copiar",
    mainSettingsColorsTitle = "Color",
    donateHeader = "Donat",
    secureSectionHeader = "Configuración de seguridad",
    secureModeTitle = "Pantalla segura",
    interfaceSectionHeader = "Interfaz",
    calendarButtonBehaviorTitle = "Comportamiento del botón de calendario",
    currentDayCalendarBehavior = "Día actual",
    selectDayCalendarBehavior = "Selección del día",
)

internal val persianSettingsString = SettingsStrings(
    settingsTitle = "تنظبمات",
    mainSettingsTitle = "تنظیمات عمومی",
    mainSettingsThemeTitle = "پوسته",
    darkThemeTitle = "تاریک",
    lightThemeTitle = "روشن",
    systemThemeTitle = "سیستم",
    mainSettingsLanguageTitle = "زبان برنامه",
    rusLanguageTitle = "روسی",
    engLanguageTitle = "انگلیسی",
    gerLanguageTitle = "آلمانی",
    spaLanguageTitle = "اسپانیایی",
    perLanguageTitle = "فارسی (بیتا)",
    freLanguageTitle = "فرانسوی",
    braporLanguageTitle = "پرتغالی",
    turLanguageTitle = "زبان ترکی",
    vieLanguageTitle = "ویتنامی",
    polLanguageTitle = "زبان لهستانی",
    italianLanguageTitle = "ایتالیایی",
    chiLanguageTitle = "چینی",
    defaultLanguageTitle = "پیش فرض",
    backIconDesc = "پیمایش به بالا",
    moreIconDesc = "بیشتر",
    resetToDefaultTitle = "تنظیم به حالت پیش فرض",
    menuIconDesc = "منو",
    dataSectionHeader = "داده",
    clearDataTitle = "پاک کردن تمام داده ها",
    clearDataButtonTitle = "پاک کردن",
    clearDataWarning = "این عمل منجر به پاکسازی کامل داده های برنامه می شود!",
    backupDataTitle = "پشتیبان گیری",
    backupDataButtonTitle = "ذخبره",
    restoreDataButtonTitle = "بازگردانی",
    errorBackupMessage = "خطای پشتیبان گیری",
    errorBackupFileMessage = "خطا هنگام کار با فایل",
    otherError = "خطا! با توسعه دهنده تماس بگیرید.",
    mainSettingsDynamicColorTitle = "رنگ های پویا",
    aboutAppHeader = "درباره اپلیکیشن",
    versionCodeTitle = "شماره ساخت",
    versionNameTitle = "نسخه",
    developerTitle = "توسعه دهنده",
    licenseTitle = "مجوز",
    githubTitle = "Github",
    askQuestionTitle = "سوال بپرسید",
    donateTitle = "از برنامه پشتیبانی کنید",
    copyTitle = "کپی",
    mainSettingsColorsTitle = "رنگ",
    donateHeader = "دونات",
    secureSectionHeader = "تنظیمات امنیتی",
    secureModeTitle = "صفحه نمایش امن",
    interfaceSectionHeader = "رابط کاربری",
    calendarButtonBehaviorTitle = "رفتار دکمه تقویم",
    currentDayCalendarBehavior = "روز جاری",
    selectDayCalendarBehavior = "انتخاب روز",
)

internal val frenchSettingsString = SettingsStrings(
    settingsTitle = "Paramètres",
    mainSettingsTitle = "Paramètres généraux",
    mainSettingsThemeTitle = "Theme:",
    darkThemeTitle = "Sombre",
    lightThemeTitle = "Clair",
    systemThemeTitle = "Système",
    mainSettingsLanguageTitle = "Langue de l'application",
    rusLanguageTitle = "Russe",
    engLanguageTitle = "Anglais",
    gerLanguageTitle = "Allemand",
    spaLanguageTitle = "Espagnol",
    perLanguageTitle = "Perse(b)",
    freLanguageTitle = "Français",
    braporLanguageTitle = "Portugais",
    turLanguageTitle = "Turque",
    vieLanguageTitle = "Vietnamienne",
    polLanguageTitle = "Polonais",
    italianLanguageTitle = "Italien",
    chiLanguageTitle = "Chinois",
    defaultLanguageTitle = "Défaut",
    backIconDesc = "Naviguer vers le haut",
    moreIconDesc = "Plus",
    resetToDefaultTitle = "Reinitialiser",
    menuIconDesc = "Menu",
    dataSectionHeader = "Données",
    clearDataTitle = "Supprimer toutes les données",
    clearDataButtonTitle = "Supprimer",
    clearDataWarning = "Cette action entrainera une suppression de toutes les données de l'application!",
    backupDataTitle = "Sauvegarde",
    backupDataButtonTitle = "Sauvegarder",
    restoreDataButtonTitle = "Restaurer",
    errorBackupMessage = "Erreur de sauvegarde",
    errorBackupFileMessage = "Erreur pendant la manipulation du fichier",
    otherError = "Erreur! Contactez le developpeur.",
    mainSettingsDynamicColorTitle = "Couleurs dynamiques",
    aboutAppHeader = "À propos de l'application",
    versionCodeTitle = "Numéro d'assemblage",
    versionNameTitle = "Version",
    developerTitle = "Développeur",
    licenseTitle = "Licence",
    githubTitle = "Github",
    askQuestionTitle = "Poser une question",
    donateTitle = "Soutenir l'application",
    copyTitle = "Copier",
    mainSettingsColorsTitle = "Couleur",
    donateHeader = "Donat",
    secureSectionHeader = "Paramètres de sécurité",
    secureModeTitle = "Écran sécurisé",
    interfaceSectionHeader = "Interface",
    calendarButtonBehaviorTitle = "Comportement du bouton calendrier",
    currentDayCalendarBehavior = "Jour en cours",
    selectDayCalendarBehavior = "Choix du jour",
)

internal val brazilianPortugueseSettingsString = SettingsStrings(
    settingsTitle = "Configurações",
    mainSettingsTitle = "Configurações gerais",
    mainSettingsThemeTitle = "Tema:",
    darkThemeTitle = "Escuro",
    lightThemeTitle = "Claro",
    systemThemeTitle = "Sistema",
    mainSettingsLanguageTitle = "Idioma do aplicativo",
    rusLanguageTitle = "Russo",
    engLanguageTitle = "Inglês",
    gerLanguageTitle = "Alemão",
    spaLanguageTitle = "Espanhol",
    perLanguageTitle = "Persa(b)",
    freLanguageTitle = "Francês",
    italianLanguageTitle = "Italiano",
    chiLanguageTitle = "Chinês",
    braporLanguageTitle = "Português",
    turLanguageTitle = "Turco",
    vieLanguageTitle = "Vietnamita",
    polLanguageTitle = "Polonês",
    defaultLanguageTitle = "Padrão",
    backIconDesc = "Navegar para cima",
    moreIconDesc = "Mais",
    resetToDefaultTitle = "Resetar para padrão",
    menuIconDesc = "Menu",
    dataSectionHeader = "Dado",
    clearDataTitle = "Apagar todos os dados",
    clearDataButtonTitle = "Limpar",
    clearDataWarning = "Esta ação irá limpar todos os dados da aplicação!",
    backupDataTitle = "Backup",
    backupDataButtonTitle = "Salvar",
    restoreDataButtonTitle = "Restaurar",
    errorBackupMessage = "Erro de backup",
    errorBackupFileMessage = "Erro durante o uso do arquivo",
    otherError = "Erro! Contate o desenvolvedor.",
    mainSettingsDynamicColorTitle = "Cores dinâmicas",
    aboutAppHeader = "Sobre o aplicativo",
    versionCodeTitle = "Número de construção",
    versionNameTitle = "Versão",
    developerTitle = "Desenvolvedor",
    licenseTitle = "Licença",
    githubTitle = "Github",
    askQuestionTitle = "Faça uma pergunta",
    donateTitle = "Suportar a aplicação",
    copyTitle = "Copiar",
    mainSettingsColorsTitle = "Cor",
    donateHeader = "Doar",
    secureSectionHeader = "Segurança",
    secureModeTitle = "Modo seguro",
    interfaceSectionHeader = "Interface",
    calendarButtonBehaviorTitle = "Comportamento do botão do calendário",
    currentDayCalendarBehavior = "Dia atual",
    selectDayCalendarBehavior = "Escolhendo o dia",
)

internal val turkishSettingsString = SettingsStrings(
    settingsTitle = "Ayarlar",
    mainSettingsTitle = "Genel ayarlar",
    mainSettingsThemeTitle = "Tema:",
    darkThemeTitle = "Koyu",
    lightThemeTitle = "Açık",
    systemThemeTitle = "Sistem",
    mainSettingsLanguageTitle = "Uygulama dili",
    rusLanguageTitle = "Rusça",
    engLanguageTitle = "İngilizce",
    gerLanguageTitle = "Almanca",
    spaLanguageTitle = "İspanyolca",
    perLanguageTitle = "Farsça",
    freLanguageTitle = "Fransızca",
    braporLanguageTitle = "Portekizce",
    turLanguageTitle = "Türkçe",
    vieLanguageTitle = "Vietnamca",
    polLanguageTitle = "Lehçe",
    italianLanguageTitle = "İtalyan",
    chiLanguageTitle = "Çince",
    defaultLanguageTitle = "Varsayılan",
    backIconDesc = "Geri git",
    moreIconDesc = "Daha Fazla",
    resetToDefaultTitle = "Varsayılana sıfırla",
    menuIconDesc = "Menü",
    dataSectionHeader = "Veri",
    clearDataTitle = "Tüm verileri sil",
    clearDataButtonTitle = "Temizle",
    clearDataWarning = "Bu işlem uygulama verilerinin tamamen silinmesine yol açacak!",
    backupDataTitle = "Yedek",
    backupDataButtonTitle = "Kaydet",
    restoreDataButtonTitle = "Geri yükle",
    errorBackupMessage = "Yedekleme Hatası",
    errorBackupFileMessage = "Dosya ile çalışırken hata oluştu",
    otherError = "Hata! Geliştirici ile iletişime geçin.",
    mainSettingsDynamicColorTitle = "Dinamik renkler",
    aboutAppHeader = "Uygulama Hakkında",
    versionCodeTitle = "Sürüm Numarası",
    versionNameTitle = "Versiyon",
    developerTitle = "Geliştirici",
    licenseTitle = "Lisans",
    githubTitle = "Github",
    askQuestionTitle = "Soru Sor",
    donateTitle = "Uygulamayı Destekle",
    copyTitle = "Kopyala",
    mainSettingsColorsTitle = "Renk",
    donateHeader = "Bağış Yap",
    secureSectionHeader = "Güvenlik",
    secureModeTitle = "Güvenli ekran",
    interfaceSectionHeader = "Arayüz",
    calendarButtonBehaviorTitle = "Takvim düğme davranışı",
    currentDayCalendarBehavior = "Mevcut gün",
    selectDayCalendarBehavior = "Gün seçimi",
)

internal val vietnameseSettingsString = SettingsStrings(
    settingsTitle = "Thiết đặt",
    mainSettingsTitle = "Thiết đặt chung",
    mainSettingsThemeTitle = "Chủ đề:",
    darkThemeTitle = "Tối",
    lightThemeTitle = "Sáng",
    systemThemeTitle = "Hệ thống",
    mainSettingsLanguageTitle = "Ngôn ngữ ứng dụng",
    rusLanguageTitle = "Tiếng Nga",
    engLanguageTitle = "Tiếng Anh",
    gerLanguageTitle = "Tiếng Đức",
    spaLanguageTitle = "Tiếng Tây Ban Nha",
    perLanguageTitle = "Tiếng Ba Tư(b)",
    freLanguageTitle = "Tiếng Pháp",
    braporLanguageTitle = "Tiếng Bồ Đào Nha",
    turLanguageTitle = "Tiếng Thổ Nhĩ Kỳ",
    vieLanguageTitle = "Tiếng Ngôn Ngữ Việt",
    polLanguageTitle = "Tiếng Ba Lan",
    italianLanguageTitle = "Tiếng ý",
    chiLanguageTitle = "Tiếng Trung",
    defaultLanguageTitle = "Mặc định",
    backIconDesc =	"Điều hướng lên",
    moreIconDesc = "Thêm",
    resetToDefaultTitle = "Đặt lại về mặc định",
    menuIconDesc = "Thực đơn",
    dataSectionHeader = "Dữ liệu",
    clearDataTitle = "Xóa tất cả dữ liệu",
    clearDataButtonTitle = "Sạch",
    clearDataWarning = "Hành động này sẽ dẫn đến việc xóa hoàn toàn dữ liệu ứng dụng!",
    backupDataTitle = "Hỗ trợ",
    backupDataButtonTitle = "Lưu",
    restoreDataButtonTitle = "Khôi phục",
    errorBackupMessage = "Lỗi sao lưu",
    errorBackupFileMessage = "Lỗi khi làm việc với tệp",
    otherError = "Lỗi! Hãy liên hệ với nhà phát triển.",
    mainSettingsDynamicColorTitle = "Màu sắc năng động",
    aboutAppHeader =	"Giới thiệu về ứng dụng",
    versionCodeTitle = "Số bản dựng",
    versionNameTitle = "Phiên bản",
    developerTitle = "Nhà phát triển",
    licenseTitle = "Giấy phép",
    githubTitle = "Github",
    askQuestionTitle = "Đặt một câu hỏi",
    donateTitle = "Hỗ trợ ứng dụng",
    copyTitle = "Sao chép",
    mainSettingsColorsTitle = "Màu sắc",
    donateHeader = "Quyên tặng",
    secureSectionHeader = "Bảo vệ",
    secureModeTitle = "Màn hình an toàn",
    interfaceSectionHeader = "Giao diện",
    calendarButtonBehaviorTitle = "Hành vi của nút Lịch",
    currentDayCalendarBehavior = "Ngày hiện tại",
    selectDayCalendarBehavior = "Chọn ngày",
)

internal val polishSettingsString = SettingsStrings(
    settingsTitle = "Ustawienia",
    mainSettingsTitle = "Wygląd",
    mainSettingsThemeTitle = "Motyw:",
    darkThemeTitle = "Ciemny",
    lightThemeTitle = "Jasny",
    systemThemeTitle = "Systemowy",
    rusLanguageTitle = "Rosyjski",
    engLanguageTitle = "Angielski",
    gerLanguageTitle = "Niemiecki",
    spaLanguageTitle = "Hiszpański",
    perLanguageTitle = "Perski",
    freLanguageTitle = "Francuski",
    braporLanguageTitle = "Portugalski",
    turLanguageTitle = "Turecki",
    vieLanguageTitle = "Wietnamski",
    polLanguageTitle = "Polski",
    italianLanguageTitle = "Włoski",
    chiLanguageTitle = "Chiński",
    defaultLanguageTitle = "Domyślny",
    mainSettingsLanguageTitle = "Język aplikacji",
    backIconDesc = "Wróć",
    moreIconDesc = "Więcej",
    resetToDefaultTitle = "Przywróć domyślne",
    menuIconDesc = "Menu",
    dataSectionHeader = "Baza danych",
    clearDataTitle = "Usuń wszystkie dane",
    clearDataButtonTitle = "Usuń",
    clearDataWarning = "Ta operacja spowoduje usunięcie wszystkich danych aplikacji",
    backupDataTitle = "Kopia zapasowa",
    backupDataButtonTitle = "Zapisz",
    restoreDataButtonTitle = "Przywróć",
    errorBackupMessage = "Błąd kopii zapasowej",
    errorBackupFileMessage = "Wystąpił błąd podczas pracy z plikiem",
    otherError = "Coś poszło nie tak. Skontaktuj się z twórcą aplikacji by otrzymać pomoc.",
    mainSettingsDynamicColorTitle = "Kolory dynamiczne",
    aboutAppHeader = "O aplikacji",
    versionCodeTitle = "Kod wersji",
    versionNameTitle = "Wersja",
    githubTitle = "GitHub",
    developerTitle = "Twórca",
    licenseTitle = "Licencja",
    askQuestionTitle = "Zadaj pytanie",
    donateTitle = "Wesprzyj darowizną",
    copyTitle = "Kopiuj",
    mainSettingsColorsTitle = "Kolor",
    donateHeader = "Wesprzyj",
    secureSectionHeader = "Bezpieczeństwo",
    secureModeTitle = "Zabezpiecz ekran",
    interfaceSectionHeader = "Interfejs",
    calendarButtonBehaviorTitle = "Zachowanie ikony kalendarza",
    currentDayCalendarBehavior = "Aktualny dzień",
    selectDayCalendarBehavior = "Wybór daty",
)

internal val italianSettingsString = SettingsStrings(
    settingsTitle = "Impostazioni",
    mainSettingsTitle = "Grafica",
    mainSettingsThemeTitle = "Tema",
    darkThemeTitle = "Scuro",
    lightThemeTitle = "Chiaro",
    systemThemeTitle = "Sistema",
    mainSettingsLanguageTitle = "Lingua",
    rusLanguageTitle = "Russo",
    engLanguageTitle = "Inglese",
    gerLanguageTitle = "Tedesco",
    spaLanguageTitle = "Spagnolo",
    perLanguageTitle = "Persiano(b)",
    freLanguageTitle = "Francese",
    braporLanguageTitle = "Portoghese",
    turLanguageTitle = "Turco",
    vieLanguageTitle = "Vietnamese",
    polLanguageTitle = "Polacco",
    italianLanguageTitle = "Italiano",
    chiLanguageTitle = "Cinese",
    defaultLanguageTitle = "Default",
    backIconDesc = "Torna indietro",
    moreIconDesc = "Altro",
    resetToDefaultTitle = "Reimposta le impostazioni originali",
    menuIconDesc = "Menu",
    dataSectionHeader = "Database",
    clearDataTitle = "Cancella tutti i dati",
    clearDataButtonTitle = "Cancella",
    clearDataWarning = "Questa azione provocherà l'eliminazione di tutti i dati",
    backupDataTitle = "Backup",
    backupDataButtonTitle = "Salva",
    restoreDataButtonTitle = "Ripristina",
    errorBackupMessage = "Errore di Backup",
    errorBackupFileMessage = "C'è stato un errore nella gestione del file",
    otherError = "Qualcosa è andato storto. Contatta lo sviluppatore per ricevere assistenza.",
    mainSettingsDynamicColorTitle = "Colori dinamici",
    aboutAppHeader = "Informazioni dell'App",
    versionCodeTitle = "Build number",
    versionNameTitle = "Versione",
    developerTitle = "Sviluppatore",
    licenseTitle = "Licenza",
    githubTitle = "Github",
    askQuestionTitle = "Fai una domanda",
    donateTitle = "Supporta con una donazione",
    copyTitle = "Copia",
    mainSettingsColorsTitle = "Colori",
    donateHeader = "Dona",
    secureSectionHeader = "Sicurezza",
    secureModeTitle = "Schermata sicura",
    interfaceSectionHeader = "Interfaccia",
    calendarButtonBehaviorTitle = "Cosa succede quando clicco sull'icona del calendario?",
    currentDayCalendarBehavior = "Vai al giorno corrente",
    selectDayCalendarBehavior = "Scegli una data",
)

internal val chineseSettingsString = SettingsStrings(
    settingsTitle = "设置",
    mainSettingsTitle = "外观",
    mainSettingsThemeTitle = "主题",
    darkThemeTitle = "深色",
    lightThemeTitle = "浅色",
    systemThemeTitle = "跟随系统",
    mainSettingsLanguageTitle = "应用语言",
    rusLanguageTitle = "俄语",
    engLanguageTitle = "英语",
    gerLanguageTitle = "德语",
    spaLanguageTitle = "西班牙语",
    perLanguageTitle = "波斯语",
    freLanguageTitle = "法语",
    braporLanguageTitle = "葡萄牙语",
    turLanguageTitle = "土耳其语",
    vieLanguageTitle = "越南语",
    polLanguageTitle = "波兰语",
    italianLanguageTitle = "意大利语",
    chiLanguageTitle = "中文",
    defaultLanguageTitle = "默认",
    backIconDesc = "返回",
    moreIconDesc = "更多",
    resetToDefaultTitle = "恢复默认",
    menuIconDesc = "菜单",
    dataSectionHeader = "数据库",
    clearDataTitle = "清除所有数据",
    clearDataButtonTitle = "清除",
    clearDataWarning = "此操作将彻底清除应用数据",
    backupDataTitle = "备份",
    backupDataButtonTitle = "保存",
    restoreDataButtonTitle = "恢复",
    errorBackupMessage = "备份错误",
    errorBackupFileMessage = "处理文件时出错",
    otherError = "出现问题。请联系开发者获取帮助。",
    mainSettingsDynamicColorTitle = "动态取色",
    aboutAppHeader = "关于应用",
    versionCodeTitle = "构建号",
    versionNameTitle = "版本",
    developerTitle = "开发者",
    licenseTitle = "许可证",
    githubTitle = "Github",
    askQuestionTitle = "提问",
    donateTitle = "支持捐助",
    copyTitle = "复制",
    mainSettingsColorsTitle = "颜色",
    donateHeader = "捐助",
    secureSectionHeader = "安全",
    secureModeTitle = "安全屏幕",
    interfaceSectionHeader = "界面",
    calendarButtonBehaviorTitle = "日历按钮行为",
    currentDayCalendarBehavior = "当前日期",
    selectDayCalendarBehavior = "选择日期",
)

internal val LocalSettingsStrings = staticCompositionLocalOf<SettingsStrings> {
    error("Settings Strings is not provided")
}

internal fun fetchSettingsStrings(language: TimePlannerLanguage) = when (language) {
    TimePlannerLanguage.EN -> englishSettingsString
    TimePlannerLanguage.RU -> russianSettingsString
    TimePlannerLanguage.DE -> germanSettingsString
    TimePlannerLanguage.ES -> spanishSettingsString
    TimePlannerLanguage.FA -> persianSettingsString
    TimePlannerLanguage.FR -> frenchSettingsString
    TimePlannerLanguage.PT_BR -> brazilianPortugueseSettingsString
    TimePlannerLanguage.TR -> turkishSettingsString
    TimePlannerLanguage.VN -> vietnameseSettingsString
    TimePlannerLanguage.PL -> polishSettingsString
    TimePlannerLanguage.IT -> italianSettingsString
    TimePlannerLanguage.ZH -> chineseSettingsString
}
