/*
 * Copyright 2023 Stanislav Aleshin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ru.aleshin.features.home.impl.presentation.theme.tokens

import androidx.compose.runtime.staticCompositionLocalOf
import ru.aleshin.core.ui.theme.tokens.TimePlannerLanguage

/**
 * @author Stanislav Aleshin on 18.02.2023.
 */
internal data class HomeStrings(
    val topAppBarHomeTitle: String,
    val topAppBarCategoriesTitle: String,
    val topAppBarOverviewTitle: String,
    val mainCategoryTitle: String,
    val topAppBarCalendarIconDesc: String,
    val topAppBarMenuIconDesc: String,
    val nextDateIconDesc: String,
    val previousDateIconDesc: String,
    val dateDialogPickerHeadline: String,
    val dateDialogPickerTitle: String,
    val timeTaskExpandedIconDesc: String,
    val timeTaskCheckIconDesc: String,
    val timeTaskMoreIconDesc: String,
    val timeTaskAddIconDesc: String,
    val timeTaskRemoveIconDesc: String,
    val timeTaskIncreaseTimeTitle: String,
    val timeTaskReduceTimeTitle: String,
    val startTimeTaskTitlePlaceHolder: String,
    val addTimeTaskIconsDesc: String,
    val addFreeTimeTaskTitle: String,
    val addTaskTitle: String,
    val navToBackTitle: String,
    val topAppBarMoreIconDesc: String,
    val topAppBarTemplatesTitle: String,
    val mainCategoryChooserTitle: String,
    val subCategoryChooserTitle: String,
    val subCategoryDialogMainCategoryFormat: String,
    val emptyScheduleTitle: String,
    val createScheduleTitle: String,
    val createScheduleDesc: String,
    val shiftError: String,
    val importanceError: String,
    val otherError: String,
    val addSubCategoryTitle: String,
    val categoryFieldLabel: String,
    val dialogCreateTitle: String,
    val emptyListTitle: String,
    val updateCategoryTitle: String,
    val deleteCategoryTitle: String,
    val subCategoryTitle: String,
    val warningDeleteCategoryText: String,
    val sortedTypeTitle: String,
    val sortedTypeDate: String,
    val sortedTypeCategories: String,
    val sortedTypeDuration: String,
    val notificationEnabledTitle: String,
    val notificationDisabledTitle: String,
    val statisticsActiveTitle: String,
    val statisticsDisabledTitle: String,
    val addTemplatesFabTitle: String,
    val templateEditorHeader: String,
    val mainCategoryLabel: String,
    val subCategoryLabel: String,
    val startTimeLabel: String,
    val endTimeLabel: String,
    val notificationLabel: String,
    val statisticsLabel: String,
    val importanceLabel: String,
    val subCategoryEmptyTitle: String,
    val addCategoryTitle: String,
    val nameCategoryTitle: String,
    val foundedPlannedTasksTitle: String,
    val monthTitle: String,
    val dayTitle: String,
    val weekNumberTitle: String,
    val weekDayTitle: String,
    val noteTitle: String,
    val restoreDefaultCategories: String,
    val schedulesHeader: String,
    val realizedScheduleTitle: String,
    val accomplishmentScheduleTitle: String,
    val plannedScheduleTitle: String,
    val undefinedTasksHeader: String,
    val executeUndefinedTasksTitle: String,
    val currentTaskHeader: String,
    val noneTitle: String,
    val progressTitle: String,
    val taskDateChooserHeader: String,
    val taskDateChooserFieldLabel: String,
    val specifyDeadlineTitle: String,
    val deadlineLabel: String,
    val showAllSchedulesTitle: String,
)

internal val russianHomeString = HomeStrings(
    topAppBarHomeTitle = "Расписание",
    topAppBarCategoriesTitle = "Категории",
    topAppBarOverviewTitle = "Обзор",
    mainCategoryTitle = "Основная",
    topAppBarCalendarIconDesc = "Выбрать дату",
    topAppBarMenuIconDesc = "Открыть меню",
    nextDateIconDesc = "Следующая дата",
    previousDateIconDesc = "Предыдущая дата",
    dateDialogPickerHeadline = "Выберите дату",
    dateDialogPickerTitle = "Дневной план",
    timeTaskExpandedIconDesc = "Дополнительно",
    timeTaskCheckIconDesc = "Выполнено",
    timeTaskMoreIconDesc = "Редактировать",
    timeTaskAddIconDesc = "Добавить время",
    timeTaskRemoveIconDesc = "Убавить время",
    timeTaskIncreaseTimeTitle = "Увеличить",
    timeTaskReduceTimeTitle = "Убавить",
    startTimeTaskTitlePlaceHolder = "00:00",
    addTimeTaskIconsDesc = "Добавить задачу",
    addFreeTimeTaskTitle = "Свободное время",
    addTaskTitle = "Добавить задачу",
    navToBackTitle = "Назад",
    topAppBarMoreIconDesc = "Дополнительно",
    topAppBarTemplatesTitle = "Шаблоны",
    mainCategoryChooserTitle = "Категория",
    subCategoryChooserTitle = "Подкатегория",
    subCategoryDialogMainCategoryFormat = "Категория: %s",
    emptyScheduleTitle = "План отсутствует",
    createScheduleTitle = "Создать",
    createScheduleDesc = "Создать план для выбранного дня",
    shiftError = "Сдвиг невозможен!",
    importanceError = "Следующая задача приоритетней!",
    otherError = "Ошибка! Обратитесь к разработчику.",
    addSubCategoryTitle = "Добавить подкатегорию",
    categoryFieldLabel = "Название",
    dialogCreateTitle = "Создать",
    emptyListTitle = "Список пуст",
    updateCategoryTitle = "Редактировать",
    deleteCategoryTitle = "Удалить",
    subCategoryTitle = "Подкатегории",
    warningDeleteCategoryText = "Вы уверены что хотите удалить основную категорию? " +
        "Данное действие приведёт к уничтожению всех ранее запланированных задач.",
    sortedTypeTitle = "Сортировать",
    sortedTypeDate = "По дате",
    sortedTypeCategories = "По категориям",
    sortedTypeDuration = "По длительности",
    notificationEnabledTitle = "Включено",
    notificationDisabledTitle = "Выключено",
    statisticsActiveTitle = "Активна",
    statisticsDisabledTitle = "Выключена",
    addTemplatesFabTitle = "+",
    templateEditorHeader = "Шаблон",
    mainCategoryLabel = "Категория",
    subCategoryLabel = "Подкатегория",
    startTimeLabel = "Начало",
    endTimeLabel = "Конец",
    notificationLabel = "Отправка уведомлений",
    statisticsLabel = "Учёт статистики",
    importanceLabel = "Высокий приоритет",
    subCategoryEmptyTitle = "Отсутствует",
    addCategoryTitle = "Добавить",
    nameCategoryTitle = "Название",
    foundedPlannedTasksTitle = "Найдено запланированных задач: %s",
    monthTitle = "Месяц",
    dayTitle = "День",
    weekNumberTitle = "Номер недели",
    weekDayTitle = "День недели",
    noteTitle = "Заметка",
    restoreDefaultCategories = "Восстановить категории по умолчанию",
    schedulesHeader = "Расписания",
    realizedScheduleTitle = "Выполненное",
    accomplishmentScheduleTitle = "Текущее",
    plannedScheduleTitle = "В планах",
    undefinedTasksHeader = "Не распределённые задачи",
    executeUndefinedTasksTitle = "Выполнить",
    currentTaskHeader = "Текущая задача",
    noneTitle = "Нету",
    progressTitle = "Прогресс",
    taskDateChooserHeader = "Выберите дату планирования",
    taskDateChooserFieldLabel = "Дата",
    specifyDeadlineTitle = "Указать",
    deadlineLabel = "Дедлайн",
    showAllSchedulesTitle = "Показать больше",
)

internal val englishHomeString = HomeStrings(
    topAppBarHomeTitle = "Schedule",
    topAppBarCategoriesTitle = "Categories",
    topAppBarOverviewTitle = "Overview",
    mainCategoryTitle = "Main",
    topAppBarCalendarIconDesc = "Select a date",
    topAppBarMenuIconDesc = "Open menu",
    nextDateIconDesc = "Next date",
    previousDateIconDesc = "Previous date",
    dateDialogPickerHeadline = "Select a date",
    dateDialogPickerTitle = "Daily plan",
    timeTaskExpandedIconDesc = "More",
    timeTaskCheckIconDesc = "Completed",
    timeTaskMoreIconDesc = "Edit",
    timeTaskAddIconDesc = "Add time",
    timeTaskRemoveIconDesc = "Reduce the time",
    timeTaskIncreaseTimeTitle = "Increase",
    timeTaskReduceTimeTitle = "Reduce",
    startTimeTaskTitlePlaceHolder = "00:00",
    addTimeTaskIconsDesc = "Add task",
    addFreeTimeTaskTitle = "Free time",
    addTaskTitle = "Add a task",
    navToBackTitle = "Back",
    topAppBarMoreIconDesc = "More",
    topAppBarTemplatesTitle = "Templates",
    mainCategoryChooserTitle = "Category",
    subCategoryChooserTitle = "Subcategory",
    subCategoryDialogMainCategoryFormat = "Category: %s",
    emptyScheduleTitle = "Nothing planned yet",
    createScheduleTitle = "Plan now",
    createScheduleDesc = "Create a plan for the selected day",
    shiftError = "Shifting is not possible!",
    importanceError = "The next task takes more priority!",
    otherError = "Error! Contact the developer.",
    addSubCategoryTitle = "Add subcategory",
    categoryFieldLabel = "Name",
    dialogCreateTitle = "Create",
    emptyListTitle = "List is empty",
    updateCategoryTitle = "Edit",
    deleteCategoryTitle = "Remove",
    subCategoryTitle = "Subcategories",
    warningDeleteCategoryText = "Are you sure you want to delete the main category? " +
        "This action will destroy all previously scheduled tasks.",
    sortedTypeTitle = "Sorted",
    sortedTypeDate = "By date",
    sortedTypeCategories = "By category",
    sortedTypeDuration = "By duration",
    notificationEnabledTitle = "Enabled",
    notificationDisabledTitle = "Disabled",
    statisticsActiveTitle = "Active",
    statisticsDisabledTitle = "Disabled",
    addTemplatesFabTitle = "+",
    templateEditorHeader = "Template",
    mainCategoryLabel = "Category",
    subCategoryLabel = "Subcategory",
    startTimeLabel = "Start",
    endTimeLabel = "End",
    notificationLabel = "Sending notification",
    statisticsLabel = "Include task in statistics",
    importanceLabel = "High priority",
    subCategoryEmptyTitle = "Absent",
    addCategoryTitle = "Add",
    nameCategoryTitle = "Name",
    foundedPlannedTasksTitle = "Found scheduled tasks: %s",
    monthTitle = "Month",
    dayTitle = "Day",
    weekNumberTitle = "Week number",
    weekDayTitle = "Day of the week",
    noteTitle = "Note",
    restoreDefaultCategories = "Restore default categories",
    schedulesHeader = "Schedules",
    realizedScheduleTitle = "Completed",
    accomplishmentScheduleTitle = "Current",
    plannedScheduleTitle = "In the plans",
    undefinedTasksHeader = "Non-distributed tasks",
    executeUndefinedTasksTitle = "Execute",
    currentTaskHeader = "Current task",
    noneTitle = "None",
    progressTitle = "Progress",
    taskDateChooserHeader = "Select a planning date",
    taskDateChooserFieldLabel = "Date",
    specifyDeadlineTitle = "Specify",
    deadlineLabel = "Deadline",
    showAllSchedulesTitle = "Show more",
)

internal val persianHomeString = HomeStrings(
    topAppBarHomeTitle = "برنامه",
    topAppBarCategoriesTitle = "دسته بندی ها",
    topAppBarOverviewTitle = "نمای کلی",
    mainCategoryTitle = "اصلی",
    topAppBarCalendarIconDesc = "انتخاب تاریخ",
    topAppBarMenuIconDesc = "بازکردن منو",
    nextDateIconDesc = "بعدی",
    previousDateIconDesc = "قبلی",
    dateDialogPickerHeadline = "انتخاب تاریخ",
    dateDialogPickerTitle = "برنامه ریز روزانه",
    timeTaskExpandedIconDesc = "بیشتر",
    timeTaskCheckIconDesc = "تکمیل شد",
    timeTaskMoreIconDesc = "تغییر",
    timeTaskAddIconDesc = "افزودن زمان",
    timeTaskRemoveIconDesc = "افزایش زمان",
    timeTaskIncreaseTimeTitle = "افزایش",
    timeTaskReduceTimeTitle = "کاهش",
    startTimeTaskTitlePlaceHolder = "00:00",
    addTimeTaskIconsDesc = "افزودن وظیفه",
    addFreeTimeTaskTitle = "وقت آزاد",
    addTaskTitle = "اضافه کردن یک کار",
    navToBackTitle = "بازگشت",
    topAppBarMoreIconDesc = "بیشتر",
    topAppBarTemplatesTitle = "قالب ها",
    mainCategoryChooserTitle = "دسته بندی",
    subCategoryChooserTitle = "زیرمجموعه",
    subCategoryDialogMainCategoryFormat = "دسته: %s",
    emptyScheduleTitle = "هنوز هیچ چیز برنامه ریزی نشده است",
    createScheduleTitle = "اکنون برنامه ریزی کنید",
    createScheduleDesc = "یک برنامه برای روز انتخاب شده ایجاد کنید",
    shiftError = "جابجایی امکان پذیر نیست!",
    importanceError = "کار بعدی اولویت بیشتری دارد!",
    otherError = "خطا! با توسعه دهنده تماس بگیرید.",
    addSubCategoryTitle = "اضافه کردن زیر مجموعه",
    categoryFieldLabel = "نام",
    dialogCreateTitle = "ایجاد",
    emptyListTitle = "لیست خالی است",
    updateCategoryTitle = "تغییر",
    deleteCategoryTitle = "حذف",
    subCategoryTitle = "زیر مجموعه ها",
    warningDeleteCategoryText = "آیا مطمئن هستید که می خواهید دسته اصلی را حذف کنید؟ " +
        "این عمل تمام کارهای برنامه ریزی شده قبلی را از بین می برد.",
    sortedTypeTitle = "مرتب شده",
    sortedTypeDate = "بر اساس تاریخ",
    sortedTypeCategories = "بر اساس طبقه بندی",
    sortedTypeDuration = "بر اساس مدت زمان",
    notificationEnabledTitle = "فعال",
    notificationDisabledTitle = "غیرفعال",
    statisticsActiveTitle = "فعال",
    statisticsDisabledTitle = "غیرفعال",
    addTemplatesFabTitle = "+",
    templateEditorHeader = "قالب",
    mainCategoryLabel = "دسته بندی",
    subCategoryLabel = "زیرمجموعه",
    startTimeLabel = "شروع",
    endTimeLabel = "پایان",
    notificationLabel = "ارسال اعلان",
    statisticsLabel = "وظیفه را در آمار وارد کنید",
    importanceLabel = "اولویت بالا",
    subCategoryEmptyTitle = "خالی",
    addCategoryTitle = "افزودن",
    nameCategoryTitle = "نام",
    foundedPlannedTasksTitle = "وظایف برنامه ریزی شده یافت شد: s%",
    monthTitle = "ماه",
    dayTitle = "روز",
    weekNumberTitle = "شماره هفته",
    weekDayTitle = "روز هفته",
    noteTitle = "یادداشت",
    restoreDefaultCategories = "بازگرداندن دسته های پیش فرض",
    schedulesHeader = "برنامه ها",
    realizedScheduleTitle = "تکمیل شده",
    accomplishmentScheduleTitle = "جریان",
    plannedScheduleTitle = "در برنامه ها",
    undefinedTasksHeader = "وظایف غیر توزیع شده",
    executeUndefinedTasksTitle = "برای انجام",
    currentTaskHeader = "وظیفه فعلی",
    noneTitle = "نه",
    progressTitle = "پیشرفت",
    taskDateChooserHeader = "تاریخ برنامه ریزی را انتخاب کنید",
    taskDateChooserFieldLabel = "تاریخ",
    specifyDeadlineTitle = "انتخاب کنید",
    deadlineLabel = "مهلت",
    showAllSchedulesTitle = "نمایش بیشتر",
)

internal val germanHomeString = HomeStrings(
    topAppBarHomeTitle = "Zeitplan",
    topAppBarCategoriesTitle = "Kategorien",
    topAppBarOverviewTitle = "Überblick",
    mainCategoryTitle = "Hauptkategorie",
    topAppBarCalendarIconDesc = "Datum auswählen",
    topAppBarMenuIconDesc = "Menü öffnen",
    nextDateIconDesc = "Nächstes Datum",
    previousDateIconDesc = "Vorheriges Datum",
    dateDialogPickerHeadline = "Datum auswählen",
    dateDialogPickerTitle = "Tagesplan",
    timeTaskExpandedIconDesc = "Zusätzlich",
    timeTaskCheckIconDesc = "Erfüllt",
    timeTaskMoreIconDesc = "Mehr",
    timeTaskAddIconDesc = "Zeit hinzufügen",
    timeTaskRemoveIconDesc = "Zeit entfernen",
    timeTaskIncreaseTimeTitle = "Vergrößern",
    timeTaskReduceTimeTitle = "Verringern",
    startTimeTaskTitlePlaceHolder = "00:00",
    addTimeTaskIconsDesc = "Aufgabe hinzufügen",
    addFreeTimeTaskTitle = "Freizeit",
    addTaskTitle = "Aufgabe hinzufügen",
    navToBackTitle = "Zurück",
    topAppBarMoreIconDesc = "Mehr",
    topAppBarTemplatesTitle = "Muster",
    mainCategoryChooserTitle = "Kategorie",
    subCategoryChooserTitle = "Unterkategorie",
    subCategoryDialogMainCategoryFormat = "Kategorie: %s",
    emptyScheduleTitle = "Kein Plan",
    createScheduleTitle = "Erstellen",
    createScheduleDesc = "Einen Plan für den ausgewählten Tag erstellen",
    shiftError = "Keine Verschiebung möglich!",
    importanceError = "Die nächste Aufgabe hat Priorität!",
    otherError = "Fehler! Wenden Sie sich an den Entwickler.",
    addSubCategoryTitle = "Unterkategorie hinzufügen",
    categoryFieldLabel = "Name",
    dialogCreateTitle = "Erstellen",
    emptyListTitle = "Die Liste ist leer",
    updateCategoryTitle = "Bearbeiten",
    deleteCategoryTitle = "Entfernen",
    subCategoryTitle = "Unterkategorien",
    warningDeleteCategoryText = "Sind Sie sicher, dass Sie die Hauptkategorie löschen möchten? " +
        "Durch diese Aktion werden alle zuvor geplanten Aufgaben gelöscht.",
    sortedTypeTitle = "Sortieren",
    sortedTypeDate = "Nach Datum",
    sortedTypeCategories = "Nach Kategorie",
    sortedTypeDuration = "Nach Dauer",
    notificationEnabledTitle = "Eingeschaltet",
    notificationDisabledTitle = "Abgeschaltet",
    statisticsActiveTitle = "Aktiv",
    statisticsDisabledTitle = "Abgeschaltet",
    addTemplatesFabTitle = "+",
    templateEditorHeader = "Muster",
    mainCategoryLabel = "Kategorie",
    subCategoryLabel = "Unterkategorie",
    startTimeLabel = "Anfang",
    endTimeLabel = "Ende",
    notificationLabel = "Benachrichtigungen",
    statisticsLabel = "Statistik",
    importanceLabel = "Hohe Priorität",
    subCategoryEmptyTitle = "Leer",
    addCategoryTitle = "Hinzufügen",
    nameCategoryTitle = "Name",
    foundedPlannedTasksTitle = "Geplante Aufgaben gefunden: %s",
    monthTitle = "Monat",
    dayTitle = "Tag",
    weekNumberTitle = "Wochennummer",
    weekDayTitle = "Wochentag",
    noteTitle = "Notiz",
    restoreDefaultCategories = "Standardkategorien wiederherstellen",
    schedulesHeader = "Zeitpläne",
    realizedScheduleTitle = "Erledigt",
    accomplishmentScheduleTitle = "Aktuelles",
    plannedScheduleTitle = "Geplant",
    undefinedTasksHeader = "Nicht verteilte Aufgaben",
    executeUndefinedTasksTitle = "Erfüllen",
    currentTaskHeader = "aktive Aufgabe",
    noneTitle = "Keine",
    progressTitle = "Fortschritt",
    taskDateChooserHeader = "Wählen Sie ein Planungsdatum aus",
    taskDateChooserFieldLabel = "Datum",
    specifyDeadlineTitle = "Angeben",
    deadlineLabel = "Frist",
    showAllSchedulesTitle = "Mehr anzeigen",
)

internal val spanishHomeString = HomeStrings(
    topAppBarHomeTitle = "Horario",
    topAppBarCategoriesTitle = "Categorías",
    topAppBarOverviewTitle = "Visión general",
    mainCategoryTitle = "Página principal",
    topAppBarCalendarIconDesc = "Selecciona fecha",
    topAppBarMenuIconDesc = "Abrir menú",
    nextDateIconDesc = "Próxima fecha",
    previousDateIconDesc = "Fecha anterior",
    dateDialogPickerHeadline = "Selecciona fecha",
    dateDialogPickerTitle = "Plan diario",
    timeTaskExpandedIconDesc = "Más",
    timeTaskCheckIconDesc = "Completado",
    timeTaskMoreIconDesc = "Editar",
    timeTaskAddIconDesc = "Añadir tiempo",
    timeTaskRemoveIconDesc = "Reducir tiempo",
    timeTaskIncreaseTimeTitle = "Aumentar",
    timeTaskReduceTimeTitle = "Reducir",
    startTimeTaskTitlePlaceHolder = "00:00",
    addTimeTaskIconsDesc = "Añadir tarea",
    addFreeTimeTaskTitle = "Tiempo libre",
    addTaskTitle = "Añadir una tarea",
    navToBackTitle = "Volver",
    topAppBarMoreIconDesc = "Más",
    topAppBarTemplatesTitle = "Plantillas",
    mainCategoryChooserTitle = "Categoría",
    subCategoryChooserTitle = "Subcategoría",
    subCategoryDialogMainCategoryFormat = "Categoría: %s",
    emptyScheduleTitle = "Nada planeado todavía",
    createScheduleTitle = "Añadir tarea",
    createScheduleDesc = "Crea un plan para el día seleccionado",
    shiftError = "¡No es posible aplazarla!",
    importanceError = "¡La siguiente tarea tiene más prioridad!",
    otherError = "¡Error! Contacta al desarrollador.",
    addSubCategoryTitle = "Añadir subcategoría",
    categoryFieldLabel = "Nombre",
    dialogCreateTitle = "Crear",
    emptyListTitle = "Lista vacía",
    updateCategoryTitle = "Editar",
    deleteCategoryTitle = "Eliminar",
    subCategoryTitle = "Subcategorías",
    warningDeleteCategoryText = "¿Quieres eliminar la categoría principal? " +
        "Esto eliminará todas las tareas programadas anteriormente.",
    sortedTypeTitle = "Ordenado",
    sortedTypeDate = "Por fecha",
    sortedTypeCategories = "Por categoría",
    sortedTypeDuration = "Por duración",
    notificationEnabledTitle = "Activada",
    notificationDisabledTitle = "Desactivada",
    statisticsActiveTitle = "Activada",
    statisticsDisabledTitle = "Desactivada",
    addTemplatesFabTitle = "+",
    templateEditorHeader = "Plantilla",
    mainCategoryLabel = "Categoría",
    subCategoryLabel = "Subcategoría",
    startTimeLabel = "Empieza",
    endTimeLabel = "Termina",
    notificationLabel = "Enviar notificación",
    statisticsLabel = "Incluir en estadísticas",
    importanceLabel = "Prioridad especial",
    subCategoryEmptyTitle = "Ninguna",
    addCategoryTitle = "Añadir",
    nameCategoryTitle = "Nombre",
    foundedPlannedTasksTitle = "Encontrado tareas programadas: %s",
    monthTitle = "Mesв",
    dayTitle = "Día",
    weekNumberTitle = "Número de la semana",
    weekDayTitle = "Feria",
    noteTitle = "Nota",
    restoreDefaultCategories = "Restaurar categorías predeterminadas",
    schedulesHeader = "Horarios",
    realizedScheduleTitle = "Realizado",
    accomplishmentScheduleTitle = "Actual",
    plannedScheduleTitle = "En los planes",
    undefinedTasksHeader = "Tareas no distribuidas",
    executeUndefinedTasksTitle = "Ejecutar",
    currentTaskHeader = "Tarea actual",
    noneTitle = "No",
    progressTitle = "Progreso",
    taskDateChooserHeader = "Seleccione una fecha de planificación",
    taskDateChooserFieldLabel = "Fecha",
    specifyDeadlineTitle = "Especificar",
    deadlineLabel = "Fecha límite",
    showAllSchedulesTitle = "Mostrar más",
)

internal val frenchHomeString = HomeStrings(
    topAppBarHomeTitle = "Horaire",
    topAppBarCategoriesTitle = "Categories",
    topAppBarOverviewTitle = "Vue d'Ensemble",
    mainCategoryTitle = "Principal",
    topAppBarCalendarIconDesc = "Sélectionnez une date",
    topAppBarMenuIconDesc = "Ouvrir le menu",
    nextDateIconDesc = "Date suivante",
    previousDateIconDesc = "Date précédente",
    dateDialogPickerHeadline = "Selectionner une date",
    dateDialogPickerTitle = "Planning journalier",
    timeTaskExpandedIconDesc = "Plus",
    timeTaskCheckIconDesc = "Complété",
    timeTaskMoreIconDesc = "Modifier",
    timeTaskAddIconDesc = "Ajouter du temps",
    timeTaskRemoveIconDesc = "Enlever du temps",
    timeTaskIncreaseTimeTitle = "Ajouter",
    timeTaskReduceTimeTitle = "Réduire",
    startTimeTaskTitlePlaceHolder = "00:00",
    addTimeTaskIconsDesc = "Ajouter une tâche",
    addFreeTimeTaskTitle = "Temps libre",
    addTaskTitle = "Ajouter une tâche",
    navToBackTitle = "Retour",
    topAppBarMoreIconDesc = "Plus",
    topAppBarTemplatesTitle = "Modèles",
    mainCategoryChooserTitle = "Catégories",
    subCategoryChooserTitle = "Sous-catégories",
    subCategoryDialogMainCategoryFormat = "Categorie: %s",
    emptyScheduleTitle = "Rien de prévu pour le moment",
    createScheduleTitle = "Ajouter quelque chose",
    createScheduleDesc = "Créer un planning pour la journée selectionnée",
    shiftError = "Impossible de déplacer cette tâche!",
    importanceError = "La tâche suivante est prioritaire!",
    otherError = "Erreur! Veuiller contacter le developpeur.",
    addSubCategoryTitle = "Ajouter une sous-catégorie",
    categoryFieldLabel = "Titre",
    dialogCreateTitle = "Créer",
    emptyListTitle = "La liste est vide",
    updateCategoryTitle = "Modifier",
    deleteCategoryTitle = "Supprimer",
    subCategoryTitle = "Sous-catégories",
    warningDeleteCategoryText = "Êtes-vous sur(e) de vouloir supprimer la catégorie principale? " +
        "Cette action engendredra la suppression de toutes les tâches prévues.",
    sortedTypeTitle = "Trié",
    sortedTypeDate = "Par date",
    sortedTypeCategories = "Par catégorie",
    sortedTypeDuration = "Par durée",
    notificationEnabledTitle = "Activé",
    notificationDisabledTitle = "Désactivé",
    statisticsActiveTitle = "Activé",
    statisticsDisabledTitle = "Désactivé",
    addTemplatesFabTitle = "+",
    templateEditorHeader = "Modèle",
    mainCategoryLabel = "Catégorie",
    subCategoryLabel = "Sous-catégorie",
    startTimeLabel = "Début",
    endTimeLabel = "Fin",
    notificationLabel = "Envoi d'une notification",
    statisticsLabel = "Inclure dans les statistiques",
    importanceLabel = "Priorité haute",
    subCategoryEmptyTitle = "Absent",
    addCategoryTitle = "Ajouter",
    nameCategoryTitle = "Titre",
    foundedPlannedTasksTitle = "Tâches planifiés trouvées: %s",
    monthTitle = "Mois",
    dayTitle = "Jour",
    weekNumberTitle = "Semaine n°",
    weekDayTitle = "Jour de la semaine",
    noteTitle = "Note",
    restoreDefaultCategories = "Restaurer les Catégories par défaut",
    schedulesHeader = "Horaires",
    realizedScheduleTitle = "Accompli",
    accomplishmentScheduleTitle = "Actuel",
    plannedScheduleTitle = "Dans les plans",
    undefinedTasksHeader = "Tâches non distribuées",
    executeUndefinedTasksTitle = "Exécuter",
    currentTaskHeader = "Tâche actuelle",
    noneTitle = "Non",
    progressTitle = "Progrès",
    taskDateChooserHeader = "Seleccione una fecha de planificación",
    taskDateChooserFieldLabel = "Fecha",
    specifyDeadlineTitle = "Précisez",
    deadlineLabel = "Date limite",
    showAllSchedulesTitle = "Voir plus",
)
internal val brazilianPortugueseHomeString = HomeStrings(
    topAppBarHomeTitle = "Horário",
    topAppBarCategoriesTitle = "Categorias",
    mainCategoryTitle = "Principal",
    topAppBarCalendarIconDesc = "Selecione uma data",
    topAppBarMenuIconDesc = "Abrir menu",
    topAppBarOverviewTitle = "Visão geral",
    nextDateIconDesc = "Próxima data",
    previousDateIconDesc = "Data anterior",
    dateDialogPickerHeadline = "Selecione uma data",
    dateDialogPickerTitle = "Planejamento diário",
    timeTaskExpandedIconDesc = "Mais",
    timeTaskCheckIconDesc = "Completo",
    timeTaskMoreIconDesc = "Editar",
    timeTaskAddIconDesc = "Adicionar tempo",
    timeTaskRemoveIconDesc = "Reduzir tempo",
    timeTaskIncreaseTimeTitle = "Aumentar",
    timeTaskReduceTimeTitle = "Reduzir",
    startTimeTaskTitlePlaceHolder = "00:00",
    addTimeTaskIconsDesc = "Adicionar tarefa",
    addFreeTimeTaskTitle = "Tempo livre",
    addTaskTitle = "Adicionar tarefa",
    navToBackTitle = "Voltar",
    topAppBarMoreIconDesc = "Mais",
    topAppBarTemplatesTitle = "Templates",
    mainCategoryChooserTitle = "Categoria",
    subCategoryChooserTitle = "Subcategoria",
    subCategoryDialogMainCategoryFormat = "Categoria: %s",
    emptyScheduleTitle = "Nada planejado ainda",
    createScheduleTitle = "Planejar agora",
    createScheduleDesc = "Criar um planejamento para o dia selecionado",
    shiftError = "Impossível utilizar o shift!",
    importanceError = "A próxima tarefa possui maior prioridade!",
    otherError = "Erro! Contate o desenvolvedor.",
    addSubCategoryTitle = "Adicionar subcategoria",
    categoryFieldLabel = "Nome",
    dialogCreateTitle = "Criar",
    emptyListTitle = "Lista está vazia",
    updateCategoryTitle = "Editar",
    deleteCategoryTitle = "Remover",
    subCategoryTitle = "Subcategorias",
    warningDeleteCategoryText = "Você tem certeza que deseja deletar a categoria principal? " +
        "Esta ação irá apagar todas as tarefas previamente planejadas.",
    sortedTypeTitle = "Classificado",
    sortedTypeDate = "Por dia",
    sortedTypeCategories = "Por categoria",
    sortedTypeDuration = "Por duração",
    notificationEnabledTitle = "Ativado",
    notificationDisabledTitle = "Desativado",
    statisticsActiveTitle = "Ativado",
    statisticsDisabledTitle = "Desativado",
    addTemplatesFabTitle = "+",
    templateEditorHeader = "Template",
    mainCategoryLabel = "Categoria",
    subCategoryLabel = "Subcategoria",
    startTimeLabel = "Iniciar",
    endTimeLabel = "Terminar",
    notificationLabel = "Enviar notificação",
    statisticsLabel = "Incluir tarefa nas estatísticas",
    importanceLabel = "Alta prioridade",
    subCategoryEmptyTitle = "Faltou",
    addCategoryTitle = "Adicionar",
    nameCategoryTitle = "Nome",
    foundedPlannedTasksTitle = "Encontrou tarefas planejadas: %s",
    monthTitle = "Mês",
    dayTitle = "Dia",
    weekNumberTitle = "Número da semana",
    weekDayTitle = "Dia da semana",
    noteTitle = "Nota",
    restoreDefaultCategories = "Restaurar categorias originais",
    schedulesHeader = "Horário",
    realizedScheduleTitle = "Feito",
    accomplishmentScheduleTitle = "Atual",
    plannedScheduleTitle = "Nos planos",
    undefinedTasksHeader = "Tarefas não distribuídas",
    executeUndefinedTasksTitle = "Para executar",
    currentTaskHeader = "Tarefa atual",
    noneTitle = "No",
    progressTitle = "Progresso",
    taskDateChooserHeader = "Selecione uma data de planejamento",
    taskDateChooserFieldLabel = "Data",
    specifyDeadlineTitle = "Apontar",
    deadlineLabel = "Prazo",
    showAllSchedulesTitle = "Mostrar mais",
)

internal val turkishHomeString = HomeStrings(
    topAppBarHomeTitle = "Program",
    topAppBarCategoriesTitle = "Kategoriler",
    topAppBarOverviewTitle = "Genel Bakış",
    mainCategoryTitle = "Ana",
    topAppBarCalendarIconDesc = "Bir tarih seçin",
    topAppBarMenuIconDesc = "Menüyü aç",
    nextDateIconDesc = "Sıradaki buluşma",
    previousDateIconDesc = "Önceki tarih",
    dateDialogPickerHeadline = "Bir tarih seçin",
    dateDialogPickerTitle = "Günlük plan",
    timeTaskExpandedIconDesc = "Daha fazla",
    timeTaskCheckIconDesc = "Tamamlandı",
    timeTaskMoreIconDesc = "Düzenle",
    timeTaskAddIconDesc = "Zaman ekle",
    timeTaskRemoveIconDesc = "Zamanı azalt",
    timeTaskIncreaseTimeTitle = "Arttır",
    timeTaskReduceTimeTitle = "Azalt",
    startTimeTaskTitlePlaceHolder = "00:00",
    addTimeTaskIconsDesc = "Görev ekle",
    addFreeTimeTaskTitle = "Boş zaman",
    addTaskTitle = "Görev ekle",
    navToBackTitle = "Geri",
    topAppBarMoreIconDesc = "Daha fazla",
    topAppBarTemplatesTitle = "Şablonlar",
    mainCategoryChooserTitle = "Kategori",
    subCategoryChooserTitle = "Alt kategori",
    subCategoryDialogMainCategoryFormat = "Kategori: %s",
    emptyScheduleTitle = "Henüz planlanmış bir şey yok",
    createScheduleTitle = "Şimdi planla",
    createScheduleDesc = "Seçilen gün için bir plan oluştur",
    shiftError = "Kaydırma mümkün değil!",
    importanceError = "Sonraki görev daha fazla öncelik taşıyor!",
    otherError = "Hata! Geliştirici ile iletişime geçin.",
    addSubCategoryTitle = "Alt kategori ekle",
    categoryFieldLabel = "Ad",
    dialogCreateTitle = "Oluştur",
    emptyListTitle = "Liste boş",
    updateCategoryTitle = "Düzenle",
    deleteCategoryTitle = "Kaldır",
    subCategoryTitle = "Alt kategoriler",
    warningDeleteCategoryText = "Ana kategoriyi silmek istediğinizden emin misiniz? " +
        "Bu işlem önceden planlanmış tüm görevleri yok eder.",
    sortedTypeTitle = "Sıralı",
    sortedTypeDate = "Tarihe göre",
    sortedTypeCategories = "Kategoriye göre",
    sortedTypeDuration = "Süreye göre",
    notificationEnabledTitle = "Etkin",
    notificationDisabledTitle = "Devre dışı",
    statisticsActiveTitle = "Aktif",
    statisticsDisabledTitle = "Devre dışı",
    addTemplatesFabTitle = "+",
    templateEditorHeader = "Şablon",
    mainCategoryLabel = "Kategori",
    subCategoryLabel = "Alt kategori",
    startTimeLabel = "Başlangıç",
    endTimeLabel = "Bitiş",
    notificationLabel = "Bildirim gönderme",
    statisticsLabel = "Görevi istatistiklere dahil et",
    importanceLabel = "Yüksek öncelik",
    subCategoryEmptyTitle = "Yok",
    addCategoryTitle = "Ekle",
    nameCategoryTitle = "Ad",
    foundedPlannedTasksTitle = "Planlanmış görevler bulundu: %s",
    monthTitle = "Ay",
    dayTitle = "Gün",
    weekNumberTitle = "Hafta numarası",
    weekDayTitle = "Haftanın günü",
    noteTitle = "Not",
    restoreDefaultCategories = "Varsayılan kategorilere geri dön",
    schedulesHeader = "Planlar",
    realizedScheduleTitle = "Tamamlandı",
    accomplishmentScheduleTitle = "Mevcut",
    plannedScheduleTitle = "Planlar içinde",
    undefinedTasksHeader = "Dağıtılmamış görevler",
    executeUndefinedTasksTitle = "Yürüt",
    currentTaskHeader = "Mevcut görev",
    noneTitle = "Hiçbiri",
    progressTitle = "İlerleme",
    taskDateChooserHeader = "Bir planlama tarihi seçin",
    taskDateChooserFieldLabel = "Tarih",
    specifyDeadlineTitle = "Belirt",
    deadlineLabel = "Son tarih",
    showAllSchedulesTitle = "Daha fazlasını göster",
)

internal val LocalHomeStrings = staticCompositionLocalOf<HomeStrings> {
    error("Home Strings is not provided")
}

internal fun fetchHomeStrings(language: TimePlannerLanguage) = when (language) {
    TimePlannerLanguage.EN -> englishHomeString
    TimePlannerLanguage.RU -> russianHomeString
    TimePlannerLanguage.DE -> germanHomeString
    TimePlannerLanguage.ES -> spanishHomeString
    TimePlannerLanguage.FA -> persianHomeString
    TimePlannerLanguage.FR -> frenchHomeString
    TimePlannerLanguage.PT -> brazilianPortugueseHomeString
    TimePlannerLanguage.TR -> turkishHomeString
}
