/*
 * Copyright 2026 Stanislav Aleshin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ru.aleshin.features.home.impl.presentation.theme.tokens

import androidx.compose.runtime.staticCompositionLocalOf
import ru.aleshin.timeplanner.core.ui.theme.tokens.TimePlannerLanguage

/**
 * @author Stanislav Aleshin on 18.02.2023.
 */
internal data class HomeStrings(
    val topAppBarHomeTitle: String,
    val topAppBarOverviewTitle: String,
    val topAppBarCalendarIconDesc: String,
    val topAppBarMenuIconDesc: String,
    val agendaTabTitle: String,
    val timelineTabTitle: String,
    val timelineTaskMoveIconDesc: String,
    val timelineTaskEditCancelIconDesc: String,
    val timelineNowTitle: String,
    val nextDateIconDesc: String,
    val previousDateIconDesc: String,
    val dateDialogPickerHeadline: String,
    val dateDialogPickerTitle: String,
    val timeTaskMoreIconDesc: String,
    val timeTaskAddIconDesc: String,
    val timeTaskRemoveIconDesc: String,
    val timeTaskIncreaseTimeTitle: String,
    val timeTaskReduceTimeTitle: String,
    val addFreeTimeTaskTitle: String,
    val addTaskTitle: String,
    val createScheduleTitle: String,
    val createScheduleDesc: String,
    val shiftError: String,
    val importanceError: String,
    val otherError: String,
    val noteTitle: String,
    val noneTitle: String,
)

internal val russianHomeString = HomeStrings(
    topAppBarHomeTitle = "Расписание",
    topAppBarOverviewTitle = "Обзор",
    topAppBarCalendarIconDesc = "Выбрать дату",
    topAppBarMenuIconDesc = "Открыть меню",
    agendaTabTitle = "Список",
    timelineTabTitle = "Таймлайн",
    timelineTaskMoveIconDesc = "Переместить задачу",
    timelineTaskEditCancelIconDesc = "Завершить изменение времени",
    timelineNowTitle = "Сейчас",
    nextDateIconDesc = "Следующая дата",
    previousDateIconDesc = "Предыдущая дата",
    dateDialogPickerHeadline = "Выберите дату",
    dateDialogPickerTitle = "Дневной план",
    timeTaskMoreIconDesc = "Редактировать",
    timeTaskAddIconDesc = "Добавить время",
    timeTaskRemoveIconDesc = "Убавить время",
    timeTaskIncreaseTimeTitle = "Увеличить",
    timeTaskReduceTimeTitle = "Убавить",
    addFreeTimeTaskTitle = "Свободное время",
    addTaskTitle = "Добавить задачу",
    createScheduleTitle = "Создать",
    createScheduleDesc = "Создать план для выбранного дня",
    shiftError = "Сдвиг невозможен!",
    importanceError = "Следующая задача приоритетней!",
    otherError = "Ошибка! Обратитесь к разработчику.",
    noteTitle = "Заметка",
    noneTitle = "Нету",
)

internal val englishHomeString = HomeStrings(
    topAppBarHomeTitle = "Schedule",
    topAppBarOverviewTitle = "Overview",
    topAppBarCalendarIconDesc = "Select a date",
    topAppBarMenuIconDesc = "Open menu",
    agendaTabTitle = "Agenda",
    timelineTabTitle = "Timeline",
    timelineTaskMoveIconDesc = "Move task",
    timelineTaskEditCancelIconDesc = "Finish editing time",
    timelineNowTitle = "Now",
    nextDateIconDesc = "Next date",
    previousDateIconDesc = "Previous date",
    dateDialogPickerHeadline = "Select a date",
    dateDialogPickerTitle = "Daily plan",
    timeTaskMoreIconDesc = "Edit",
    timeTaskAddIconDesc = "Add time",
    timeTaskRemoveIconDesc = "Reduce the time",
    timeTaskIncreaseTimeTitle = "Increase",
    timeTaskReduceTimeTitle = "Reduce",
    addFreeTimeTaskTitle = "Unassigned",
    addTaskTitle = "Add a task",
    createScheduleTitle = "Plan now",
    createScheduleDesc = "Create a plan for the selected day",
    shiftError = "Rescheduling is not possible!",
    importanceError = "The next task has higher priority",
    otherError = "Something went wrong. Contact the developer for help.",
    noteTitle = "Note",
    noneTitle = "None",
)

internal val persianHomeString = HomeStrings(
    topAppBarHomeTitle = "برنامه",
    topAppBarOverviewTitle = "نمای کلی",
    topAppBarCalendarIconDesc = "انتخاب تاریخ",
    topAppBarMenuIconDesc = "بازکردن منو",
    agendaTabTitle = "فهرست",
    timelineTabTitle = "خط زمانی",
    timelineTaskMoveIconDesc = "جابجایی کار",
    timelineTaskEditCancelIconDesc = "پایان ویرایش زمان",
    timelineNowTitle = "اکنون",
    nextDateIconDesc = "بعدی",
    previousDateIconDesc = "قبلی",
    dateDialogPickerHeadline = "انتخاب تاریخ",
    dateDialogPickerTitle = "برنامه ریز روزانه",
    timeTaskMoreIconDesc = "تغییر",
    timeTaskAddIconDesc = "افزودن زمان",
    timeTaskRemoveIconDesc = "افزایش زمان",
    timeTaskIncreaseTimeTitle = "افزایش",
    timeTaskReduceTimeTitle = "کاهش",
    addFreeTimeTaskTitle = "وقت آزاد",
    addTaskTitle = "اضافه کردن یک کار",
    createScheduleTitle = "اکنون برنامه ریزی کنید",
    createScheduleDesc = "یک برنامه برای روز انتخاب شده ایجاد کنید",
    shiftError = "جابجایی امکان پذیر نیست!",
    importanceError = "کار بعدی اولویت بیشتری دارد!",
    otherError = "خطا! با توسعه دهنده تماس بگیرید.",
    noteTitle = "یادداشت",
    noneTitle = "نه",
)

internal val germanHomeString = HomeStrings(
    topAppBarHomeTitle = "Zeitplan",
    topAppBarOverviewTitle = "Überblick",
    topAppBarCalendarIconDesc = "Datum auswählen",
    topAppBarMenuIconDesc = "Menü öffnen",
    agendaTabTitle = "Liste",
    timelineTabTitle = "Zeitleiste",
    timelineTaskMoveIconDesc = "Aufgabe verschieben",
    timelineTaskEditCancelIconDesc = "Zeitbearbeitung beenden",
    timelineNowTitle = "Jetzt",
    nextDateIconDesc = "Nächstes Datum",
    previousDateIconDesc = "Vorheriges Datum",
    dateDialogPickerHeadline = "Datum auswählen",
    dateDialogPickerTitle = "Tagesplan",
    timeTaskMoreIconDesc = "Mehr",
    timeTaskAddIconDesc = "Zeit hinzufügen",
    timeTaskRemoveIconDesc = "Zeit entfernen",
    timeTaskIncreaseTimeTitle = "Vergrößern",
    timeTaskReduceTimeTitle = "Verringern",
    addFreeTimeTaskTitle = "Freizeit",
    addTaskTitle = "Aufgabe hinzufügen",
    createScheduleTitle = "Erstellen",
    createScheduleDesc = "Einen Plan für den ausgewählten Tag erstellen",
    shiftError = "Keine Verschiebung möglich!",
    importanceError = "Die nächste Aufgabe hat Priorität!",
    otherError = "Fehler! Wenden Sie sich an den Entwickler.",
    noteTitle = "Notiz",
    noneTitle = "Keine",
)

internal val spanishHomeString = HomeStrings(
    topAppBarHomeTitle = "Horario",
    topAppBarOverviewTitle = "Visión general",
    topAppBarCalendarIconDesc = "Selecciona fecha",
    topAppBarMenuIconDesc = "Abrir menú",
    agendaTabTitle = "Agenda",
    timelineTabTitle = "Cronología",
    timelineTaskMoveIconDesc = "Mover tarea",
    timelineTaskEditCancelIconDesc = "Finalizar edición de hora",
    timelineNowTitle = "Ahora",
    nextDateIconDesc = "Próxima fecha",
    previousDateIconDesc = "Fecha anterior",
    dateDialogPickerHeadline = "Selecciona fecha",
    dateDialogPickerTitle = "Plan diario",
    timeTaskMoreIconDesc = "Editar",
    timeTaskAddIconDesc = "Añadir tiempo",
    timeTaskRemoveIconDesc = "Reducir tiempo",
    timeTaskIncreaseTimeTitle = "Aumentar",
    timeTaskReduceTimeTitle = "Reducir",
    addFreeTimeTaskTitle = "Tiempo libre",
    addTaskTitle = "Añadir una tarea",
    createScheduleTitle = "Añadir tarea",
    createScheduleDesc = "Crea un plan para el día seleccionado",
    shiftError = "¡No es posible aplazarla!",
    importanceError = "¡La siguiente tarea tiene más prioridad!",
    otherError = "¡Error! Contacta al desarrollador.",
    noteTitle = "Nota",
    noneTitle = "No",
)

internal val frenchHomeString = HomeStrings(
    topAppBarHomeTitle = "Horaire",
    topAppBarOverviewTitle = "Vue d'Ensemble",
    topAppBarCalendarIconDesc = "Sélectionnez une date",
    topAppBarMenuIconDesc = "Ouvrir le menu",
    agendaTabTitle = "Liste",
    timelineTabTitle = "Chronologie",
    timelineTaskMoveIconDesc = "Déplacer la tâche",
    timelineTaskEditCancelIconDesc = "Terminer la modification de l’heure",
    timelineNowTitle = "Maintenant",
    nextDateIconDesc = "Date suivante",
    previousDateIconDesc = "Date précédente",
    dateDialogPickerHeadline = "Selectionner une date",
    dateDialogPickerTitle = "Planning journalier",
    timeTaskMoreIconDesc = "Modifier",
    timeTaskAddIconDesc = "Ajouter du temps",
    timeTaskRemoveIconDesc = "Enlever du temps",
    timeTaskIncreaseTimeTitle = "Ajouter",
    timeTaskReduceTimeTitle = "Réduire",
    addFreeTimeTaskTitle = "Temps libre",
    addTaskTitle = "Ajouter une tâche",
    createScheduleTitle = "Ajouter quelque chose",
    createScheduleDesc = "Créer un planning pour la journée selectionnée",
    shiftError = "Impossible de déplacer cette tâche!",
    importanceError = "La tâche suivante est prioritaire!",
    otherError = "Erreur! Veuiller contacter le developpeur.",
    noteTitle = "Note",
    noneTitle = "Non",
)
internal val brazilianPortugueseHomeString = HomeStrings(
    topAppBarHomeTitle = "Horário",
    topAppBarCalendarIconDesc = "Selecione uma data",
    topAppBarMenuIconDesc = "Abrir menu",
    agendaTabTitle = "Agenda",
    timelineTabTitle = "Linha do tempo",
    timelineTaskMoveIconDesc = "Mover tarefa",
    timelineTaskEditCancelIconDesc = "Concluir edição de horário",
    timelineNowTitle = "Agora",
    topAppBarOverviewTitle = "Visão geral",
    nextDateIconDesc = "Próxima data",
    previousDateIconDesc = "Data anterior",
    dateDialogPickerHeadline = "Selecione uma data",
    dateDialogPickerTitle = "Planejamento diário",
    timeTaskMoreIconDesc = "Editar",
    timeTaskAddIconDesc = "Adicionar tempo",
    timeTaskRemoveIconDesc = "Reduzir tempo",
    timeTaskIncreaseTimeTitle = "Aumentar",
    timeTaskReduceTimeTitle = "Reduzir",
    addFreeTimeTaskTitle = "Tempo livre",
    addTaskTitle = "Adicionar tarefa",
    createScheduleTitle = "Planejar agora",
    createScheduleDesc = "Criar um planejamento para o dia selecionado",
    shiftError = "Impossível utilizar o shift!",
    importanceError = "A próxima tarefa possui maior prioridade!",
    otherError = "Erro! Contate o desenvolvedor.",
    noteTitle = "Nota",
    noneTitle = "No",
)

internal val turkishHomeString = HomeStrings(
    topAppBarHomeTitle = "Program",
    topAppBarOverviewTitle = "Genel Bakış",
    topAppBarCalendarIconDesc = "Bir tarih seçin",
    topAppBarMenuIconDesc = "Menüyü aç",
    agendaTabTitle = "Ajanda",
    timelineTabTitle = "Zaman çizelgesi",
    timelineTaskMoveIconDesc = "Görevi taşı",
    timelineTaskEditCancelIconDesc = "Zaman düzenlemeyi bitir",
    timelineNowTitle = "Şimdi",
    nextDateIconDesc = "Sıradaki buluşma",
    previousDateIconDesc = "Önceki tarih",
    dateDialogPickerHeadline = "Bir tarih seçin",
    dateDialogPickerTitle = "Günlük plan",
    timeTaskMoreIconDesc = "Düzenle",
    timeTaskAddIconDesc = "Zaman ekle",
    timeTaskRemoveIconDesc = "Zamanı azalt",
    timeTaskIncreaseTimeTitle = "Arttır",
    timeTaskReduceTimeTitle = "Azalt",
    addFreeTimeTaskTitle = "Boş zaman",
    addTaskTitle = "Görev ekle",
    createScheduleTitle = "Şimdi planla",
    createScheduleDesc = "Seçilen gün için bir plan oluştur",
    shiftError = "Kaydırma mümkün değil!",
    importanceError = "Sonraki görev daha fazla öncelik taşıyor!",
    otherError = "Hata! Geliştirici ile iletişime geçin.",
    noteTitle = "Not",
    noneTitle = "Hiçbiri",
)

internal val vietnameseHomeString = HomeStrings(
    topAppBarHomeTitle = "Lịch trình",
    topAppBarOverviewTitle = "Tổng quan",
    topAppBarCalendarIconDesc = "Chọn ngày",
    topAppBarMenuIconDesc = "Mở thực đơn",
    agendaTabTitle = "Danh sách",
    timelineTabTitle = "Dòng thời gian",
    timelineTaskMoveIconDesc = "Di chuyển nhiệm vụ",
    timelineTaskEditCancelIconDesc = "Kết thúc chỉnh sửa thời gian",
    timelineNowTitle = "Bây giờ",
    nextDateIconDesc = "Ngày tiếp theo",
    previousDateIconDesc = "Ngày trước đó",
    dateDialogPickerHeadline = "Chọn ngày",
    dateDialogPickerTitle = "Kế hoạch hàng ngày",
    timeTaskMoreIconDesc = "Biên tập",
    timeTaskAddIconDesc = "Thêm thời gian",
    timeTaskRemoveIconDesc = "Giảm thời gian",
    timeTaskIncreaseTimeTitle =	"Tăng",
    timeTaskReduceTimeTitle = "Giảm bớt",
    addFreeTimeTaskTitle = "Thời gian rảnh",
    addTaskTitle = "Thêm nhiệm vụ",
    createScheduleTitle = "Lên kế hoạch ngay bây giờ",
    createScheduleDesc = "Tạo kế hoạch cho ngày đã chọn",
    shiftError = "Không thể chuyển đổi!",
    importanceError =	"Nhiệm vụ tiếp theo được ưu tiên hơn!",
    otherError = "Lỗi! Hãy liên hệ với nhà phát triển.",
    noteTitle = "Ghi chú",
    noneTitle = "Không có",
)

internal val polishHomeString = HomeStrings(
    topAppBarHomeTitle = "Planer",
    topAppBarOverviewTitle = "Przegląd",
    topAppBarCalendarIconDesc = "Wybierz datę",
    topAppBarMenuIconDesc = "Otwórz menu",
    agendaTabTitle = "Lista",
    timelineTabTitle = "Oś czasu",
    timelineTaskMoveIconDesc = "Przenieś zadanie",
    timelineTaskEditCancelIconDesc = "Zakończ edycję czasu",
    timelineNowTitle = "Teraz",
    nextDateIconDesc = "Następna data",
    previousDateIconDesc = "Wcześniejsza data",
    dateDialogPickerHeadline = "Wybierz datę",
    dateDialogPickerTitle = "Plan dzienny",
    timeTaskMoreIconDesc = "Edytuj",
    timeTaskAddIconDesc = "Dodaj czas",
    timeTaskRemoveIconDesc = "Skróć czas",
    timeTaskIncreaseTimeTitle = "Zwiększ",
    timeTaskReduceTimeTitle = "Zmniejsz",
    addFreeTimeTaskTitle = "Czas wolny",
    addTaskTitle = "Dodaj zadanie",
    createScheduleTitle = "Zaplanuj teraz",
    createScheduleDesc = "Utwórz plan na wybrany dzień",
    shiftError = "Zmiana planu nie jest możliwa!",
    importanceError = "Następne zadanie ma wyższy priorytet",
    otherError = "Coś poszło nie tak. Skontaktuj się z deweloperem by otrzymać pomoc.",
	noteTitle = "Notatka",
    noneTitle = "Brak",
)

internal val italianHomeString = HomeStrings(
    topAppBarHomeTitle = "Agenda",
    topAppBarOverviewTitle = "Panoramica",
    topAppBarCalendarIconDesc = "Seleziona una data",
    topAppBarMenuIconDesc = "Apri menu",
    agendaTabTitle = "Agenda",
    timelineTabTitle = "Cronologia",
    timelineTaskMoveIconDesc = "Sposta attività",
    timelineTaskEditCancelIconDesc = "Termina modifica dell’orario",
    timelineNowTitle = "Ora",
    nextDateIconDesc = "Prossima data",
    previousDateIconDesc = "Data precedente",
    dateDialogPickerHeadline = "Seleziona una data",
    dateDialogPickerTitle = "Pianificazione giornaliera",
    timeTaskMoreIconDesc = "Modifica",
    timeTaskAddIconDesc = "Inserisci orario",
    timeTaskRemoveIconDesc = "Diminuisci la durata",
    timeTaskIncreaseTimeTitle = "Aumenta",
    timeTaskReduceTimeTitle = "diminuisci",
    addFreeTimeTaskTitle = "Non Assegnati",
    addTaskTitle = "Nuovo task",
    createScheduleTitle = "Pianifica adesso",
    createScheduleDesc = "Pianifica per il giorno selezionato",
    shiftError = "La riassegnazione non è possibile!",
    importanceError = "Il prossimo task ha una priorità più elevata",
    otherError = "Qualcosa è andato storto. Contatta lo sviluppatore per ottenere assistenza.",
    noteTitle = "Note",
    noneTitle = "Niente",
)


internal val chineseHomeString = HomeStrings(
    topAppBarHomeTitle = "日程",
    topAppBarOverviewTitle = "概览",
    topAppBarCalendarIconDesc = "选择日期",
    topAppBarMenuIconDesc = "打开菜单",
    agendaTabTitle = "日程",
    timelineTabTitle = "时间轴",
    timelineTaskMoveIconDesc = "移动任务",
    timelineTaskEditCancelIconDesc = "结束时间编辑",
    timelineNowTitle = "现在",
    nextDateIconDesc = "下一日期",
    previousDateIconDesc = "上一日期",
    dateDialogPickerHeadline = "选择日期",
    dateDialogPickerTitle = "每日计划",
    timeTaskMoreIconDesc = "编辑",
    timeTaskAddIconDesc = "增加时间",
    timeTaskRemoveIconDesc = "减少时间",
    timeTaskIncreaseTimeTitle = "增加",
    timeTaskReduceTimeTitle = "减少",
    addFreeTimeTaskTitle = "未分配",
    addTaskTitle = "添加任务",
    createScheduleTitle = "创建",
    createScheduleDesc = "为所选日期创建计划",
    shiftError = "无法调整时间！",
    importanceError = "下一个任务优先级更高！",
    otherError = "出现问题。请联系开发者获取帮助。",
    noteTitle = "备注",
    noneTitle = "无",
)

internal val LocalHomeStrings = staticCompositionLocalOf<HomeStrings> {
    error("Home Strings is not provided")
}

internal fun fetchHomeStrings(language: TimePlannerLanguage) = when (language) {
    TimePlannerLanguage.EN -> englishHomeString
    TimePlannerLanguage.RU -> russianHomeString
    TimePlannerLanguage.DE -> germanHomeString
    TimePlannerLanguage.ES -> spanishHomeString
    TimePlannerLanguage.FA -> persianHomeString
    TimePlannerLanguage.FR -> frenchHomeString
    TimePlannerLanguage.PT_BR -> brazilianPortugueseHomeString
    TimePlannerLanguage.TR -> turkishHomeString
    TimePlannerLanguage.VN -> vietnameseHomeString
    TimePlannerLanguage.PL -> polishHomeString
    TimePlannerLanguage.IT -> italianHomeString
    TimePlannerLanguage.ZH -> chineseHomeString
}
