/*
 * Copyright 2023 Stanislav Aleshin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * imitations under the License.
 */
package ru.aleshin.features.home.impl.presentation.theme.tokens

import androidx.compose.runtime.staticCompositionLocalOf
import ru.aleshin.core.ui.theme.tokens.TimePlannerLanguage

/**
 * @author Stanislav Aleshin on 18.02.2023.
 */
internal data class HomeStrings(
    val topAppBarHomeTitle: String,
    val topAppBarCategoriesTitle: String,
    val mainCategoryTitle: String,
    val topAppBarCalendarIconDesc: String,
    val topAppBarMenuIconDesc: String,
    val nextDateIconDesc: String,
    val previousDateIconDesc: String,
    val dateDialogPickerHeadline: String,
    val dateDialogPickerTitle: String,
    val timeTaskExpandedIconDesc: String,
    val timeTaskCheckIconDesc: String,
    val timeTaskMoreIconDesc: String,
    val timeTaskAddIconDesc: String,
    val timeTaskRemoveIconDesc: String,
    val timeTaskIncreaseTimeTitle: String,
    val timeTaskReduceTimeTitle: String,
    val startTimeTaskTitlePlaceHolder: String,
    val addTimeTaskIconsDesc: String,
    val addTimeTaskTitle: String,
    val topAppBarBackIconDesc: String,
    val topAppBarMoreIconDesc: String,
    val topAppBarTemplatesTitle: String,
    val mainCategoryChooserTitle: String,
    val subCategoryChooserTitle: String,
    val subCategoryDialogMainCategoryFormat: String,
    val emptyScheduleTitle: String,
    val createScheduleTitle: String,
    val createScheduleDesc: String,
    val shiftError: String,
    val importanceError: String,
    val otherError: String,
    val addSubCategoryTitle: String,
    val categoryFieldLabel: String,
    val dialogCreateTitle: String,
    val emptyListTitle: String,
    val updateCategoryTitle: String,
    val deleteCategoryTitle: String,
    val subCategoryTitle: String,
    val warningDeleteCategoryText: String,
    val sortedTypeTitle: String,
    val sortedTypeDate: String,
    val sortedTypeCategories: String,
    val sortedTypeDuration: String,
    val notificationEnabledTitle: String,
    val notificationDisabledTitle: String,
    val statisticsActiveTitle: String,
    val statisticsDisabledTitle: String,
    val addTemplatesFabTitle: String,
    val templateEditorHeader: String,
    val mainCategoryLabel: String,
    val subCategoryLabel: String,
    val startTimeLabel: String,
    val endTimeLabel: String,
    val notificationLabel: String,
    val statisticsLabel: String,
    val importanceLabel: String,
    val subCategoryEmptyTitle: String,
    val addCategoryTitle: String,
    val nameCategoryTitle: String,
)

internal val russianHomeString = HomeStrings(
    topAppBarHomeTitle = "Главная",
    topAppBarCategoriesTitle = "Категории",
    mainCategoryTitle = "Основная",
    topAppBarCalendarIconDesc = "Выбрать дату",
    topAppBarMenuIconDesc = "Открыть меню",
    nextDateIconDesc = "Следующая дата",
    previousDateIconDesc = "Предыдущая дата",
    dateDialogPickerHeadline = "Выберите дату",
    dateDialogPickerTitle = "Дневной план",
    timeTaskExpandedIconDesc = "Дополнительно",
    timeTaskCheckIconDesc = "Выполнено",
    timeTaskMoreIconDesc = "Редактировать",
    timeTaskAddIconDesc = "Добавить время",
    timeTaskRemoveIconDesc = "Убавить время",
    timeTaskIncreaseTimeTitle = "Увеличить",
    timeTaskReduceTimeTitle = "Убавить",
    startTimeTaskTitlePlaceHolder = "00:00",
    addTimeTaskIconsDesc = "Добавить задачу",
    addTimeTaskTitle = "Свободное время",
    topAppBarBackIconDesc = "Назад",
    topAppBarMoreIconDesc = "Дополнительно",
    topAppBarTemplatesTitle = "Шаблоны",
    mainCategoryChooserTitle = "Категория",
    subCategoryChooserTitle = "Подкатегория",
    subCategoryDialogMainCategoryFormat = "Категория: %s",
    emptyScheduleTitle = "План отсутствует",
    createScheduleTitle = "Создать",
    createScheduleDesc = "Создать план для выбранного дня",
    shiftError = "Сдвиг невозможен!",
    importanceError = "Следующая задача приоритетней!",
    otherError = "Ошибка! Обратитесь к разработчику.",
    addSubCategoryTitle = "Добавить подкатегорию",
    categoryFieldLabel = "Название",
    dialogCreateTitle = "Создать",
    emptyListTitle = "Список пуст",
    updateCategoryTitle = "Редактировать",
    deleteCategoryTitle = "Удалить",
    subCategoryTitle = "Подкатегории",
    warningDeleteCategoryText = "Вы уверены что хотите удалить основную категорию? " +
        "Данное действие приведёт к уничтожению всех ранее запланированных задач.",
    sortedTypeTitle = "Сортировать",
    sortedTypeDate = "По дате",
    sortedTypeCategories = "По категориям",
    sortedTypeDuration = "По длительности",
    notificationEnabledTitle = "Включено",
    notificationDisabledTitle = "Выключено",
    statisticsActiveTitle = "Активна",
    statisticsDisabledTitle = "Выключена",
    addTemplatesFabTitle = "+",
    templateEditorHeader = "Шаблон",
    mainCategoryLabel = "Категория",
    subCategoryLabel = "Подкатегория",
    startTimeLabel = "Начало",
    endTimeLabel = "Конец",
    notificationLabel = "Отправка уведомлений",
    statisticsLabel = "Учёт статистики",
    importanceLabel = "Высокий приоритет",
    subCategoryEmptyTitle = "Отсутствует",
    addCategoryTitle = "Добавить",
    nameCategoryTitle = "Название",
)

internal val englishHomeString = HomeStrings(
    topAppBarHomeTitle = "Home",
    topAppBarCategoriesTitle = "Categories",
    mainCategoryTitle = "Main",
    topAppBarCalendarIconDesc = "Select a date",
    topAppBarMenuIconDesc = "Open menu",
    nextDateIconDesc = "Next date",
    previousDateIconDesc = "Previous date",
    dateDialogPickerHeadline = "Select a date",
    dateDialogPickerTitle = "Daily plan",
    timeTaskExpandedIconDesc = "More",
    timeTaskCheckIconDesc = "Completed",
    timeTaskMoreIconDesc = "Edit",
    timeTaskAddIconDesc = "Add time",
    timeTaskRemoveIconDesc = "Reduce the time",
    timeTaskIncreaseTimeTitle = "Increase",
    timeTaskReduceTimeTitle = "Reduce",
    startTimeTaskTitlePlaceHolder = "00:00",
    addTimeTaskIconsDesc = "Add task",
    addTimeTaskTitle = "Free time",
    topAppBarBackIconDesc = "Back",
    topAppBarMoreIconDesc = "More",
    topAppBarTemplatesTitle = "Templates",
    mainCategoryChooserTitle = "Category",
    subCategoryChooserTitle = "Subcategory",
    subCategoryDialogMainCategoryFormat = "Category: %s",
    emptyScheduleTitle = "Nothing planned yet",
    createScheduleTitle = "Plan now",
    createScheduleDesc = "Create a plan for the selected day",
    shiftError = "Shifting is not possible!",
    importanceError = "The next task takes more priority!",
    otherError = "Error! Contact the developer.",
    addSubCategoryTitle = "Add subcategory",
    categoryFieldLabel = "Name",
    dialogCreateTitle = "Create",
    emptyListTitle = "List is empty",
    updateCategoryTitle = "Edit",
    deleteCategoryTitle = "Remove",
    subCategoryTitle = "Subcategories",
    warningDeleteCategoryText = "Are you sure you want to delete the main category? " +
        "This action will destroy all previously scheduled tasks.",
    sortedTypeTitle = "Sorted",
    sortedTypeDate = "By date",
    sortedTypeCategories = "By category",
    sortedTypeDuration = "By duration",
    notificationEnabledTitle = "Enabled",
    notificationDisabledTitle = "Disabled",
    statisticsActiveTitle = "Active",
    statisticsDisabledTitle = "Disabled",
    addTemplatesFabTitle = "+",
    templateEditorHeader = "Template",
    mainCategoryLabel = "Category",
    subCategoryLabel = "Subcategory",
    startTimeLabel = "Start",
    endTimeLabel = "End",
    notificationLabel = "Sending notification",
    statisticsLabel = "Include task in statistics",
    importanceLabel = "High priority",
    subCategoryEmptyTitle = "Absent",
    addCategoryTitle = "Add",
    nameCategoryTitle = "Name",
)

internal val germanHomeString = HomeStrings(
    topAppBarHomeTitle = "Hauptseite",
    topAppBarCategoriesTitle = "Kategorien",
    mainCategoryTitle = "Hauptkategorie",
    topAppBarCalendarIconDesc = "Datum auswählen",
    topAppBarMenuIconDesc = "Menü öffnen",
    nextDateIconDesc = "Nächstes Datum",
    previousDateIconDesc = "Vorheriges Datum",
    dateDialogPickerHeadline = "Datum auswählen",
    dateDialogPickerTitle = "Tagesplan",
    timeTaskExpandedIconDesc = "Zusätzlich",
    timeTaskCheckIconDesc = "Erfüllt",
    timeTaskMoreIconDesc = "Redigieren",
    timeTaskAddIconDesc = "Zeit hinzufügen",
    timeTaskRemoveIconDesc = "Zeit reduzieren",
    timeTaskIncreaseTimeTitle = "Vergrößern",
    timeTaskReduceTimeTitle = "Verringern",
    startTimeTaskTitlePlaceHolder = "00:00",
    addTimeTaskIconsDesc = "Aufgabe hinzufügen",
    addTimeTaskTitle = "Freizeit",
    topAppBarBackIconDesc = "Zurück",
    topAppBarMoreIconDesc = "Zusätzlich",
    topAppBarTemplatesTitle = "Muster",
    mainCategoryChooserTitle = "Kategorie",
    subCategoryChooserTitle = "Unterkategorie",
    subCategoryDialogMainCategoryFormat = "Kategorie: %s",
    emptyScheduleTitle = "Kein Plan",
    createScheduleTitle = "Schaffen",
    createScheduleDesc = "Einen Plan für den ausgewählten Tag erstellen",
    shiftError = "Keine Verschiebung möglich!",
    importanceError = "Die nächste Aufgabe hat Priorität!",
    otherError = "Fehler! Wenden Sie sich an den Entwickler.",
    addSubCategoryTitle = "Unterkategorie hinzufügen",
    categoryFieldLabel = "Name",
    dialogCreateTitle = "Schaffen",
    emptyListTitle = "Die Liste ist leer",
    updateCategoryTitle = "Redigieren",
    deleteCategoryTitle = "Entfernen",
    subCategoryTitle = "Unterkategorien",
    warningDeleteCategoryText = "Sind Sie sicher, dass Sie die Hauptkategorie löschen möchten? " +
        "Durch diese Aktion werden alle zuvor geplanten Aufgaben gelöscht.",
    sortedTypeTitle = "Sortieren",
    sortedTypeDate = "Nach Datum",
    sortedTypeCategories = "Nach Kategorie",
    sortedTypeDuration = "Nach Dauer",
    notificationEnabledTitle = "Eingeschaltet",
    notificationDisabledTitle = "Abgeschaltet",
    statisticsActiveTitle = "Aktiv",
    statisticsDisabledTitle = "Abgeschaltet",
    addTemplatesFabTitle = "+",
    templateEditorHeader = "Muster",
    mainCategoryLabel = "Kategorie",
    subCategoryLabel = "Unterkategorie",
    startTimeLabel = "Anfang",
    endTimeLabel = "Das Ende",
    notificationLabel = "Benachrichtigungen",
    statisticsLabel = "Statistik",
    importanceLabel = "Hohe Priorität",
    subCategoryEmptyTitle = "Fehlt",
    addCategoryTitle = "Hinzufügen",
    nameCategoryTitle = "Name",
)

internal val LocalHomeStrings = staticCompositionLocalOf<HomeStrings> {
    error("Home Strings is not provided")
}

internal fun fetchHomeStrings(language: TimePlannerLanguage) = when (language) {
    TimePlannerLanguage.EN -> englishHomeString
    TimePlannerLanguage.RU -> russianHomeString
    TimePlannerLanguage.DE -> germanHomeString
}
